### PR TITLE
fix: Can not add properties in "SetProperties" action

### LINKED ISSUE #4526: Can not add properties in "SetProperties" action
## Describe the bug

Can not add properties in "SetProperties" action

## Version

Latest Main 

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. add "SetProperties" action
2. in Property view, click "add" to add an empty property
3. edit property will remove this property

## Expected behavior

I should change the type of this property

### PR DESCRIPTION
**Pull request by LouisEugeneMSFT**
## Description

**SetProperties** leverages the **ArrayFieldItem** component. On blur, the item is removed if it has an empty value:
image

The children of **SetProperties** rely on Intellisense fields. But the onBlur callback was not passed in the array of dependency of the useEffect responsible for managing Intellisense blur. Therefore the initial (empty) value was used and always removed the item, regardless of the current real value. Adding to the array of dependency fixed the issue.

This PR also contains some minor optimizations (rendering and listeners) for Intellisense.

closes #4526 

## Screenshots

image

### CODE REVIEW

File: Composer/packages/adaptive-form/src/components/fields/IntellisenseFields.tsx [hunk 1]
```diff
@@ -22,6 +22,8 @@ export const IntellisenseTextField: React.FC<FieldProps<string>> = (props) => {
   const scopes = uiOptions.intellisenseScopes || [];
   const intellisenseServerUrlRef = useRef(getIntellisenseUrl());
 
+  const noop = useCallback(() => {}, []);
```
Comment (hatpick) [inline Composer/packages/adaptive-form/src/components/fields/IntellisenseFields.tsx:25]: DRY: you can define a noop outside all these components and use it.

**Review by hatpick — CHANGES_REQUESTED** [review]

**Review by GeoffCoxMSFT — APPROVED** [review]

File: Composer/packages/adaptive-form/src/components/fields/IntellisenseFields.tsx [hunk 2]
```diff
@@ -3,7 +3,7 @@
 
 import { FieldProps } from '@bfc/extension-client';
 import { Intellisense } from '@bfc/intellisense';
-import React, { useRef } from 'react';
+import React, { useRef, useCallback } from 'react';
```
Comment (hatpick) [inline Composer/packages/adaptive-form/src/components/fields/IntellisenseFields.tsx:6]: remove

File: Composer/packages/intellisense/src/components/Intellisense.tsx [hunk 3]
```diff
@@ -97,21 +97,28 @@ export const Intellisense = React.memo(
...
+      document.body.addEventListener('click', outsideClickHandler);
+
+      return () => {
+        document.body.removeEventListener('click', outsideClickHandler);
+      };
+    }, [focused, onBlur]);
+
+    // Closes the list of completion items if user presses "Escape"
+    React.useEffect(() => {
       const keyupHandler = (event: KeyboardEvent) => {
```
Comment (hatpick) [inline Composer/packages/intellisense/src/components/Intellisense.tsx:109]: check for focused here?

**Review by hatpick — CHANGES_REQUESTED** [review]

**Review by hatpick — APPROVED** [review]
