### PR TITLE
fix: Composer nav + button discoverability

### LINKED ISSUE #5680: Composer nav + button discoverability
The + button in the composer nav is not discoverable and is creating friction while trying to add skills.
the create dialog and trigger icons in the three dot menu though contextual is hard to discover 

image

Suggested fix:

image

### PR DESCRIPTION
**Pull request by lei9444**
## Description
new Design: https://www.figma.com/file/deFhMPBnRWxTYiYDYqYxrc/Composer---Vivek?node-id=10809%3A0
image

filter1

This PR also fix one bug. The bug is the filter is used in some function, and the function can only get the stale value, so when we input the text into the search box, The filter doesn't work
image
In this PR use Ref to make sure the value is latest.

## Task Item
closes #5680

### CODE REVIEW

**Review by boydc2014 — APPROVED** [review]

**Comment by hatpick** [comment]
Does this PR also solve the following issue:
(header of project tree is scrolling with it)
https://user-images.githubusercontent.com/1483492/107267236-74aaf200-69fb-11eb-98fe-25a59ecddde4.mov

**Comment by liweitian** [comment]
> Does this PR also solve the following issue:
> (header of project tree is scrolling with it)
> https://user-images.githubusercontent.com/1483492/107267236-74aaf200-69fb-11eb-98fe-25a59ecddde4.mov

From the design, the header is removed. @vivekkshankar could you help verify on this? The search bar is also changed on lu/lg/qna page. Should we do that?

File: Composer/packages/client/src/components/ProjectTree/ProjectTreeHeader.tsx [hunk 1]
```diff
@@ -51,54 +118,47 @@ export const ProjectTreeHeader: React.FC<ProjectTreeHeaderProps> = ({ menu }) =>
...
+          ariaLabel={formatMessage('Type trigger name')}
+          componentRef={searchBoxRef}
+          iconProps={{ iconName: 'Filter' }}
+          placeholder={formatMessage('Filter by trigger name')}
+          styles={searchBox}
+          onBlur={handleSearchBoxBlur}
+          onChange={onFilter}
+        />
+      ) : (
         <OverflowSet
```
Comment (hatpick) [inline Composer/packages/client/src/components/ProjectTree/ProjectTreeHeader.tsx:140]: why do you need this overflow set? Simply used a commandbar button
(https://developer.microsoft.com/en-us/fluentui#/controls/web/button)

File: Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx [hunk 2]
```diff
@@ -197,6 +187,8 @@ export const ProjectTree: React.FC<Props> = ({
   const setPageElement = (name: string, value) => setPageElementState('dialogs', { ...pageElements, [name]: value });
 
   const [filter, setFilter] = useState('');
+  const filterRef = useRef(filter);
```
Comment (hatpick) [inline Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx:190]: I dont understand what's happening with this ref, what does it represent? and why is it needed?

File: Composer/packages/client/src/components/ProjectTree/ProjectTreeHeader.tsx [hunk 3]
```diff
@@ -34,9 +51,59 @@ export interface ProjectTreeHeaderMenuItem {
 
 export interface ProjectTreeHeaderProps {
   menu: ProjectTreeHeaderMenuItem[];
+  onFilter?: (_e, newValue?: string) => void;
```
Comment (hatpick) [inline Composer/packages/client/src/components/ProjectTree/ProjectTreeHeader.tsx:54]: if you dont want to use the event why are you including it in the callback?

File: Composer/packages/client/src/components/ProjectTree/ProjectTreeHeader.tsx [hunk 4]
```diff
@@ -3,27 +3,44 @@
...
+    width: '100%',
+  },
+};
+
+const buttonStyle = css`
+  height: 100%;
+`;
 
 const headerText = css`
+  border-bottom: 1px solid #edebe9;
```
Comment (hatpick) [inline Composer/packages/client/src/components/ProjectTree/ProjectTreeHeader.tsx:28]: use a color from Fluent instead of hard coding it

File: Composer/packages/client/src/components/ProjectTree/ProjectTreeHeader.tsx [hunk 5]
```diff
@@ -3,27 +3,44 @@
...
-import { TooltipHost, DirectionalHint } from 'office-ui-fabric-react/lib/Tooltip';
+import { CommandButton } from 'office-ui-fabric-react/lib/Button';
+import { IOverflowSetItemProps, OverflowSet } from 'office-ui-fabric-react/lib/OverflowSet';
 import { IContextualMenuItem } from 'office-ui-fabric-react/lib/ContextualMenu';
+import { ISearchBox, ISearchBoxStyles, SearchBox } from 'office-ui-fabric-react/lib/SearchBox';
 
-import { moreButton, overflowSet } from './treeItem';
+const searchBox: ISearchBoxStyles = {
+  root: {
+    borderBottom: '1px solid #edebe9',
```
Comment (hatpick) [inline Composer/packages/client/src/components/ProjectTree/ProjectTreeHeader.tsx:16]: same here for the color
https://developer.microsoft.com/en-us/fluentui#/styles/web/colors/neutrals
gray30

File: Composer/packages/client/src/components/ProjectTree/ProjectTreeHeader.tsx [hunk 6]
```diff
@@ -34,9 +51,59 @@ export interface ProjectTreeHeaderMenuItem {
...
+      text={item.name}
+      onClick={item.onClick}
+    />
+  );
+};
+
+const onRenderOverflowButton = (isActive: boolean) => {
+  const moreLabel = formatMessage('Actions');
+  return (overflowItems: IContextualMenuItem[] | undefined) => {
+    if (overflowItems == null) return null;
```
Comment (hatpick) [inline Composer/packages/client/src/components/ProjectTree/ProjectTreeHeader.tsx:76]: if(!overflowItems) {
   return null;
}

nit: avoid using Abstract Equality Comparison (==) vs. ===

**Review by hatpick — CHANGES_REQUESTED** [review]

**Comment by hatpick** [comment]
> > Does this PR also solve the following issue:
> > (header of project tree is scrolling with it)
> > https://user-images.githubusercontent.com/1483492/107267236-74aaf200-69fb-11eb-98fe-25a59ecddde4.mov
> 
> @hatpick From the design, the header is removed. @vivekkshankar could you help verify on this? The search bar is also changed on lu/lg/qna page. Should we do that?

When the project tree list is long and user scrolls, the "header" that you have add button and filtering in it will scroll oit of view with it, @vivekkshankar is that what you wanted for ux?

File: Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx (hunk 2 above)
Comment (lei9444) [reply Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx:190]: Hi, @hatpick , There is bug in main branch, I fixed it in this PR. The bug is the filter doesn't work when we input some text. The reason is I found the filter text is used in a function, but react will use the stale value anytime
image

**Comment by lei9444** [comment]
> > > Does this PR also solve the following issue:
> > > (header of project tree is scrolling with it)
> > > https://user-images.githubusercontent.com/1483492/107267236-74aaf200-69fb-11eb-98fe-25a59ecddde4.mov
> > 
> > 
> > @hatpick From the design, the header is removed. @vivekkshankar could you help verify on this? The search bar is also changed on lu/lg/qna page. Should we do that?
> 
> When the project tree list is long and user scrolls, the "header" that you have add button and filtering in it will scroll out of the viewport, @lei9444 @vivekkshankar is that what you wanted for ux?

Hi, @hatpick I think we need to fix the header, I have fixed in this PR 
image

File: Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx (hunk 2 above)
Comment (hatpick) [reply Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx:196]: I have created a hook in my local branch for another feature:
```
export const useDebounce = <T>(value: T, delay: number) => {
  const [debouncedValue, setDebouncedValue] = useState<T>(value);

  useEffect(() => {
    const handler = setTimeout(() => {
      setDebouncedValue(value);
    }, delay);

    return () => {
      clearTimeout(handler);
    };
  }, [value]);

  return debouncedValue;
};
```
you can consume it for this exact case like:
```
const [query, setQuery] = React.useState<string | undefined>();
const debouncedQuery = useDebounce<string | undefined>(query, 300);
```

and then you deal with ```debouncedQuery```

wanna give it a try? if it works as expected you can add that hook to share library so others can use it too.

**Comment by srinaath** [comment]
@hatpick Are we good with this PR? It removes a P0 of our plate.

File: Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx (hunk 2 above)
Comment (lei9444) [reply Composer/packages/client/src/components/ProjectTree/ProjectTree.tsx]: Thanks @hatpick , I think I didn't explain the issue very clearly. 
I think there is a wrong usage in < ProjectTree />: Some children components will use the filter message to re-render the UI, but all these components will call a function from parent to filter their items and they don't depends on the filter message change, so the function will only use the stale value. 

So I think I just need to listen to the filter state and re-render these components when filter change. I fixed it in the latest commit and removed the Ref.

I think it's a good idea to share the useDebounce to the library, the filter state in ProjectTree also use a  similar implementation with throttle. Can we do this in a new PR?

**Review by cwhitten — APPROVED** [review]
