### PR TITLE
fix: Fixed useArrayItems and useObjectItems

### LINKED ISSUE #4276: Property page for new action not displayed
## Describe the bug

This probably isn't an easy repo as I think it's the first time I've ever seen it happen but I just added a new `SetProperties` action and composer is still showing the previous actions property editor. Clicking to another action and back resolved the issue:

image

## Version

1.1.1

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

### PR DESCRIPTION
**Pull request by tdurnford**
## Description
When the Property Editor switches between two actions of the same type, the `useArrayItems` and `useObjectItems` caches were not resetting. 

## Task Item
Closes #4276

### CODE REVIEW

File: Composer/packages/adaptive-form/src/utils/arrayUtils.ts [hunk 1]
```diff
@@ -78,6 +79,19 @@ export function useArrayItems<ItemType = unknown>(
 ): ArrayItemState<ItemType> {
   const [cache, setCache] = useState(generateArrayItems(items));
 
+  useEffect(() => {
+    const newCache = generateArrayItems(items);
+
+    if (
+      !isEqual(
+        cache.map(({ value }) => value),
```
Comment (srinaath) [inline Composer/packages/adaptive-form/src/utils/arrayUtils.ts:87]: This could yield undefined === undefined right?

Comment (srinaath) [inline Composer/packages/adaptive-form/src/utils/arrayUtils.ts:87]: This could yield undefined === undefined right?

Comment (tdurnford) [reply Composer/packages/adaptive-form/src/utils/arrayUtils.ts:87]: I don't think so. If a value is `undefined`, the Adaptive Form removes it from the array.

**Review by srinaath — APPROVED** [review]
