### PR TITLE
fix: Empty Webchat inspector text and Disabling items in PVA context

### LINKED ISSUE #6824: Outputs window needs scroll-bars to view larger issues - e.g. stack trace
## Describe the bug

Larger error messages in the outputs window can't be viewed fully due to lack of scrollbars or similar.

## Version

1.4.0.nightly-233315

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. See screenshot for an example error shown after an issue with starting a new project (#6823) but other repros will exist. 

## Expected behavior

Be able to scroll and see the whole text without having to copy to clipboard and view elsewhere

## Screenshots

image

### LINKED ISSUE #7077: Discoverability: On clicking "webchat" icon, initiate 'Start bot' if it's not already running
When the user has not yet clicked 'start run bots', the webchat button is disabled, and in the diagnostics panel, webchat says ' No Web Chat activity yet ' but nothing is actionable so the user has to figure out what it's not working.

Expected:

1. Enable the 'webchat' icon and if the bot is not running yet, initiate "start run" automatically.
2. In the diagnostics panel, have an actionable item that initiates the bot running and shows the webchat.
. Startbot_automatically_for_webchat
3. In the diagnostics panel, update the font size to be the same size as the label vs a large font size.
ReduceFontsize_error_or_status_message
7. 
8. 
9.

### PR DESCRIPTION
**Pull request by srinaath**
## Description

1.  Fixes the scroll issue in Error Callout
2.  Adds UI text to webchat inspector when no activity present.
3.  Disabling Connections, AppInsights and Packages in PVA context

## Task Item

Fixes #7077 
Fixes #6824

## Screenshots

Screen Shot 2021-04-21 at 12 27 30 PM

  
 

Screen Shot 2021-04-21 at 12 27 01 PM

### CODE REVIEW

File: Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebChatLog/WebChatLogContent.tsx [hunk 1]
```diff
@@ -160,14 +179,39 @@ export const WebChatLogContent: React.FC<DebugPanelTabHeaderProps> = ({ isActive
...
   };
 
+  const onOpenWebChatPanelClick = () => {
+    setWebChatPanelVisibility(true);
+  };
+
+  const noWebChatTrafficSection = useMemo(() => {
+    if (currentStatus === BotStatus.inactive) {
+      return (
+        <div css={emptyStateMessageContainer}>
```
Comment (hatpick) [inline Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebChatLog/WebChatLogContent.tsx:189]: nit: highly recommend using formatMessage.rich for this and the following on L200

**Review by hatpick — DISMISSED** [review]

**Comment by cwhitten** [comment]
@srinaath I don't see this guarded with the disabled PVA check

**Comment by srinaath** [comment]
Shoot. Nice catch @cwhitten I have it in my todo list. Forgot to work that item.

**Review by a-b-r-o-w-n — APPROVED** [review]
