### PR TITLE
fix: Update attachment template format to support PVA

### LINKED ISSUE #7394: PVA: Valid adaptive card json prevents publishing to PVA
## Repro
* Create a non-PVA bot with adaptive card, test that it works.
* Create a PVA bot, switch to advanced authoring with composer
* Reproduce the adaptive card in PVA bot
* Publish

## Error
```
"severity": "Error",
"source": "MoodCheckerDialog.en-us.lg",
"message": "Error occurred when parsing expression 'json({\r\n \"$schema\": \"http://adaptivecards.io/schemas/adaptive-card.json\",\r\n \"version\": \"1.2\",\r\n \"type\": \"AdaptiveCard\",\r\n \"body\": [\r\n {\r\n \"type\": \"Container\",\r\n \"items\": [\r\n {\r\n \"type\": \"ColumnSet\",\r\n \"columns\": [\r\n {\r\n \"type\": \"Column\",\r\n \"width\": \"auto\",\r\n \"items\": [\r\n {\r\n \"type\": \"Image\",\r\n \"url\": \"https://metatour.azurewebsites.net/img/happy.png\",\r\n \"size\": \"small\"\r\n '. missing '}' at '<EOF>'"
}
---
```

## Sample JSON
```
# SendActivity_kUwtny()
[Activity
    Attachments = ${SendActivity_kUwtny_attachment_fpA8bl()}
]

# SendActivity_kUwtny_attachment_fpA8bl()
> To learn more Adaptive Cards format, read the documentation at
> https://docs.microsoft.com/en-us/adaptive-cards/getting-started/bots
- \```${json({
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.2",
  "type": "AdaptiveCard",
  "body": [
    {
        "type": "Container",
        "items": [
          {
            "type": "ColumnSet",
            "columns": [
              {
                "type": "Column",
                "width": "auto",
                "items": [
                  {
                    "type": "Image",
                    "url": "https://metatour.azurewebsites.net/img/sad.png",
                    "size": "small"
                  }
                ]
              },
              {
                "type": "Column",
                "width": "stretch",
                "items": [
                  {
                    "type": "TextBlock",
                    "text": "I'm sorry to hear that. Feel better soon.",
                    "weight": "bolder",
                    "wrap": true,
                    "BlockElementHeight" : "stretch"
                  }
                ]
              }
            ]
          }
        ]
    }
  ]
})}\```
(backslash inserted for rendering in issue comment)
```

### PR DESCRIPTION
**Pull request by tdurnford**
## Description
Updates the adaptive card template and how attachments are formatted in activity templates to support PVA.

## Task Item
Closes #7394

### CODE REVIEW

File: Composer/.prettierignore [hunk 1]
```diff
@@ -1,3 +1,2 @@
 node_modules
```
Comment (hatpick) [inline Composer/.prettierignore:1]: remove this change, I have another PR for this open

File: Composer/packages/client/src/shell/utils.ts [hunk 2]
```diff
@@ -44,9 +44,8 @@ export const serializeLgTemplate = (
           ? (lgTemplate.properties[responseType] as string[])
           : ([lgTemplate.properties[responseType]] as string[]);
         for (const subTemplateItem of subTemplateItems) {
-          const matched = subTemplateItem.trim().match(exprRegex);
-          if (matched && matched.length > 1) {
-            const subTemplateId = matched[1];
+          const subTemplateId = extractTemplateNameFromExpression(subTemplateItem.trim());
```
Comment (hatpick) [inline Composer/packages/client/src/shell/utils.ts:47]: remove unused variable exprRegex

File: Composer/packages/lib/code-editor/src/utils/structuredResponse.ts [hunk 3]
```diff
@@ -1,7 +1,8 @@
 // Copyright (c) Microsoft Corporation.
 // Licensed under the MIT License.
+/* eslint-disable security/detect-unsafe-regex */
```
Comment (hatpick) [inline Composer/packages/lib/code-editor/src/utils/structuredResponse.ts:3]: move this to be for line 23 (if even needed)

File: Composer/packages/lib/shared/src/lgUtils/stringBuilders/lgStringUtils.ts [hunk 4]
```diff
@@ -106,3 +106,17 @@ export const templateBodyItemsToString = (items: TemplateBodyItem[]) =>
       }
     })
     .join('\n');
+
```
Comment (hatpick) [inline Composer/packages/lib/shared/src/lgUtils/stringBuilders/lgStringUtils.ts:109]: add tests

**Review by hatpick — CHANGES_REQUESTED** [review]

**Review by hatpick — DISMISSED** [review]

**Review by hatpick — APPROVED** [review]
