### PR TITLE
fix: set func-related settings during build step

### LINKED ISSUE #7691: Functions bots do not work when running locally (LUIS, QNA and other settings are not properly received)
## Describe the bug
Dotnet function bots throw an invalid LUIS subscription key error when trying to call LUIS

## Version
Version:  2.0.0-nightly.243234.8264ac4
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

**Updated**
1. create empty dotnet bot
2. add and wire up echo intent
3. create provisioning profile and publish bot (step that was missing)
4. start bot
5. send intent message

## Expected behavior
The call should go through

## Screenshots
image

## Additional context
The fix for this issue is probably similar to the fix for [this issue](https://github.com/microsoft/BotFramework-Composer/issues/7602) since the errors are fairly similar.

### PR DESCRIPTION
**Pull request by benbrown**
## Description

In order to pass the "sensitive" values to the functions version of the runtime, Composer needs to call some additional commands to set special environment variables for the function runtime.  This is done by calling `func settings add [key] [value]` for each key need to pass --- in this case, the luis endpoint key, qna endpoint key, app password, and skill host endpoint URL.   

These are otherwise passed as command line parameters to the webapp runtime.

## Task Item

Fixes #7691

### CODE REVIEW

File: extensions/localPublish/src/index.ts [hunk 1]
```diff
@@ -130,6 +130,19 @@ class LocalPublisher implements PublishPlugin<PublishConfig> {
 
   private publishAsync = async (botId: string, version: string, fullSettings: any, project: any, user) => {
     try {
+      let port;
```
Comment (benbrown) [inline extensions/localPublish/src/index.ts:133]: Needed to move the port selection up in the code a bit so that it can be passed to the build step.

File: extensions/runtimes/src/index.ts [hunk 2]
```diff
@@ -14,6 +14,50 @@ import { IFileStorage } from './interface';
...
+/**
+ * Used to set values for Azure Functions runtime environment variables
+ * This is used to set the "sensitive values" when using Azure Functions
+ * @param name name of key
+ * @param value value of key
+ * @param cwd path where the command will be run
+ */
+const writeLocalFunctionsSetting = async (name: string, value: string, cwd: string) => {
+  // only set if there is both a setting and a value.
+  if (name && value && cwd) {
```
Comment (hatpick) [inline extensions/runtimes/src/index.ts:26]: I suggest adding a log to this function in case of failure we can use

**Review by cwhitten — COMMENTED** [review]
Just a couple items. 

What I'd like to see post-BUILD is a loader pattern that can be injected into this path that encapsulates the read/write complexity & differences between execution environments (webapps, functions, etc).

File: extensions/runtimes/src/index.ts [hunk 3]
```diff
@@ -456,10 +500,15 @@ export default async (composer: any): Promise<void> => {
     name: 'C# - Functions',
     // startCommand: 'dotnet run',
     // path: dotnetTemplatePath,
-    build: async (runtimePath: string, _project: any) => {
-      composer.log(`BUILD THIS C# PROJECT! at ${runtimePath}...`);
+    build: async (runtimePath: string, _project: any, fullSettings?: any, port?: string) => {
```
Comment (hatpick) [inline extensions/runtimes/src/index.ts:503]: nit: If both of these new args always appear together, it's better to put them under one single optional arg.
It will have the added benefit of named args.

p.s: seems like project is prefixed with _ which perhaps means that it's not used.

File: Composer/packages/types/src/runtime.ts [hunk 4]
```diff
@@ -63,7 +63,7 @@ export type RuntimeTemplate = {
   eject?: (project: IBotProject, localDisk?: any, isReplace?: boolean) => Promise<string>;
 
   /** build method used for local publish */
-  build: (runtimePath: string, project: IBotProject) => Promise<void>;
+  build: (runtimePath: string, project: IBotProject, fullSettings?: DialogSetting, port?: string) => Promise<void>;
```
[the remark this answers is not in the document]
Comment (joshgummersall) [reply Composer/packages/types/src/runtime.ts:66]: Windows app services listen on a named pipe which is expressed as a string. Unix sockets are also strings.

**Comment by joshgummersall** [comment]
Just generated a Node.js Core + Language bot, the `local.settings.json` file was updated with settings and the bot is running!

File: Composer/packages/types/src/runtime.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (joshgummersall) [reply Composer/packages/types/src/runtime.ts:66]: Doubtful, but if this code interacts with deployments at all it may be wise to keep that option open. If it's purely for local execution of bots, good chance you can limit it to numbers.

File: extensions/localPublish/src/index.ts [hunk 5]
```diff
@@ -130,6 +130,19 @@ class LocalPublisher implements PublishPlugin<PublishConfig> {
 
   private publishAsync = async (botId: string, version: string, fullSettings: any, project: any, user) => {
```
[the remark this answers is not in the document]
Comment (benbrown) [reply extensions/localPublish/src/index.ts:131]: yes I will update this and other instances that should be typed.

File: extensions/runtimes/src/index.ts (hunk 3 above)
Comment (benbrown) [reply extensions/runtimes/src/index.ts]: I updated the _projects to remove the underscore where the parameter is now in play

File: extensions/runtimes/package.json [hunk 6]
```diff
@@ -10,6 +10,7 @@
     "watch": "yarn build --watch"
   },
   "dependencies": {
+    "@botframework-composer/types": "file:../../Composer/packages/types",
```
Comment (joshgummersall) [inline extensions/runtimes/package.json:13]: Is this how published packages should be expressing dependencies? Not as familiar with file references.

Comment (benbrown) [reply extensions/runtimes/package.json:13]: This is how the extensions currently reference these libraries that are in a different yarn workspace. I'm not sure if they should be updated to point to the published packages...

**Review by hatpick — APPROVED** [review]
