### PR TITLE
fix: get diagnostics data for different project not work

### LINKED ISSUE #6003: The project tree in diagnostic page doesn't work
## Describe the bug
diagnostic

## Version
main branch

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

### PR DESCRIPTION
**Pull request by alanlong9278**
## Description

fix: get diagnostics data for different project not work
diagnostic
## Task Item

closes #6003

### CODE REVIEW

File: Composer/packages/client/src/pages/diagnostics/DiagnosticsTable.tsx [hunk 1]
```diff
@@ -41,7 +42,8 @@ const itemCount = 10;
 
 export const DiagnosticsTable: React.FC<IDiagnosticListProps> = (props) => {
   const { onItemClick, showType } = props;
-  const diagnostics = useDiagnosticsData();
+  const projectId = useRecoilValue(currentProjectIdState);
```
Comment (lei9444) [inline Composer/packages/client/src/pages/diagnostics/DiagnosticsTable.tsx:45]: The currentProjectIdState may be mixed the state of design page and diagnostics page 
Can we use the projectId from props directly?
errors

**Review by lei9444 — CHANGES_REQUESTED** [review]

File: Composer/packages/client/src/pages/diagnostics/DiagnosticsTable.tsx (hunk 1 above)
Comment (alanlong9278) [reply Composer/packages/client/src/pages/diagnostics/DiagnosticsTable.tsx]: Fixed. Use props instead of recoilValue `currentProjectId`

**Review by boydc2014 — DISMISSED** [review]

**Review by srinaath — APPROVED** [review]

**Review by lei9444 — APPROVED** [review]
