### PR TITLE
fix: show bot url as tooltip

### LINKED ISSUE #2530: Expose bot port in Composer
## Describe the bug

In the skill doc, we have a step to use ngrok to configure the skillHostEndpoint, since our bot port is not restricted to 3979 any more. we need to have to way to let user know what is the port of the runing bot. 

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

### PR DESCRIPTION
**Pull request by boydc2014**
image

fixes #2530

### CODE REVIEW

**Comment by cwhitten** [comment]
Dong can you provide an icon that when clicked just copies the connection string to the clipboard?

**Comment by cwhitten** [comment]
see this codepen https://codepen.io/cwhitten/pen/abvNwKR

**Comment by boydc2014** [comment]
Thanks @cwhitten and @a-b-r-o-w-n, here is the updated version

image

File: Composer/packages/client/src/components/TestController/emulatorOpenButton.tsx [hunk 1]
```diff
@@ -4,30 +4,43 @@
...
-      }}
-      onClick={onClick}
+    <TooltipHost
+      content={
+        <Fragment>
+          URL: {botEndpoint}{' '}
+          <IconButton iconProps={{ iconName: 'copy' }} onClick={() => navigator.clipboard.writeText(botEndpoint)} />
+        </Fragment>
+      }
+      closeDelay={50000}
```
Comment (cwhitten) [inline Composer/packages/client/src/components/TestController/emulatorOpenButton.tsx:34]: you have configured 50 second closeDelay? why so high?

File: Composer/packages/client/src/components/TestController/emulatorOpenButton.tsx [hunk 2]
```diff
@@ -4,30 +4,43 @@
...
   return (
-    <ActionButton
-      iconProps={{
-        iconName: 'OpenInNewTab',
-      }}
-      onClick={onClick}
+    <TooltipHost
+      content={
+        <Fragment>
+          URL: {botEndpoint}{' '}
```
Comment (cwhitten) [inline Composer/packages/client/src/components/TestController/emulatorOpenButton.tsx:30]: Not a fan of this URL: prefix. Can we just remove it and show botEndpoint?

File: Composer/packages/client/src/components/TestController/emulatorOpenButton.tsx (hunk 1 above)
Comment (boydc2014) [reply Composer/packages/client/src/components/TestController/emulatorOpenButton.tsx]: accidentally checked in debugging configuration, corrected

File: Composer/packages/client/src/components/TestController/emulatorOpenButton.tsx (hunk 2 above)
Comment (boydc2014) [reply Composer/packages/client/src/components/TestController/emulatorOpenButton.tsx]: Thought it would be more like the Azure style, there is a key:value, but not sure, removing them is also good, done
