### PR TITLE
fix: use router-based links to project manager

### LINKED ISSUE #7225: Add from package manager link ref wrong view
Ref video

https://user-images.githubusercontent.com/16264167/115598923-3f642f80-a2db-11eb-9123-964d15bc279c.mp4

### PR DESCRIPTION
**Pull request by beyackle**
## Description

This changes the two "package manager" links in our connections settings to use the Reach Router-based link style instead of direct HTTP ones; this solves the issue of the link destinations being incorrect.

## Task Item

closes #7225

## Screenshots

image
These two links now correctly route to the package manager.

### CODE REVIEW

**Review by a-b-r-o-w-n — APPROVED** [review]

File: Composer/packages/client/src/pages/botProject/adapters/ExternalAdapterSettings.tsx [hunk 1]
```diff
@@ -132,9 +131,9 @@ const ExternalAdapterSettings = (props: Props) => {
       <div key={'subtitle'} css={subtitle}>
         {formatMessage.rich('<a>Add from package manager</a>.', {
```
Comment (tdurnford) [inline Composer/packages/client/src/pages/botProject/adapters/ExternalAdapterSettings.tsx:132]: Can you remove the period at the end?

**Review by tdurnford — CHANGES_REQUESTED** [review]

File: Composer/packages/client/__tests__/pages/botProjectsSettings/AdapterSettings.test.tsx [hunk 2]
```diff
@@ -87,7 +87,9 @@ describe('ExternalAdapterSettings', () => {
 
     const link = getByText(/from package manager/);
 
-    expect(link.attributes.getNamedItem('href')?.value).toEqual('plugin/package-manager/package-manager');
+    console.log(link);
```
Comment (tdurnford) [inline Composer/packages/client/__tests__/pages/botProjectsSettings/AdapterSettings.test.tsx:90]: Remove console.log

**Review by tdurnford — CHANGES_REQUESTED** [review]

File: Composer/packages/client/__tests__/pages/botProjectsSettings/AdapterSettings.test.tsx (hunk 2 above)
Comment (beyackle) [reply Composer/packages/client/__tests__/pages/botProjectsSettings/AdapterSettings.test.tsx:90]: 🤦‍♀️D'oh. Thanks for the catch.

**Review by tdurnford — APPROVED** [review]
