### PR TITLE
fix: detect "Get started" dependencies in all projects not just current project

### LINKED ISSUE #6649: BUG: When in a multibot project such as enterprise assistant, the get started feature is does not lock to the root bot, and also does not detect child bot dependencies.
As a result, the project will say it requires QNA, but not LUIS.

If you select one of the skills, it will switch to LUIS, but not QNA.

This should always be locked to the root bot, and include ALL child deps.

### PR DESCRIPTION
**Pull request by benbrown**
## Description

adjust the mechanism used to determine if a project needs LUIS or QNA to support multi-bot projects. This moves code from the header component into a recoil selector.

## Task Item

fixes #6649

### CODE REVIEW

**Review by GeoffCoxMSFT — DISMISSED** [review]

File: Composer/packages/client/src/components/Header.tsx [hunk 1]
```diff
@@ -176,11 +175,9 @@ export const Header = () => {
   // These are needed to determine if the bot needs LUIS or QNA
   // this data is passed into the GetStarted widget
   // ... if the get started widget moves, this code should too!
-  const dialogs = useRecoilValue(dialogsWithLuProviderSelectorFamily(projectId));
-  const luFiles = useRecoilValue(luFilesSelectorFamily(projectId));
-  const qnaFiles = useRecoilValue(qnaFilesSelectorFamily(projectId));
-  const requiresLUIS = BotIndexer.shouldUseLuis(dialogs, luFiles);
-  const requiresQNA = BotIndexer.shouldUseQnA(dialogs, qnaFiles);
+  const requiredStuff = useRecoilValue(allRequiredRecognizersSelector);
+  const requiresLUIS = requiredStuff.filter((p) => p.requiresLUIS)?.length ? true : false;
```
Comment (a-b-r-o-w-n) [inline Composer/packages/client/src/components/Header.tsx:179]:
```suggestion
  const requiresLUIS = requiredStuff.some((p) => p.requiresLUIS);
```

File: Composer/packages/client/src/components/Header.tsx [hunk 2]
```diff
@@ -176,11 +175,9 @@ export const Header = () => {
...
+  const requiresQNA = requiredStuff.filter((p) => p.requiresQNA)?.length ? true : false;
```
Comment (a-b-r-o-w-n) [inline Composer/packages/client/src/components/Header.tsx:180]:
```suggestion
  const requiresQNA = requiredStuff.some((p) => p.requiresQNA);
```

**Review by a-b-r-o-w-n — APPROVED** [review]

**Review by a-b-r-o-w-n — APPROVED** [review]
