### PR TITLE
fix: language err for build luis in azure deploy

### LINKED ISSUE #4136: Multi language after deploy
Hello,

I have a project which I added another language using the new multilanguage feature. In this case I already had created the bot in  english and added portuguese. I translated the bot and then I changed the deault language and the bot language to portuguese as you can see in the screenshot below.

image

Below is my local configuration

`{
  "feature": {
    "UseShowTypingMiddleware": false,
    "UseInspectionMiddleware": false,
    "RemoveRecipientMention": false
  },
  "MicrosoftAppPassword": "",
  "MicrosoftAppId": "",
  "cosmosDb": {
    "authKey": "",
    "collectionId": "botstate-collection",
    "cosmosDBEndpoint": "",
    "databaseId": "botstate-db"
  },
  "applicationInsights": {
    "InstrumentationKey": ""
  },
  "blobStorage": {
    "connectionString": "",
    "container": "transcripts"
  },
  "luis": {
    "name": "edpV3",
    "authoringKey": "xxxxxxxxxxx",
    "endpointKey": "",
    "authoringRegion": "westeurope",
    "defaultLanguage": "pt-br",
    "environment": "composer",
    "endpoint": "xxxxxxxxxxx",
    "authoringEndpoint": ""
  },
  "qna": {
    "knowledgebaseid": "xxxxxxxxx",
    "hostname": "xxxxxxxxx",
    "endpointKey": "xxxxxxxxx",
    "subscriptionKey": "xxxxxxxxx",
    "qnaRegion": "westus"
  },
  "telemetry": {
    "logPersonalInformation": false,
    "logActivities": true
  },
  "runtime": {
    "customRuntime": false,
    "path": "",
    "command": ""
  },
  "downsampling": {
    "maxImbalanceRatio": 10,
    "maxUtteranceAllowed": 15000
  },
  "defaultLanguage": "pt-br",
  "languages": [
    "en-us",
    "pt-br"
  ]
}`

So far so good. I tested on the emulator and it worked as intended. When I change the locale on the emulator the bot starts speaking in the respective language and understands what I tell him in the respective language also. 

The problem is when I deploy the bot.
Below is my deploy configuration.

`{
  "accessToken": "xxxxxxxxxxxx",
  "name": "edp-test-bot",
  "environment": "dev",
  "settings": {
    "applicationInsights": {
      "InstrumentationKey": "<Instrumentation Key>"
    },
    "cosmosDb": {
      "cosmosDBEndpoint": "<endpoint url>",
      "authKey": "<auth key>",
      "databaseId": "botstate-db",
      "collectionId": "botstate-collection",
      "containerId": "botstate-container"
    },
    "blobStorage": {
      "connectionString": "<connection string>",
      "container": "<container>"
    },
    "luis": {
      "authoringKey": "xxxxxxxxxxxxxxxxxxxx",
      "authoringEndpoint": "xxxxxxxxxxxxxxxxxxxxx",
      "endpointKey": "xxxxxxxxxxxxxxxxx",
      "endpoint": "xxxxxxxxxxxxxxxxxxxxxxx",
      "region": "westeurope",
      "defaultLangage": "pt-br"
    },
    "MicrosoftAppId": "xxxxxxxxxxxx",
    "MicrosoftAppPassword": "xxxxxxxxxxxxxxxxx"
  },
  "hostname": "edp-testbot",
  "luisResource": "edp-testbot-luis",
  "defaultLanguage": "pt-br"
}`

The problem is that the bot starts speaking in portuguese but it only understands when I talk in english, so it is checking on the en-us apps that are on LUIS instead of checking the pt-br ones.
I'm using the same LUIS resource for local and for the prooduction version.
I added the "defaultLanguage" properties with hope it would fix my problem but it had no effect.

Can you please check if there is something wrong with my configurations.
Also below is an image showing that both en-us and pt-br apps exist on LUIS.

image

### PR DESCRIPTION
**Pull request by alanlong9278**
## Description

Bug fix: default language  for build luis in azure deploy

In composer settings, we use defaultLanguge as the fallback language for both LU and LG.
But currently there is a bug in the azure publish plugin that it takes the settings.language as the default language for lubuild.

This PR is to fix that issue. 

## Task Item

closes #4136

### CODE REVIEW

File: Composer/plugins/azurePublish/src/deploy.ts [hunk 1]
```diff
@@ -55,8 +55,9 @@ export class BotProjectDeploy {
 
       // STEP 2: UPDATE LUIS
       // Do the LUIS build if LUIS settings are present
-      if (!language) {
-        language = 'en-us';
+      let luisLanguage = language || settings.luis.defaultLanguage;
```
Comment (luhan2017) [inline Composer/plugins/azurePublish/src/deploy.ts:58]: I think we could just take defaultLanguage. you can update the code like this:

let language = defaultLanguage || settings.luis.defaultLanguage；
if (!language){
   language = 'en-us'
}

**Review by luhan2017 — APPROVED** [review]

**Review by cwhitten — APPROVED** [review]
