### PR TITLE
fix: revise text in Azure Bot creation dialog

### LINKED ISSUE #8166: Update Open from ABS modal copy
## Describe the bug

The copy on the modal shown when you open from ABS needs to be updated.

absopenmodal

Please amend this copy to the following.

**Title:** Choose a bot project for your Azure Bot
**Subtext:** Use your Azure Bot resource with a new or existing bot project. You can publish your bot project directly to Azure, using the publishing profile created for you. Learn more.
**Option 1:** Create a new bot project
**Option 2:** Use an existing bot project

The learn more link should link to https://docs.microsoft.com/en-us/composer/quickstart-create-bot-with-azure (we probably need an aka.ms link for this if we don't already have one for use in Composer).

FYI @JonathanFingold as our docs will need to be updated following this change in R14 and the screenshots over there already look out of date anyway https://docs.microsoft.com/en-us/composer/quickstart-create-bot-with-azure.

### PR DESCRIPTION
**Pull request by beyackle**
## Description

This turned out to be more than a simple copy change; adding the Learn More link meant I had to restructure the dialog a little, and I refactored it out into its own file to be a little cleaner and easier to modify.

## Task Item

closes #8166 

## Screenshots

MicrosoftTeams-image (9)

### CODE REVIEW

File: Composer/packages/client/src/components/CreationFlow/AzureBotDialog.tsx [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+import { DialogCreationCopy } from '../../constants';
+
+type Props = {
+  isOpen: boolean;
+  onDismiss: () => void;
+  onJumpToOpenModal: (search?: string) => void;
+  setIsOpenCreateModal: (boolean) => void;
+} & RouteComponentProps<{}>;
+
+const options: IChoiceGroupOption[] = [
```
Comment (tdurnford) [inline Composer/packages/client/src/components/CreationFlow/AzureBotDialog.tsx:25]: `options` needs to be moved into the component since it uses `formatMessage`.

File: Composer/packages/client/src/components/CreationFlow/AzureBotDialog.tsx [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+  modal: {
+    main: {
+      maxWidth: '80% !important',
+      width: '480px !important',
+    },
+  },
+};
+
+export const AzureBotDialog = (props: Props) => {
+  const [option, setOption] = useState('Create');
```
Comment (tdurnford) [inline Composer/packages/client/src/components/CreationFlow/AzureBotDialog.tsx:57]:
```suggestion
  const [option, setOption] = useState<'Create' | 'Connect'>('Create');
```

File: Composer/packages/client/src/components/CreationFlow/AzureBotDialog.tsx [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+import { RouteComponentProps } from '@reach/router';
+
+import TelemetryClient from '../../telemetry/TelemetryClient';
+import { DialogCreationCopy } from '../../constants';
+
+type Props = {
+  isOpen: boolean;
+  onDismiss: () => void;
+  onJumpToOpenModal: (search?: string) => void;
+  setIsOpenCreateModal: (boolean) => void;
```
Comment (tdurnford) [inline Composer/packages/client/src/components/CreationFlow/AzureBotDialog.tsx:22]: `setIsOpenCreateModal` should be `onToggleCreateModal`. Event handlers passed as props should not start with `set*`.

File: Composer/packages/client/src/constants.tsx [hunk 4]
```diff
@@ -200,9 +200,9 @@ export const BotStatusesCopy = {
 export const DialogCreationCopy = {
   get CREATE_OPTIONS() {
     return {
-      title: formatMessage('Your new Azure Bot is available in Composer'),
+      title: formatMessage('Choose a bot project for your Azure Bot'),
       subText: formatMessage(
-        'The Azure Bot created in Azure Bot Services contains bot resources that can be used as the basis for a new bot, or to add or replace resources of an existing bot.'
+        'Use your Azure Bot resource with a new or existing bot project. You can publish your bot project directly to Azure, using the publishing profile created for you.'
```
Comment (tdurnford) [inline Composer/packages/client/src/constants.tsx:205]: Unnecessary coma. 
```suggestion
        'Use your Azure Bot resource with a new or existing bot project. You can publish your bot project directly to Azure using the publishing profile created for you.'
```

**Review by tdurnford — CHANGES_REQUESTED** [review]

File: Composer/packages/client/src/constants.tsx (hunk 4 above)
Comment (beyackle) [reply Composer/packages/client/src/constants.tsx:205]: Thanks for catching that; I'd blindly copied the text I was handed without proofreading it first.

**Review by tdurnford — APPROVED** [review]
