### PR TITLE
fix: Minor Orchestrator Text Changes

### LINKED ISSUE #5087: "Orchestrator Recognizer" case issue
## Describe the bug

**Orchestrator Recognizer** is not consistent with the casing rules of the other recognizers. 

image

## Version

main branch as of December 3, 2020

## Browser

- [x] Chrome

## OS

- [x] Windows

## To Reproduce

1. Enable "Orchestrator" from feature flag
2. Go to 'Recognizer Type'
3. Expand the drop-down menu

## Expected behavior

Suggested: Change "Orchestrator Recognizer" to "Orchestrator recognizer"

### PR DESCRIPTION
**Pull request by taicchoumsft**
## Description
Minor text updates for Orchestrator. "Learn More" link goes to [https://aka.ms/bf-orchestrator](https://aka.ms/bf-orchestrator)

## Task Item
closes #5087 and #5112 

## Screenshots
image

image

### CODE REVIEW

File: Composer/packages/lib/shared/src/featureFlagUtils/index.ts [hunk 1]
```diff
@@ -23,9 +23,8 @@ export const getDefaultFeatureFlags = (): FeatureFlagMap => ({
   },
   ORCHESTRATOR: {
     displayName: formatMessage('Orchestrator'),
-    description: formatMessage(
-      'Use as intent-only recognizer, typically for routing to skills or subsequent LUIS or QnAMaker processing or when entity extraction is not needed.'
-    ),
+    description: formatMessage('Recognize an intent, and take action or route  to a skill, LUIS app, or QnAMaker KB.'),
```
Comment (zxyanliu) [inline Composer/packages/lib/shared/src/featureFlagUtils/index.ts]: Looks good to me except that there is an extra space in the `formatMessage` string b/w the words "route" and "to":
'Recognize an intent, and take action or **route  to** a skill, LUIS app, or QnAMaker KB.'

Comment (taicchoumsft) [reply Composer/packages/lib/shared/src/featureFlagUtils/index.ts]: Thanks, great eye! Fixed.

**Comment by zxyanliu** [comment]
Thanks! @taicchoumsft 
The PR looks good to me.

**Review by zxyanliu — APPROVED** [review]

**Review by cwhitten — APPROVED** [review]
