### PR TITLE
fix: Include settings changes in persistence layer and flush changes before switching bot

### LINKED ISSUE #3101: Add loading indicator when open bot
Open a bot may take sometimes to load, and feels weird when waiting because the UI don't show anything, adding a indicator will avoid confusing

image

i mean after clicking ToDoLuis samples, there should be some spinner and block me from typing a gain.

### PR DESCRIPTION
**Pull request by lei9444**
## Description
1. wait lu/lg worker and task queue flush before switching a bot.
2. add a loading modal when open pending. 
3. Include settings changes in persistence layer

## Task Item
closes #3101

## Screenshots

queue

### CODE REVIEW

**Comment by boydc2014** [comment]
this haven't include "extend the task queue to cover settings read\write" right?

File: Composer/packages/client/src/App.tsx [hunk 1]
```diff
@@ -117,6 +118,7 @@ export const App: React.FC = () => {
         </div>
         <Suspense fallback={<div />}>{!state.onboarding.complete && <Onboarding />}</Suspense>
         <Suspense fallback={<div />}>{renderAppUpdater && <AppUpdater />}</Suspense>
+        <LoadingModal isOpen={botOpening} />
```
Comment (a-b-r-o-w-n) [inline Composer/packages/client/src/App.tsx:121]: We can use the loading spinner component here instead.

File: Composer/packages/client/src/store/persistence/FilePersistence.ts [hunk 2]
```diff
@@ -136,15 +136,22 @@ class FilePersistence {
...
+  private _createChange(
+    file: any,
+    fileExtension: FileExtensions,
+    changeType: ChangeType,
+    projectId: string
+  ): IFileChange {
     let content = file.content;
-    if (fileExtension === FileExtensions.Dialog || fileExtension === FileExtensions.Manifest) {
+    const jsonContent = [FileExtensions.Dialog, FileExtensions.Manifest, FileExtensions.Setting];
+    if (~jsonContent.indexOf(fileExtension)) {
```
Comment (a-b-r-o-w-n) [inline Composer/packages/client/src/store/persistence/FilePersistence.ts:147]:
```suggestion
    const isJson = [FileExtensions.Dialog, FileExtensions.Manifest, FileExtensions.Setting].includes(fileExtension);
    if (isJson) {
```

File: Composer/packages/client/src/store/action/project.ts [hunk 3]
```diff
@@ -12,6 +15,25 @@ import settingStorage from './../../utils/dialogSettingStorage';
 import luFileStatusStorage from './../../utils/luFileStatusStorage';
 import httpClient from './../../utils/httpUtil';
 
+export const checkProjectUpdates = async () => {
+  return new Promise(resolve => {
+    const timer = setInterval(() => {
+      //before open a new bot, we should check the task queue, lu/lg worker
+      if (filePersistence.isEmpty() && lgWorker.isEmpty() && luWorker.isEmpty()) {
```
Comment (a-b-r-o-w-n) [inline Composer/packages/client/src/store/action/project.ts:22]: Is there a way to tell the workers to drain their queues instead of asking if they are empty?

I imagine something like:

```
allWork = []
for worker in [filePersistence, lgWorker, luWorker]
  allWork.push(worker.flush());

await Promise.all(allWork);
```
