### PR TITLE
fix: Register IBotTelemetryClient and add telemetry initializer middleware…

### LINKED ISSUE #2915: Telemetry configuration broken in runtime
Some changes to the runtime have broken the telemetry configuration.

- IBotTelemetryClient is no longer registered for DI
- The TelemetryInitializerMiddleware is never added to the adapter pipeline

I have a fix ready to PR for this - will raise the PR once this issue is opened.

### PR DESCRIPTION
**Pull request by garypretty**
Fixes #2915 - registers the IBotTelemetryClient and adds the TelemetryInitializerMiddleware to the pipeline of the adapter.

### CODE REVIEW

File: runtime/dotnet/azurewebapp/Startup.cs [hunk 1]
```diff
@@ -131,17 +132,13 @@ public void ConfigureServices(IServiceCollection services)
...
-            });
-            services.AddSingleton<TelemetryInitializerMiddleware>(sp =>
-            {
-                var httpContextAccessor = sp.GetService<IHttpContextAccessor>();
-                var telemetryLoggerMiddleware = sp.GetService<TelemetryLoggerMiddleware>();
-                return new TelemetryInitializerMiddleware(httpContextAccessor, telemetryLoggerMiddleware, settings.Telemetry.LogActivities);
-            });
+            services.AddSingleton<IBotTelemetryClient, BotTelemetryClient>();
+
+            var sp = services.BuildServiceProvider();
```
Comment (carlosscastro) [inline runtime/dotnet/azurewebapp/Startup.cs:137]: The github actions is issuing some good advice. This is expensive to run, please remove it. Instead, in line 169 you can do s.getservice there which is a factory method and will be called after the service provider is built.

If you need to use the telemetry somehwere else, just do as we did with the bot and use the factory method instead of the instance method to do deferred resolution. Ping me if you want to chat more about this.

File: runtime/dotnet/azurewebapp/Startup.cs [hunk 2]
```diff
@@ -80,15 +80,16 @@ public IStorage ConfigureStorage(BotSettings settings)
             return storage;
         }
 
-        public BotFrameworkHttpAdapter GetBotAdapter(IStorage storage, BotSettings settings, UserState userState, ConversationState conversationState, IServiceProvider s)
+        public BotFrameworkHttpAdapter GetBotAdapter(IStorage storage, BotSettings settings, UserState userState, ConversationState conversationState, IServiceProvider s, TelemetryInitializerMiddleware telemetryInitializerMiddleware)
```
Comment (carlosscastro) [inline runtime/dotnet/azurewebapp/Startup.cs:83]: Please port these to the `runtime/dotnet/azurefunctions` folder too. I can help you verify if you need.

File: runtime/dotnet/azurewebapp/Startup.cs (hunk 1 above)
Comment (garypretty) [reply runtime/dotnet/azurewebapp/Startup.cs:137]: Sorry, I had done this for passing in TelemetryInitializerMiddleware on line 160, but missed the fact that I had access to the service provider here (which I didn't think I did). Thanks for the catch. I'll amend now,

File: runtime/dotnet/azurewebapp/Startup.cs (hunk 2 above)
Comment (garypretty) [reply runtime/dotnet/azurewebapp/Startup.cs:83]: Added the changes to functions app as requested.
