### PR TITLE
fix: showing correct error message in local publish

### LINKED ISSUE #5390: Bot fails to start after update to v1.3.0
## Describe the bug

After updating to v1.3.0 the bot does not start in the emulator. 
image

Publishing to azure is still going fine
image

## Version

1.3.0

## Browser

- [ ] Electron distribution
- Chrome
- [ ] Safari
- [ ] Firefox
- Edge

## OS

- [ ] macOS
- Windows
- [ ] Ubuntu

## To Reproduce

1. Open bot
2. Click on start bot or restart bot

## Expected behavior

Bot opens in emulator

### PR DESCRIPTION
**Pull request by VanyLaw**
## Description
some error doesn't serializate.

## Task Item

close #5390

### CODE REVIEW

File: extensions/localPublish/src/index.ts [hunk 1]
```diff
@@ -52,6 +51,17 @@ const isLocalhostUrl = (matchUrl: string) => {
...
   return !skillHostEndpoint || isLocalhostUrl(skillHostEndpoint);
 };
+
+const stringifyError = (error: any): string => {
+  if (error instanceof Error) {
+    return `${error.name} - ${error.message}`;
+  } else if (typeof error === 'object') {
+    return JSON.stringify(error, Object.getOwnPropertyNames(error));
+  } else {
+    return error;
```
Comment (boydc2014) [inline extensions/localPublish/src/index.ts:61]: how about return error.toString()?

Comment (VanyLaw) [reply extensions/localPublish/src/index.ts:61]: if error is instanceof Error or typeof string, it can return toString(), but if it's an normal object, toString will throw error.

Comment (boydc2014) [reply extensions/localPublish/src/index.ts:61]: I mean the your default condition, line 61, should be error.toString() right? since your function are supposed to return a string

Comment (VanyLaw) [reply extensions/localPublish/src/index.ts]: done.

**Review by boydc2014 — APPROVED** [review]
