### PR TITLE
fix: Fixed unset electron production flag.

### LINKED ISSUE #2770: Allow Composer to dynamically find a port to mount the server to
Currently, Composer is set to run on port 5000, which can cause it to fail if the user's machine is using that port for anything else.

Composer should dynamically find an open port and mount the server using that port.

### PR DESCRIPTION
**Pull request by tonyanziano**
## Description

The `NODE_ENV` env variable was expected to be set to `production` when executing the packaged Composer Electron app, but it was not being set. This was breaking some production functionality such as dynamically finding an open port to mount the server on.

## Task Item

fixes #2770

### CODE REVIEW

File: Composer/packages/electron-server/src/main.ts [hunk 1]
```diff
@@ -32,6 +32,12 @@ const getBaseUrl = () => {
   return `http://localhost:${serverPort}/`;
 };
 
+// set production flag
+if (app.isPackaged) {
```
Comment (srinaath) [inline Composer/packages/electron-server/src/main.ts:36]: Is this the first place where app.isPackaged is set to true @tonyanziano . Can we move it outside directly inside main.ts not nested in any function?

Comment (srinaath) [reply Composer/packages/electron-server/src/main.ts:36]: Or what if we use cross-env NODE_ENV=production inside the command yarn dist:full?

Comment (tonyanziano) [reply Composer/packages/electron-server/src/main.ts:36]: I'm not sure I understand the wording of your question. Where would you like to move it to?

Comment (tonyanziano) [reply Composer/packages/electron-server/src/main.ts:36]: Setting the variable at the script level doesn't work after testing. This is because `process.env` is scoped to the process at runtime, so attaching it to the `yarn dist:full` script would simply set it for the duration of building the production version, but at runtime it would be unset.
