### PR TITLE
fix: fixes auth flow on web & electron version

### LINKED ISSUE #6963: e2e testing: Using Get LUIS or Get QnA Key option does not work in Composer
## Version
image

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create an Enterprise bot in Composer
2. Click on 'Project Settings' in left nav to go to the following page

image

3. Click on 'Get LUIS keys', the dialog box is greyed out, see below:
image

Note: QnA keys also show a dialog that has the subscription greyed out.

## Expected behavior
I should be able to select the subscription and proceed.

### LINKED ISSUE #7597: Create new speech service not authenticating for create new
## Describe the bug

When trying to enable speech service on a publishing profile, the create new service option does not prompt for authentication.  It just sticks on screen with no way to go forward.

image

## Version

Version:  2.0.0-nightly.242275.686a144
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new Empty bot
2. Create a new Publishing profile using new services
3. Publish bot to Publishing profile
4. Go to bot settings and Connections
5. Turn on speech channel
6. Select to create new service
7. No Auth prompt and you can't proceed

## Expected behavior

Should be asked to logon to Azure and/or use existing auth

### LINKED ISSUE #7601: Azure sign-in not working (I signed in, but the directory and subscription fields are disabled
## Describe the bug

In the creation, I signed into Azure, but when I go to add resources the Azure directory and Subscription fields are diabled.

## Version

Bot Framework Composer

Version:  2.0.0-nightly.242275.686a144
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Open Composer.
2. Click New.
3. Choose template. I chose Core with Qna.
2. After downloading templates, the create QnA modal appears and the Azure sign in appears over it:
image

3. Finish sign in.
4. Eventually I got an error that QnA maker failed.
5. Try to add QnA Maker by clicking the project settings page.
4. The modal appears with the direction and subscription grayed out:
image

5. Same for the adding LUIS:
image
image

### LINKED ISSUE #7602: Can't load LUIS keys for function bots
## Describe the bug
The menu for selecting LUIS keys is grayed out

## Version
Version:  2.0.0-nightly.242275.686a144
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create an empty node function bot
2. Create a provision for the bot
3. Add an echo dialog and add a trigger to call that dialog
4. Click on the error to add a LUIS key
5. Click through the menus until you need to select the LUIS resource

## Expected behavior
The menu should be interactable

## Screenshots
image

## Additional context
Issue repos for node and dotnet bots

### PR DESCRIPTION
**Pull request by VamsiModem**
## Description
This PR fixes couple of auth issues

## Task Item
fixes #6963 
fixes #7602 
fixes #7597 
fixes #7601 

## Screenshots
image
image

### CODE REVIEW

File: Composer/packages/client/src/components/ManageService/ManageService.tsx [hunk 1]
```diff
@@ -210,9 +219,21 @@ export const ManageService = (props: ManageServiceProps) => {
...
-    if (newtoken) {
-      setToken(newtoken);
+      if (newtoken) {
+        const decoded = decodeToken(newtoken);
+        if (decoded) {
+          setToken(newtoken);
+          setUserProvidedTokens(true);
+        } else {
+          setTenantsErrorMessage(
+            formatMessage(
```
Comment (hatpick) [inline Composer/packages/client/src/components/ManageService/ManageService.tsx:229]: Does this happen only in dev mode? or a normal user might face this message as well? If so, is this UX approved?
I think we need to provide a much simpler way to clear the token from application local storage, as simple as having a link/button right here to clear it.

File: Composer/packages/client/src/components/ManageService/ManageService.tsx [hunk 2]
```diff
@@ -95,7 +96,7 @@ export const ManageService = (props: ManageServiceProps) => {
   const [availableSubscriptions, setAvailableSubscriptions] = useState<Subscription[]>([]);
   const [subscriptionsErrorMessage, setSubscriptionsErrorMessage] = useState<string>();
   const [keys, setKeys] = useState<KeyRec[]>([]);
-
+  const [userProvidedTokens, setUserProvidedTokens] = useState<boolean>(false);
```
Comment (hatpick) [inline Composer/packages/client/src/components/ManageService/ManageService.tsx:99]: what's the difference between userProvidedTokens and !!token? (i.e., token has value)

**Review by benbrown — APPROVED** [review]

File: Composer/packages/client/src/components/ManageService/ManageService.tsx (hunk 1 above)
Comment (VamsiModem) [reply Composer/packages/client/src/components/ManageService/ManageService.tsx:229]: This only happens in dev mode.

File: Composer/packages/client/src/components/ManageService/ManageService.tsx (hunk 2 above)
Comment (VamsiModem) [reply Composer/packages/client/src/components/ManageService/ManageService.tsx:99]: we need to know if it's in dev mode and user provided the tokens, instead of calling userShouldProvideTokens(), I am using this state.

**Review by hatpick — APPROVED** [review]

**Review by GeoffCoxMSFT — APPROVED** [review]
