### PR TITLE
fix: add static QnA and Luis entities and remove duplicate entities

### LINKED ISSUE #5882: LG Language Server suggested entities does not work correctly.
1. Missing QnA and Luis static members: `@answer`, `@itemList` 
2. Suggest duplicate entities from multiple files

MicrosoftTeams-image

### PR DESCRIPTION
**Pull request by cosmicshuai**
closes #5882

1. Add `@answer` and `@itemList` to suggested entities

2. remove duplicate entities from multiple lu files.

image

### CODE REVIEW

File: Composer/packages/tools/language-servers/language-generation/src/lgParser.ts [hunk 1]
```diff
@@ -33,15 +33,15 @@ class LgParserWithoutWorker {
...
+    let suggestEntities: string[] = ['answer', 'itemList'];
     if (luContents) {
       for (const content of luContents) {
         const luisJson = await extractLUISContent(content);
         suggestEntities = suggestEntities.concat(getSuggestionEntities(luisJson, suggestionAllEntityTypes));
       }
     }
 
-    return { suggestEntities: suggestEntities };
+    return { suggestEntities: uniq(suggestEntities) };
```
Comment (lei9444) [inline Composer/packages/tools/language-servers/language-generation/src/lgParser.ts:44]: we can use uniq from lodash direttly

Comment (cosmicshuai) [reply Composer/packages/tools/language-servers/language-generation/src/lgParser.ts:45]: changed

**Review by boydc2014 — APPROVED** [review]
