### PR TITLE
fix: azure deploy bugfix

### LINKED ISSUE #3897: Provision new Azure resources and publish bot - Test in Web Chat had no response.
## Describe the bug

* Provision new resources and publish an echo bot. 

  image

* Test in Web Chat had no response. 

   image

## Version

[main](https://github.com/microsoft/BotFramework-Composer) branch.

## Browser

- [x] Chrome

## OS

- [x] Windows

## To Reproduce

https://docs.microsoft.com/en-us/composer/how-to-publish-bot

## Expected behavior

After publish, Test in Web Chat should have responses.

## Additional context

Related to: [docs pre-release test](https://github.com/MicrosoftDocs/composer-docs-pr/issues/190)

### PR DESCRIPTION
**Pull request by alanlong9278**
## Description
Bug: Test in Web Chat had no response
Fix: It should always create `${dialogName}.lu.qna.dialog` in `generated` folder even there is an empty lu & qna file.

## Task Item

fix #3897

### CODE REVIEW

**Comment by alanlong9278** [comment]
@zxyanliu Could u please help check it?

File: Composer/plugins/azurePublish/src/luisAndQnA.ts [hunk 1]
```diff
@@ -384,41 +384,47 @@ export class LuisAndQnaPublish {
...
-        language,
-        luisSettings,
-        interruptionLuFiles,
-        luisResource
-      );
-      const qnaConfig = await this.publishQna(name, environment, language, qnaSettings, interruptionQnaFiles);
-      await this.cleanCrossTrain();
-      return { luisAppIds, qnaConfig };
+    if (notEmptyLuFiles.length > 0 && !(authoringKey && authoringRegion)) {
+      throw 'Should have luis authoringKey and authoringRegion when lu file not empty';
```
Comment (a-b-r-o-w-n) [inline Composer/plugins/azurePublish/src/luisAndQnA.ts:404]: Should throw an error instead of a string.

File: Composer/plugins/azurePublish/src/luisAndQnA.ts [hunk 2]
```diff
@@ -384,41 +384,47 @@ export class LuisAndQnaPublish {
...
-      if (qnaFiles.length > 0 && !subscriptionKey) {
-        throw 'Should have qna subscriptionKey when qna file not empty';
-      }
-      const dialogFiles = botFiles.filter((name) => {
-        return name.endsWith('.dialog') && this.notEmptyModel(name);
-      });
+    // check content
+    const notEmptyLuFiles = luFiles.filter((name) => {
+      return this.notEmptyModel(name);
+    });
```
Comment (a-b-r-o-w-n) [inline Composer/plugins/azurePublish/src/luisAndQnA.ts:398]:
```suggestion
    const notEmptyLuFiles = luFiles.some(this.notEmptyModel);
```

File: Composer/plugins/azurePublish/src/luisAndQnA.ts [hunk 3]
```diff
@@ -384,41 +384,47 @@ export class LuisAndQnaPublish {
...
+    const notEmptyQnaFiles = qnaFiles.filter((name) => {
+      return this.notEmptyModel(name);
+    });
```
Comment (a-b-r-o-w-n) [inline Composer/plugins/azurePublish/src/luisAndQnA.ts:401]:
```suggestion
    const notEmptyQnaFiles = qnaFiles.some(this.notEmptyModel);
```

**Comment by zxyanliu** [comment]
@alanlong9278 I will do an end-to-end test for this.

**Review by boydc2014 — APPROVED** [review]
