### PR TITLE
fix: Start bots panel design and error popup issues

### LINKED ISSUE #4975: Start bots panel error popup becomes detached from its parent
## Describe the bug

The error popup in the start bots panel sticks around when you click on it even though the start bots panel itself goes away

## Version

1.3 preview

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Open the start bots panel when a bot is inactive
2. Click on 'See Details'
3. Click on the error popup
4. Observe that the start bots panel closes but the error popup moves to the upper left corner

## Expected behavior

The error popup should not be visible if its parent is invisible

## Screenshots

image

image

## Additional context

The get the error in the first place, I just tried opening a bot from a previous version of Composer

### PR DESCRIPTION
**Pull request by srinaath**
## Description

Misc fixes for start bots panel styles.

1.  Resolves missing .net dependency warning.

## Screenshots

Screen Shot 2020-12-02 at 11 40 53 AM

  
 

Screen Shot 2020-12-02 at 11 41 05 AM

  
 

Final2

Fixes #4975

### CODE REVIEW

File: Composer/packages/client/src/recoilModel/dispatchers/publisher.ts [hunk 1]
```diff
@@ -31,6 +31,24 @@ const PUBLISH_SUCCESS = 200;
...
+    url: 'https://docs.microsoft.com/en-us/composer/setup-yarn',
+  },
+  link: {
+    text: formatMessage('Install Microsoft .NET Core SDK'),
+    url: 'https://dotnet.microsoft.com/download/dotnet-core/3.1',
+  },
+};
+
+const checkIfDotnetVersionMissing = (err: any) => {
+  return /(Command failed: dotnet build)| (Command failed: dotnet user-secrets)|(install[\w\r\s\S\t\n]*\.NET Core SDK)/.test(
```
Comment (beyackle) [inline Composer/packages/client/src/recoilModel/dispatchers/publisher.ts:47]: I'm not sure I understand that character class. `\s\S` together means "any character at all", so just `install.*\.NET` should work fine.

**Review by beyackle — APPROVED** [review]
I know it's the same regexp that was already there, but if you want to change that, you could. Everything else looks fine.
