### PR TITLE
fix: use actual tooltips for icons in header

### LINKED ISSUE #7080: Buttons in blue app bar should have a label + tooltip to show the label
Open composer.
Notice the top header bar has several icons: 

- three stacked horizontal lines, no label, no hover to show tooltip with label
- 2 chat bubbles, no label, no hover to show tooltip with label
- bell icon, no label, no hover to show tooltip with label
- rocket icon, no label, no hover to show tooltip with label

This will not pass usability, accessibility nor can it be documented as such for instructions _(Imagine this (-;  : go to the blue toolbar a the top of your screen. Click the icon 3nd from the left that looks like 3 horizonal stacked lines and...)_

Composer_toplevel_toolbar_needs_labels_and_tooltips

Expected:
- three stacked horizontal lines: Add label and provide descriptive copy on hover
- 2 chat bubbles: Add label and provide descriptive copy on hover
- bell icon: REMOVE THIS ICON as this is now handled in the diagostics bar at the bottom bar 
- rocket icon: Add label and provide descriptive copy on hover

### PR DESCRIPTION
**Pull request by beyackle**
## Description

This replaces the browser-based alt-text descriptions for the header buttons with tooltips that match the style of the ones we already use in our left-side nav bar.

## Task Item

closes #7080

## Screenshots

image
image
(Note: for some reason, the "Start and stop local bot runtimes" and "Open notification panel" tooltips aren't cooperating with being screenshotted, but they're both properly there without bringing up an extra browser-based alt-text callout)

### CODE REVIEW

File: Composer/packages/client/src/components/BotRuntimeController/BotController.tsx [hunk 1]
```diff
@@ -277,31 +278,32 @@ const BotController: React.FC<BotControllerProps> = ({ onHideController, isContr
...
-              root: {
-                color: NeutralColors.white,
-                height: '36px',
-                background: isControllerHidden ? CommunicationColors.tint10 : transparentBackground,
-                selectors: {
-                  ':disabled .ms-Button-icon': {
-                    opacity: 0.6,
-                    backgroundColor: CommunicationColors.tint10,
-                    color: `${NeutralColors.white}`,
+          <TooltipHost content={startStopLabel} directionalHint={DirectionalHint.bottomCenter}>
```
Comment (srinaath) [inline Composer/packages/client/src/components/BotRuntimeController/BotController.tsx:281]: @beyackle quick clarification, Do tooltips show up if the underlying button is disabled?

Comment (beyackle) [reply Composer/packages/client/src/components/BotRuntimeController/BotController.tsx:281]: I asked, and in this case they do.

File: Composer/packages/client/src/components/AppComponents/SideBar.tsx [hunk 2]
```diff
@@ -105,7 +104,7 @@ export const SideBar: React.FC<RouteComponentProps> = () => {
                 iconName={link.iconName}
                 labelName={link.labelName}
                 match={link.match}
-                showTooltip={showTooltips(link)}
+                showTooltip={!link.disabled && !sideBarExpand}
```
Comment (tdurnford) [inline Composer/packages/client/src/components/AppComponents/SideBar.tsx:107]: Are we sure we want to hide the tooltip if the link is disabled?

File: Composer/packages/client/src/components/Header.tsx [hunk 3]
```diff
@@ -291,34 +294,37 @@ export const Header = () => {
...
-              if (currentWebChatVisibility) {
-                TelemetryClient.track('WebChatPaneOpened');
-              } else {
-                TelemetryClient.track('WebChatPaneClosed');
-              }
-            }}
-          />
+          <TooltipHost content={labels().test} directionalHint={DirectionalHint.bottomCenter}>
+            <IconButton
+              ariaDescription={labels().test}
```
Comment (tdurnford) [inline Composer/packages/client/src/components/Header.tsx:299]: You should call the `labels` function and unpack it instead of calling `labels` multiple times. 

```js
const {
  logo: logoLabel,
  test: testLabel,
  rocket: rocketLabel,
  update: updateLabel,
 } = labels();
```

```suggestion
              ariaDescription={testLabel}
```

File: Composer/packages/client/src/components/AppComponents/SideBar.tsx (hunk 2 above)
Comment (srinaath) [reply Composer/packages/client/src/components/AppComponents/SideBar.tsx:107]: I think we would still want to show the tooltip if a button is disabled. For ex if a button is disabled due to PVA context(qna) we would typically want to know the tooltip instead of expanding the Sidebar

Comment (beyackle) [reply Composer/packages/client/src/components/AppComponents/SideBar.tsx:107]: That's how the sidebar currently works; the changes in there are a refactor.

File: Composer/packages/client/src/components/Header.tsx (hunk 3 above)
Comment (beyackle) [reply Composer/packages/client/src/components/Header.tsx:299]: Good idea. I'll fix that.

File: Composer/packages/client/src/components/AppComponents/SideBar.tsx (hunk 2 above)
Comment (tdurnford) [reply Composer/packages/client/src/components/AppComponents/SideBar.tsx:107]: @mareekuh @vivekkshankar Do either of you have an opinion on rendering the tooltip even if the button is disabled? The current behavior is to hide the tooltip if the button is disabled which seems like an odd behavior. The user might be curious what the button is even if it’s disabled.

Comment (mareekuh) [reply Composer/packages/client/src/components/AppComponents/SideBar.tsx:107]: Yes, please still show it even if the button is disabled.

File: Composer/packages/client/src/components/NavItem.tsx [hunk 4]
```diff
@@ -38,7 +38,7 @@ const link = (active: boolean, disabled: boolean) => css`
     `}
 
   ${disabled
-    ? `pointer-events: none;`
+    ? ``
```
Comment (tdurnford) [inline Composer/packages/client/src/components/NavItem.tsx:41]: nit: You flip this logic. 
```js
 ${!disabled ? ... : ''}
```

**Review by srinaath — APPROVED** [review]
