### PR TITLE
fix: Add form-wide and better trigger grouping

### LINKED ISSUE #4534: Grouped triggers need to display form-wide operations grouping
## Describe the bug

Triggers that don't match a property are missing when grouped by trigger for form dialogs

## Version

main/

## Browser

- [ ] Electron distribution
- [ X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Generate form dialog
2. Nav to design tree
3. Look for triggers (grouped)
4. Notice missing triggers

## Expected behavior

Triggers not missing

## Screenshots

N/A

### PR DESCRIPTION
**Pull request by GeoffCoxMSFT**
## Description

Triggers w/o properties were missing, this now provides the form-wide group
Updated to include expectedProperties in property search

## Task Item

Fixes #4534 

## Screenshots

image

### CODE REVIEW

File: Composer/packages/lib/indexers/src/groupTriggers.ts [hunk 1]
```diff
@@ -56,7 +78,8 @@ export const groupTriggersByPropertyReference = (
 
   const validProperties = options?.validProperties;
   const isValidProperty = validProperties
-    ? (x: string | undefined) => x && validProperties.findIndex((p) => x === p) !== -1
+    ? (x: string | undefined) =>
+        x && (x === NoGroupingTriggerGroupName || validProperties.findIndex((p) => x === p) !== -1)
```
Comment (hatpick) [inline Composer/packages/lib/indexers/src/groupTriggers.ts:82]: nit: replace ```indexOf``` with ```includes```

**Review by hatpick — APPROVED** [review]

**Review by hatpick — APPROVED** [review]
