### PR TITLE
fix: Make LUIS, QNA and Speech blocking modals

### LINKED ISSUE #6721: Bug: clicking the deep link to the QNA key from get started does not navigate to the appropriate tab on the settings page

### LINKED ISSUE #6722: Bug: while the luis or QNA provisionig processes are happening, it is possible to accidentally dismiss the modal by clicking outside the modal

### PR DESCRIPTION
**Pull request by benbrown**
## Description

Set isBlocking to true on these 3 modals so they cannot be improperly dismissed while busy provisioning services.

## Task Item

fixes #6722
Fixes #6721

### CODE REVIEW

File: Composer/packages/client/src/pages/botProject/BotProjectsSettingsTabView.tsx [hunk 1]
```diff
@@ -30,8 +30,8 @@ const container = css`
 
 const idsInTab: Record<PivotItemKey, string[]> = {
   Basics: ['runtimeSettings'],
-  LuisQna: [],
-  Connections: ['connections', 'addNewPublishProfile'],
+  LuisQna: ['luisKey', 'qnaKey'],
```
Comment (benbrown) [inline Composer/packages/client/src/pages/botProject/BotProjectsSettingsTabView.tsx:33]: this fixes an issue where deep links to these items weren't working

**Review by hatpick — APPROVED** [review]
