### PR TITLE
fix: added loading state to the subscriptions dropdown

### LINKED ISSUE #8341: Add a loading shimmer to subscriptions dropdown in azurePublish extension
At times, Subscriptions dropdown takes too long to populate the dropdown, it would be nice to show the loading state.

### PR DESCRIPTION
**Pull request by VamsiModem**
## Description

Placeholder text will be shown as 'Loading ...' when the call to server is still in progress.

## Task Item

Fixes #8341

## Screenshots
image

### CODE REVIEW

**Review by GeoffCoxMSFT — APPROVED** [review]

File: extensions/azurePublish/src/components/azureProvisionDialog.tsx [hunk 1]
```diff
@@ -816,7 +820,7 @@ export const AzureProvisionDialog: React.FC = () => {
               disabled={currentConfig?.subscriptionId}
               errorMessage={subscriptionsErrorMessage}
               options={subscriptionOptions}
-              placeholder={formatMessage('Select one')}
+              placeholder={formatMessage(subscriptionsLoading ? 'Loading ...' : 'Select one')}
```
Comment (hatpick) [inline extensions/azurePublish/src/components/azureProvisionDialog.tsx:823]: this should be ```condition ? formatMessage(...) : formatMessage(...)```
you should get a linter complain about this.

**Review by hatpick — CHANGES_REQUESTED** [review]

**Review by hatpick — APPROVED** [review]
