### PR TITLE
fix: read default values from schema when building modal

### LINKED ISSUE #5906: Adapters: boolean defaults from schema not working in modal

### PR DESCRIPTION
**Pull request by beyackle**
## Description

The adapter settings modal wasn't reading the values for defaults from the schema; it was just initializing the values as empty if there was no existing value object to load.

## Task Item

closes #5906

## Screenshots

image

### CODE REVIEW

**Comment by beyackle** [comment]
Hang on, need to fix a type error.

File: Composer/packages/client/src/pages/botProject/adapters/ExternalAdapterModal.tsx [hunk 1]
```diff
@@ -35,18 +35,24 @@ type Props = {
   projectId: string;
   schema: JSONSchema7;
   uiSchema: JSONSchema7 & { helpLink?: string };
-  value?: { [key: string]: ConfigValue };
+  value?: { [key: string]: JSONSchema4Type };
```
Comment (a-b-r-o-w-n) [inline Composer/packages/client/src/pages/botProject/adapters/ExternalAdapterModal.tsx:38]: Why use `JSONSchema4Type` instead of the already imported `JSONSchema7` type?

Also, this could be replaced by `SchemaDefinitions` which is also exported by the types package.

File: Composer/packages/client/src/pages/botProject/adapters/ExternalAdapterModal.tsx [hunk 2]
```diff
@@ -35,18 +35,24 @@ type Props = {
...
+  const { properties } = schema;
+
+  return mapValues(properties, 'default');
+}
+
 const AdapterModal = (props: Props) => {
   const { isOpen, onClose, schema, uiSchema, projectId, adapterKey, packageName, isFirstTime } = props;
 
-  const [value, setValue] = useState(props.value);
+  const [value, setValue] = useState(props.value == null ? makeDefault(schema) : props.value);
```
Comment (a-b-r-o-w-n) [inline Composer/packages/client/src/pages/botProject/adapters/ExternalAdapterModal.tsx:55]: A couple of questions:
1. What if the value is `null` and that is a valid value?
2. Depending on the answer to the above -- could we use the nullish operator instead?

File: Composer/packages/client/src/pages/botProject/adapters/ExternalAdapterModal.tsx (hunk 1 above)
Comment (beyackle) [reply Composer/packages/client/src/pages/botProject/adapters/ExternalAdapterModal.tsx:38]: Good idea - this was to fix a typecheck error, so I pulled the first thing I found that looked like what it was complaining about.

Comment (a-b-r-o-w-n) [reply Composer/packages/client/src/pages/botProject/adapters/ExternalAdapterModal.tsx:38]: Ok. Not a big deal if that doesn't correct the issue.

File: Composer/packages/client/src/pages/botProject/adapters/ExternalAdapterModal.tsx (hunk 2 above)
Comment (beyackle) [reply Composer/packages/client/src/pages/botProject/adapters/ExternalAdapterModal.tsx:55]: The only possible things `value` can be are `null` or an object with settings in it; if it's `null` then we're in the case where we tried to find settings in appSettings.json and they weren't there. That being said, it makes sense to use the coalesce operator here, so I'll do that.

**Review by carlosscastro — APPROVED** [review]
