### PR TITLE
fix: Change Microsoft.UpdateActivity title from "Send an activity" to "Update an activity"

### LINKED ISSUE #4656: [Minor] Send an activity should be Update an activity action
## Describe the bug

Select **Update activity** action from the **Manage properties** menu, the action will show as **Send an activity** action on both the properties panel and authoring canvas.

image

image

## Version

[Electron 1.1.1-nightly.181088.77ad8e1](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.181088.77ad8e1)

## Browser

- [x] Electron distribution

## OS

- [x] Windows

## To Reproduce

1. Select **Manage properties** from the actions menu
2. Select **Update activity**
3. See the error

## Expected behavior

The **Send an activity** action should be **Update an activity** action displayed in both the authoring canvas and the properties pane.

### PR DESCRIPTION
**Pull request by zhixzhan**
## Description

Update schema title.

## Task Item
close #4656 

## Screenshots

image

### CODE REVIEW

File: Composer/packages/server/schemas/sdk.pl.schema [hunk 1]
```diff
@@ -4348,7 +4348,7 @@
       }
     },
     "Microsoft.UpdateActivity": {
-      "title": "Wyślij działanie",
+      "title": "Zmodernizować działanie",
```
Comment (zhixzhan) [inline Composer/packages/server/schemas/sdk.pl.schema:4351]: The google translate 'update' result.

File: Composer/packages/server/schemas/sdk.sv.schema [hunk 2]
```diff
@@ -4348,7 +4348,7 @@
       }
     },
     "Microsoft.UpdateActivity": {
-      "title": "Skicka en aktivitet",
+      "title": "Uppdatera en aktivitet",
```
Comment (zhixzhan) [inline Composer/packages/server/schemas/sdk.sv.schema:4351]: The google translate 'update' result in Swedish.

**Review by boydc2014 — APPROVED** [review]

**Review by boydc2014 — APPROVED** [review]
