### PR TITLE
a11y: add arialabel and make lg/lu nav operable by keyboard

### LINKED ISSUE #2047: [Accessibility][Keyboard Navigation - User Input]: 'All' and specific user input section is not accessible via Keyboard.
**User Experience:**
For keyboard users it is difficult to complete the task is if any control is not accessible via keyboard.

**Test Environment:**
Environment: Chromium Edge (Anaheim) + Narrator
Build Version: 2004 (OS Build 19564.1005)​​
Microsoft Edge Version: 82.0.425.0 (Official build) canary (64-bit)​
Test URL: http://localhost:3000/home

**Repro Steps:**
1. Open URL: http://localhost:3000/home
2. Select 'User Input' link from left navigation.
3. Observe the issue.

**Actual Result:**
'All' and specific user input section is not accessible via Keyboard. On clicking using mouse, these controls are interactive as action is getting performed but its not accessible with keyboard.

**Note:**
Same issue is repro for 'Bot responses'.

**Expected Result:**
'All' and specific user input section should be accessible via Keyboard.

**MAS Reference:**
https://microsoft.sharepoint.com/:w:/r/sites/accessibility/CELA/Official_Microsoft_Accessibility_Standards/MAS%202.1.1%20%E2%80%93%20Keyboard.docx?d=w1f29acf9a3e7414fbd8d7e3598d877bb&csf=1&e=LSJeSF

**Attachment:**
[MAS2.1.1_Bot responses_.zip](https://github.com/microsoft/BotFramework-Composer/files/4239008/MAS2.1.1_Bot.responses_.zip)
[MAS2.1.1_User Input_Bot responses.zip](https://github.com/microsoft/BotFramework-Composer/files/4239009/MAS2.1.1_User.Input_Bot.responses.zip)

### PR DESCRIPTION
**Pull request by liweitian**
## Description
1. add arialabel.
2. make lg/lu nav operable by keyboard
## Task Item
closes #2047 
## Screenshots
aaaaa

### CODE REVIEW

File: Composer/packages/client/src/components/NavLinks/index.tsx [hunk 1]
```diff
@@ -21,15 +21,16 @@ export const NavLinks: React.FC<NavLinksProps> = props => {
...
             key={dialog.id}
             onClick={() => {
               onSelect(dialog.id);
             }}
-          >
-            {dialog.name}
-          </div>
+            styles={fileId === dialog.id ? dialogItemSelected : dialogItemNotSelected}
+            text={dialog.name}
+            ariaLabel={dialog.id + 'language understanding file'}
```
Comment (a-b-r-o-w-n) [inline Composer/packages/client/src/components/NavLinks/index.tsx]: 1) this should be translated
2) there probably should be a space between the dialog id and the rest of the text

File: Composer/packages/client/src/components/NavLinks/index.tsx [hunk 2]
```diff
@@ -5,9 +5,9 @@
 
 import { jsx } from '@emotion/core';
 import React, { Fragment } from 'react';
+import { DefaultButton } from 'office-ui-fabric-react/lib/Button';
 
-import { dialogItem } from '../../pages/language-understanding/styles';
-
+import { dialogItemSelected, dialogItemNotSelected } from '../../pages/language-understanding/styles';
```
Comment (a-b-r-o-w-n) [inline Composer/packages/client/src/components/NavLinks/index.tsx]: This seems like a smell to me. Should these styles be defined next to nav links?

File: Composer/packages/client/src/pages/language-understanding/index.tsx [hunk 3]
```diff
@@ -105,15 +107,14 @@ const LUPage: React.FC<LUPageProps> = props => {
...
+          <DefaultButton
             key={'_all'}
             onClick={() => {
               onSelect('all');
             }}
-          >
-            {'All'}
-          </div>
+            styles={isRoot ? dialogItemSelected : dialogItemNotSelected}
+            text={'All'}
```
Comment (a-b-r-o-w-n) [inline Composer/packages/client/src/pages/language-understanding/index.tsx]: This should be translated.
