### PR TITLE
fix: Problems pane reset

### LINKED ISSUE #8345: Problems pane defaults settings should be to show both errors and warning and all bots
## Describe the bug

The Problems pane should be not remember settings when you switch bots. It should reset to show all errors, all warnings, and for all bots each time you open a bot in Composer.

## Version

2.0.0-nightly.258070.287a4dc

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Open any bot that does not have multiple bots.
2. Go back to the home page.
4. Open an enterprise assistant bot.
5. Open Problems pane and see that the pane is filtered to just the root bot.

## Expected behavior

The Problems pane defaults should be reset to show everything (errors, warning, all bots) whenever I (re-)open a bot.

## Screenshots

https://user-images.githubusercontent.com/39317542/125354199-5fbeeb80-e318-11eb-9e6c-fed556645038.mov

### PR DESCRIPTION
**Pull request by srinaath**
## Description
This PR
1. Resets the show warning and show error states in the DebuPane to true when swapping bots
2. When a bot project is opened it defaults to "All" option to show errors and warnings across bots. When a new skill is added to the solution it sets it again to "All" option.

## Task Item
Fixes #8345

### CODE REVIEW

File: Composer/packages/client/src/components/DropdownWithAllOption/DropdownWithAllOption.tsx [hunk 1]
```diff
@@ -24,12 +24,11 @@ export const DropdownWithAllOption: React.FC<DropdownWithAllOptionProps> = (prop
 
   const currentOptions = useMemo(() => {
     const allOptions = [...dropdownOptions];
-    if (allOptions.length > 1) {
-      allOptions.unshift({
-        key: optionAll.key,
-        text: optionAll.text,
-      });
-    }
+
```
Comment (hatpick) [inline Composer/packages/client/src/components/DropdownWithAllOption/DropdownWithAllOption.tsx:27]: nit: ```return [optionAll, ...dropdownOptions];```

**Review by boydc2014 — APPROVED** [review]
