### PR TITLE
fix: adjust get started tasks

### LINKED ISSUE #7106: Auto-created publish profile from download doesn't proactively communicate need to complete step
## Describe the bug

The auto-created publish profile when you create from ABS is incomplete (needs other resources created).  You dont' find that out though until you try to publish and get a somewhat inscrutable error.  We should have some form of proactive communication of what to do after it's create for you.

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1) Create bot in composer
2) Create azure bot in abs portal
3) Open in composer
4) Connect to existing bot (from step 1)
5) Try to publish
<error; publish profile not provisioned yet>

## Screenshots

image

### LINKED ISSUE #7323: R13 Bugbash: Enterprise Assistant template creation is blocked without the EA readme shown in Rocket menu
## Describe the bug

For creation of a bot using Enterprise assistant, to test that locally, just adding LUIS key and QnAMaker key is not sufficient. Azure Bot Registration for root bot and 2 skills, and authentication configurations are also required to test locally. However,  the current rocket menu after Enterprise assistant is created using the template is very confusing with only "Add a LUIS key" and "Add a QnA key" under Required. 

image

## Expected behavior

The Enterprise assistant template readme should be added under Required (before LUIS and QnA key) in the Rocket menu

image

## Version

image

## Browser

- [x ] Electron distribution

## OS

- [ x] Windows

### PR DESCRIPTION
**Pull request by benbrown**
## Description

* If a bot has a README in the project folder, a new "View template readme" button will appear in the get started. This will open the readme, and navigate the user to the settings page where the "view readme" button can be found.
* If a bot has a partial publishing profile from an ABS-handoff, a new "Complete publishing profile" button will appear. This will lead the user to the publishing page and open the modal

* In addition, the LU and LG buttons hae been moved from optional to recommended.

## Task Item

Fixes #7106 
Fixes #7323 

## Screenshots

Screen Shot 2021-04-23 at 4 48 58 PM

### CODE REVIEW

File: Composer/packages/client/src/components/GetStarted/GetStartedNextSteps.tsx [hunk 1]
```diff
@@ -292,6 +335,14 @@ export const GetStartedNextSteps: React.FC<GetStartedProps> = (props) => {
           }}
           onToggleVisibility={setDisplayManageQNA}
         />
+        <DisplayMarkdownDialog
+          content={readme}
+          hidden={readmeHidden}
+          title={'Project Readme'}
```
Comment (hatpick) [inline Composer/packages/client/src/components/GetStarted/GetStartedNextSteps.tsx:341]: formatMessage 😃

Comment (benbrown) [reply Composer/packages/client/src/components/GetStarted/GetStartedNextSteps.tsx]: good catch - there was another one too!

**Review by a-b-r-o-w-n — APPROVED** [review]
