### PR TITLE
fix: use ':' instead of '=' for prefix

### LINKED ISSUE #2222: Drop adding `=` prefix if property value starts with `=`
Consider dropping double `=` if property value already has `=` prefix.

image

### PR DESCRIPTION
**Pull request by alanlong9278**
## Description
 Use `:` instead of `=` for prefix

## Task Item
closes #2222 

## Screenshots

image

### CODE REVIEW

**Comment by cwhitten** [comment]
@alanlong9278 we decided we wanted to keep the expression = sign but replace the assignment operator in the node with `:`, so:

`somval: =somefunc`

Can you update this?

**Comment by alanlong9278** [comment]
> @alanlong9278 we decided we wanted to keep the expression = sign but replace the assignment operator in the node with `:`, so:
> 
> `somval: =somefunc`
> 
> Can you update this?

Sure.

File: Composer/packages/extensions/visual-designer/src/utils/prefixOperation.ts [hunk 1]
```diff
@@ -0,0 +1,17 @@
+// Copyright (c) Microsoft Corporation.
+// Licensed under the MIT License.
+
+export function addEqualPrefix(first: string, second: string): string {
```
Comment (boydc2014) [inline Composer/packages/extensions/visual-designer/src/utils/prefixOperation.ts]: Since we just move from = to :, do we still need this function?

Comment (alanlong9278) [reply Composer/packages/extensions/visual-designer/src/utils/prefixOperation.ts]: > Since we just move from = to :, do we still need this function?

revert code for the new logic
