### PR TITLE
fix: bot load files include form dialog generated files

### LINKED ISSUE #5763: Form generation is broken because composer copies root LG templates to children LG files
## Describe the bug

If you build a form and generate it, you will get a whole lot of errors.  The reason seems to be that composer is copying root bot templates into the child LG files as empty templates which then causes there to be duplicate template names.

Everything after > Generator was added by composer--it should not.

```
[Name](Name/sandwich-Name.en-us.lg)
[personNameEntity](form/sandwich-personNameEntity.en-us.lg)
[Bread](Bread/sandwich-Bread.en-us.lg)
[BreadEntity](Bread/sandwich-BreadEntity.en-us.lg)
[Meat](Meat/sandwich-Meat.en-us.lg)
[MeatEntity](Meat/sandwich-MeatEntity.en-us.lg)
[Cheese](Cheese/sandwich-Cheese.en-us.lg)
[CheeseEntity](Cheese/sandwich-CheeseEntity.en-us.lg)
[Toppings](Toppings/sandwich-Toppings.en-us.lg)
[ToppingsEntity](Toppings/sandwich-ToppingsEntity.en-us.lg)
[Sauces](Sauces/sandwich-Sauces.en-us.lg)
[SaucesEntity](Sauces/sandwich-SaucesEntity.en-us.lg)
[moneyEntity](form/sandwich-moneyEntity.en-us.lg)
[Price](Price/sandwich-Price.en-us.lg)
[Quantity](Quantity/sandwich-Quantity.en-us.lg)
[numberEntity](form/sandwich-numberEntity.en-us.lg)
[dimensionEntity](form/sandwich-dimensionEntity.en-us.lg)
[Length](Length/sandwich-Length.en-us.lg)
[booleanEntity](form/sandwich-booleanEntity.en-us.lg)
[stringEntity](form/sandwich-stringEntity.en-us.lg)
[form-Choose](form/sandwich-form-Choose.en-us.lg)
[form-DisplayOperation](form/sandwich-form-DisplayOperation.en-us.lg)
[form-Show](form/sandwich-form-Show.en-us.lg)
[form](form/sandwich-form.en-us.lg)

> Generator: 5094d744401f1289098a7a1995f9bb91
# Name_Help()
-
# Name_ClearConfirmation()
-
# Name_Show()
-
LOTS MORE
```

## Version
image

## Browser

- [ x] Electron distribution

## OS

- [x ] Windows

### LINKED ISSUE #5982: Bugbash(private): common.lu is not showing up in editor or triggers, but it is on disk
Build: Private daily (Tai)

Scenario: 
* Use & import common.lu in dialog \[import]\(.language-understanding/en-us/common.lu)
* Import entry shows empty in editor, triggers are also empty
* File on disk looks good.
* This worked on 1.3.1 (no change in bot, just updated composer build).

image

image

image

### PR DESCRIPTION
**Pull request by zhixzhan**
## Description

Bot load files include form dialog paths and file name not include locale, the updated pattern is:

```
'language-generation/**/*.lg',
'language-understanding/**/*.lu',
'knowledge-base/**/*.qna',
```

## Task Item
close #5763 
close #5982 

## Screenshots
image

### CODE REVIEW

File: Composer/packages/server/src/models/bot/botStructure.ts [hunk 1]
```diff
@@ -94,6 +82,15 @@ export const BotStructureFilesPatterns = [
   templateInterpolate(BotStructureTemplate.crossTrainConfig, { CROSSTRAINCONFIGNAME: 'cross-train.config.json' }),
   '*.schema',
   '*.uischema',
+  'language-generation/**/*.lg',
+  'language-understanding/**/*.lu',
+  'knowledge-base/**/*.qna',
+  'dialogs/*/language-generation/**/*.lg',
+  'dialogs/*/language-understanding/**/*.lu',
+  'dialogs/*/knowledge-base/**/*.qna',
+  'dialogs/imported/*/language-generation/**/*.lg',
```
Comment (boydc2014) [inline Composer/packages/server/src/models/bot/botStructure.ts:91]: in which case we have this "imported" path?

**Review by boydc2014 — APPROVED** [review]

**Review by boydc2014 — APPROVED** [review]
