### PR TITLE
fix: share name field between two create kb modal

### LINKED ISSUE #7196: QnA Maker New "From Scratch" UI Tweaks
## Describe the bug

A few UX issues here:
1. [ ] On the "From scratch" dialog for QnA Maker, the "Knowledge base and "KB" are used interchangeably. Choose one. Follow the QnA Maker standard. Note that in the [QnA Maker docs (found here)](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/concepts/data-sources-and-content#structured-multi-turn-format-through-import) they NEVER use "KB". 
2. [ ] "From scratch" is really awkward. Consider just deleting. 
3. [ ] No period after the "KB" on the "Manually add question" line. 
4. [ ] "Type a name that describes this content" should probably be "Type a name for this Knowledge Base". 
5. [ ] Remove the "X" from the top-right, so I can't close the dialog that way. 

image

## Version

Version:  1.4.0-nightly.237101.f01cb52
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

### LINKED ISSUE #7197: QnA Maker "From Scratch" not carrying over Name
## Describe the bug
On the QnA Maker "Create New" screen I create a new Knowledge Base and hit the Create from Scratch Button. 

image

I expect to see the name I typed out on the next screen.
image

## Version

Version:  1.4.0-nightly.237101.f01cb52
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution

### PR DESCRIPTION
**Pull request by liweitian**
## Description
share name field between two creating kb modal and update text

## Task Item
Closes #7197
Closes #7196

## Screenshots
createQnA

### CODE REVIEW

File: Composer/packages/client/src/components/QnA/constants.ts [hunk 1]
```diff
@@ -45,7 +47,9 @@ export type CreateQnAFromUrlModalProps = {
   defaultLocale: string;
   dialogId: string;
   qnaFiles: QnAFile[];
+  initialName?: string;
   subscriptionKey?: string;
+  setInitialName?: (initialName: string) => void;
```
Comment (hatpick) [inline Composer/packages/client/src/components/QnA/constants.ts:52]: onUpdateInitialName

**Review by hatpick — CHANGES_REQUESTED** [review]

**Review by hatpick — APPROVED** [review]
