### PR TITLE
fix: Refactor LUIS, QNA and Speech to use a single base component

### LINKED ISSUE #6804: Updated UX for QnA/LUIS/Speech dev keys
## Describe the bug
Users are currently prompted to login before selecting how they'd like to add keys. One option, handoff to Azure admin, doesn't require logging in. This updated UX moves the login and subscription selection to the second step. Also minor copy updates for handoff to admin.

Figma: https://www.figma.com/file/tvENftrexoAYJngzsJxUbv/EmFig?node-id=3485%3A360

## Screenshots
image

## Additional context
UX is shown for QnA maker but same logic applies to LUIS and Speech.

### LINKED ISSUE #6874: Creating QnAMaker resource taking up to 20+ minutes
## Describe the bug

Creating a QnA Maker resource through Composer is taking in excess of 20+ minutes.

## Version

Version:  1.4.0-nightly.233776.7019ef0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new Bot
2. Add Knowledge Base
3. Generate QnA Maker instance
4. Process takes 20 minutes even to fail and tell you that you have too many free instances

## Expected behavior

Process completes quicker or is ASync to allow me to do other things.

## Screenshots

image

### LINKED ISSUE #7009: Add QnA Maker key fails in Next Steps
## Describe the bug

When creating a bot from the QnA Maker Bot template and then going through Next Steps to create a new QnA Maker service in Azure.  The following message is received:
image

## Version

Version:  1.4.0-nightly.235590.f4de79
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new QnA Bot from Template
2. Add a QnA Maker key by following the process in Next Steps
3. Get Error
4. Start Bot and try to ask a question in the KB and get error below

## Expected behavior

QnA Maker key and project is setup where I can test the bot and the QnA Maker content that by using start bot button.

## Additional context

It seems that the process worked, however when I try to start the bot and ask a question in the QnA KB you get this error:
image

### PR DESCRIPTION
**Pull request by benbrown**
## Description

* Refactor LUIS, QNA and Speech to use a common base component
* Implement UX revisions

## Task Item

Fixes #6804 
Fixes #7009 
Fixes #6874

### CODE REVIEW

**Review by pavolum — APPROVED** [review]

File: Composer/packages/client/src/components/ManageService/ManageService.tsx [hunk 1]
```diff
@@ -0,0 +1,693 @@
...
+              }
+              placeholder={formatMessage('Select one')}
+              selectedKey={subscriptionId}
+              styles={dropdownStyles}
+              onChange={onChangeSubscription}
+            />
+          </div>
+          <div>
+            {noKeys && subscriptionId && (
+              <span style={{ color: 'rgb(161, 159, 157)' }}>
```
Comment (beyackle) [inline Composer/packages/client/src/components/ManageService/ManageService.tsx:474]: Can we get this color from an existing UI palette?

File: Composer/packages/client/src/components/ManageQNA/ManageQNA.tsx [hunk 2]
```diff
@@ -3,706 +3,173 @@
...
-          needGraph={false}
-          next={hasAuth}
-          onDismiss={() => {
-            setShowAuthDialog(false);
-          }}
-        />
+    <ManageService
+      createService={createService}
+      handoffInstructions={formatMessage(
+        'I am working on a Microsoft Bot Framework project, and I now require some Azure resources to be created. Please follow the instructions below to create these resources and provide them to me.\n\n1. Using the Azure portal, please create a QnAMaker resource on my behalf.\n2. Once provisioned, securely share the resulting credentials with me as described in the link below.\n\nDetailed instructions:\nhttps://aka.ms/bfcomposerhandoffqnamaker'
```
Comment (beyackle) [inline Composer/packages/client/src/components/ManageQNA/ManageQNA.tsx:163]: Since this string is mostly the same in all three of these subpages, could we refactor it as well into the ManageService component and just provide the URL as a prop? It looks like you already have the service name coming as one.

**Review by beyackle — CHANGES_REQUESTED** [review]
Looks mostly good; I just have an idea for how to simplify it a little further.

File: Composer/packages/client/src/components/ManageQNA/ManageQNA.tsx (hunk 2 above)
Comment (benbrown) [reply Composer/packages/client/src/components/ManageQNA/ManageQNA.tsx:163]: I thought about that, but I think there is a high degree of likelihood that these instructions DO become more differentiated as we move forward.  Would prefer to let the full text be specified for now.

Comment (beyackle) [reply Composer/packages/client/src/components/ManageQNA/ManageQNA.tsx:163]: Can we at least refactor out the first half of it, up to the "provide them to me"? That seems unlikely to change.

File: Composer/packages/client/src/components/ManageService/ManageService.tsx (hunk 1 above)
Comment (benbrown) [reply Composer/packages/client/src/components/ManageService/ManageService.tsx]: yup!

**Review by pavolum — DISMISSED** [review]

**Comment by cwhitten** [comment]
@benbrown typescript is grumpy about something

File: Composer/packages/client/src/recoilModel/dispatchers/provisionQNA.ts [hunk 3]
```diff
@@ -0,0 +1,220 @@
...
+        const webAppResult = await webSiteManagementClient.webApps.createOrUpdate(
+          resourceGroupName,
+          qnaMakerWebAppName,
+          {
+            name: qnaMakerWebAppName,
+            serverFarmId: resourceGroupName,
+            location: region,
+            siteConfig: {
+              cors: {
+                allowedOrigins: ['*'],
```
Comment (srinaath) [inline Composer/packages/client/src/recoilModel/dispatchers/provisionQNA.ts:125]: Is this something we want? Setting the CORS policy for a service to \* can be risky. Maybe allow just the MSAppID of the bot.

Comment (benbrown) [reply Composer/packages/client/src/recoilModel/dispatchers/provisionQNA.ts:125]: This is how we provision QNA during the provisioning process, and in our ARM templates.

File: Composer/packages/client/src/components/ManageService/ManageService.tsx [hunk 4]
```diff
@@ -0,0 +1,702 @@
...
+  handoffInstructions: string;
+  hidden: boolean;
+  learnMore?: string;
+  onDismiss: () => void;
+  onGetKey: (settings: { key: string; region: string }) => void;
+  onNext?: () => void;
+  serviceName: string;
+  regions?: IDropdownOption[];
+  serviceKeyType: string;
+  setVisible: (value: any) => void;
```
Comment (hatpick) [inline Composer/packages/client/src/components/ManageService/ManageService.tsx:50]: this is a callback, name it accordingly, onToggleVisibility: (visible: boolean) => void

File: Composer/packages/client/src/components/ManageService/ManageService.tsx [hunk 5]
```diff
@@ -0,0 +1,702 @@
...
+  const [resourceGroups, setResourceGroups] = useState<any[]>([]);
+  const [createResourceGroup, setCreateResourceGroup] = useState<boolean>(false);
+  const [newResourceGroupName, setNewResourceGroupName] = useState<string>('');
+  const [resourceGroupKey, setResourceGroupKey] = useState<string>('');
+  const [resourceGroup, setResourceGroup] = useState<string>('');
+
+  const [showHandoff, setShowHandoff] = useState<boolean>(false);
+  const [resourceName, setResourceName] = useState<string>('');
+  const [loading, setLoading] = useState<string | undefined>(undefined);
+  const [noKeys, setNoKeys] = useState<boolean>(false);
```
Comment (hatpick) [inline Composer/packages/client/src/components/ManageService/ManageService.tsx:82]: can you track this with ```keys.length``` state? do you really need an extra state for it?

File: Composer/packages/client/src/components/ManageService/ManageService.tsx [hunk 6]
```diff
@@ -0,0 +1,702 @@
...
+        }
+      }
+    }
+    return keyList;
+  };
+
+  const fetchAccounts = async (subscriptionId) => {
+    if (token) {
+      setLoading(formatMessage('Loading keys...'));
+      setNoKeys(false);
```
Comment (hatpick) [inline Composer/packages/client/src/components/ManageService/ManageService.tsx:194]: before you fetch the keys, no keys should be ```true``` meaning no keys right?

File: Composer/packages/client/src/components/ManageService/ManageService.tsx (hunk 5 above)
Comment (hatpick) [reply Composer/packages/client/src/components/ManageService/ManageService.tsx:82]: if you decided to keep it, shouldn't it be true by default?

File: Composer/packages/client/src/components/ManageService/ManageService.tsx [hunk 7]
```diff
@@ -0,0 +1,702 @@
...
+
+  // allow a user to provide a subscription id if one is missing
+  const onChangeSubscription = async (_, opt) => {
+    // get list of keys for this subscription
+    setSubscription(opt.key);
+    fetchAccounts(opt.key);
+    setLoading(formatMessage('Loading subscription...'));
+    // if we don't have a list of regions already passed in
+    if (!props.regions) {
+      fetchLocations(opt.key);
```
Comment (hatpick) [inline Composer/packages/client/src/components/ManageService/ManageService.tsx:341]: should it await here?

File: Composer/packages/client/src/components/ManageService/ManageService.tsx [hunk 8]
```diff
@@ -0,0 +1,702 @@
...
+    }
+    fetchResourceGroups(opt.key);
```
Comment (hatpick) [inline Composer/packages/client/src/components/ManageService/ManageService.tsx:343]: await?

File: Composer/packages/client/src/components/ManageService/ManageService.tsx [hunk 9]
```diff
@@ -0,0 +1,702 @@
...
+
+      setCurrentPage(3);
+    }
+  };
+
+  // allow a user to provide a subscription id if one is missing
+  const onChangeSubscription = async (_, opt) => {
+    // get list of keys for this subscription
+    setSubscription(opt.key);
+    fetchAccounts(opt.key);
```
Comment (hatpick) [inline Composer/packages/client/src/components/ManageService/ManageService.tsx:337]: await?

Comment (benbrown) [reply Composer/packages/client/src/components/ManageService/ManageService.tsx:337]: why?

Comment (benbrown) [reply Composer/packages/client/src/components/ManageService/ManageService.tsx:337]: we can fire all these API calls at once instead of awaiting each one.

Comment (hatpick) [reply Composer/packages/client/src/components/ManageService/ManageService.tsx:337]: both the caller and the context are async, but neither is being awaited, I'm asking if it should be.

File: Composer/packages/client/src/components/ManageService/ManageService.tsx (hunk 6 above)
Comment (benbrown) [reply Composer/packages/client/src/components/ManageService/ManageService.tsx:194]: the noKeys flag should only be true if the query has returned no keys.

File: Composer/packages/client/src/components/ManageService/ManageService.tsx (hunk 5 above)
Comment (benbrown) [reply Composer/packages/client/src/components/ManageService/ManageService.tsx:82]: No because empty because it hasn't loaded is different than empty because there really are no keys.

File: Composer/packages/client/src/components/ManageService/ManageService.tsx (hunk 9 above)
Comment (benbrown) [reply Composer/packages/client/src/components/ManageService/ManageService.tsx:337]: I don't think so!  I guess I could remove the async on that onChangeSubscription...

File: Composer/packages/client/src/components/ManageService/ManageService.tsx [hunk 10]
```diff
@@ -0,0 +1,702 @@
...
+        }
+      } catch (err) {
+        setOutcomeDescription(
+          formatMessage(
+            'Due to the following error, we were unable to successfully add your selected {service} keys to your bot project:',
+            { service: props.serviceName }
+          )
+        );
+        setOutcomeSummary(
+          <div>
```
Comment (srinaath) [inline Composer/packages/client/src/components/ManageService/ManageService.tsx:290]: is this div wrapper required?

File: Composer/packages/client/src/components/ManageService/ManageService.tsx (hunk 9 above)
Comment (hatpick) [reply Composer/packages/client/src/components/ManageService/ManageService.tsx:337]: It' all good, I was just making sure.

File: Composer/packages/client/src/recoilModel/dispatchers/provisionQNA.ts [hunk 11]
```diff
@@ -0,0 +1,220 @@
...
+        );
+        await cognitiveServicesManagementClient.accounts.create(resourceGroupName, qnaMakerServiceName, {
+          kind: 'QnAMaker',
+          sku: {
+            name: 'F0',
+          },
+          location: region,
+          properties: {
+            apiProperties: {
+              qnaRuntimeEndpoint: `https://${webAppResult.hostNames?.[0]}`,
```
Comment (srinaath) [inline Composer/packages/client/src/recoilModel/dispatchers/provisionQNA.ts:183]: does it make sense wrap the whole account creation inside if (webAppResult.hostNames?\[0\]) as the the endpoint has a chance of https://undefined here.

File: Composer/packages/client/src/pages/publish/Notifications.tsx [hunk 12]
```diff
@@ -90,3 +90,43 @@ export const getPendingNotificationCardProps = (items: BotStatus[]): CardProps =
...
+  };
+};
+
+export const getCompletedQNANotificationCardProps = (opts: { time: number }): CardProps => {
+  const statusIconStyle = css({
+    margin: '12px 0 0 -1px',
+    width: '12px',
+    height: '12px',
+    fontSize: '12px',
+    color: '#27AE60',
```
Comment (srinaath) [inline Composer/packages/client/src/pages/publish/Notifications.tsx:116]: can we get the closest matching color from FluentTheme.palette or Shared, Communication coors

File: Composer/packages/client/src/recoilModel/dispatchers/provisionQNA.ts (hunk 11 above)
Comment (benbrown) [reply Composer/packages/client/src/recoilModel/dispatchers/provisionQNA.ts:183]: This should never happen because a failure of the webapp call will throw an error, HOWEVER I did a test for this condition and threw my own error just in case.

**Review by srinaath — APPROVED** [review]

**Review by srinaath — APPROVED** [review]
