### PR TITLE
fix: location select Content component

### LINKED ISSUE #1291: UX - Templates should get a default name
When opening a template, the user will likely expect to immediately see that template. Instead, one gets a file-new kind of experience. This is fine, but it'd be more userfriendly to pre-name the file, starting with the template name and a number or other so that the user can just hit next/open and continue the process vs stop and think what to name a file they didnt create on their own nor have seen what it contains. 

Screen Shot 2019-10-28 at 10 58 51 AM

### LINKED ISSUE #1603: unable to enter custom name for new bot
## Describe the bug
#1583 introduced a bug in which a user is unable to type a custom name for a new bot because the input field cannot be cleared. It is always reset to the 'default' name.

## Version
21516678c2

### PR DESCRIPTION
**Pull request by liweitian**
## Description
Refactor the locationSelectContent part to make it more pure. 

The overall idea/code flow becomes. Every time we changed the location(the last accessed path), it will save to data.json, then the storages in stores(global state) will be changed too. This will trigger updating the focuedStorageFolder.

## Task Item
closes #1603 
closes #1291

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code refactor (non-breaking change which improve code quality, clean up, add tests, etc)
## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have functionally tested my change

### CODE REVIEW

File: Composer/packages/client/src/CreationFlow/DefineConversation/index.js [hunk 1]
```diff
@@ -59,6 +75,22 @@ export function DefineConversation(props) {
...
+    let i = 0;
+    const bot = templateId || botName;
+    let defaultName = `${bot}-${i}`;
+
+    while (
+      bots.findIndex(bot => {
+        return bot.name === defaultName;
+      }) > -1
+    ) {
+      i = i + 1;
```
Comment (compulim) [inline Composer/packages/client/src/CreationFlow/DefineConversation/index.js]:
```suggestion
      i++;
```

File: Composer/packages/client/src/CreationFlow/DefineConversation/index.js [hunk 2]
```diff
@@ -59,6 +75,22 @@ export function DefineConversation(props) {
...
 
+  function getDefaultName() {
+    let i = 0;
+    const bot = templateId || botName;
+    let defaultName = `${bot}-${i}`;
+
+    while (
+      bots.findIndex(bot => {
+        return bot.name === defaultName;
+      }) > -1
```
Comment (compulim) [inline Composer/packages/client/src/CreationFlow/DefineConversation/index.js]: The better way for determining whether `index === -1` or not, is using `~index`. It's called bitwase-negate. Since number in JavaScript is "two's complement", negating -1 will be 0.

```js
~(-1) === 0 //falsy
~(0) is truthy
~(1) is truthy, etc
```

File: Composer/packages/client/src/CreationFlow/DefineConversation/index.js [hunk 3]
```diff
@@ -59,6 +75,22 @@ export function DefineConversation(props) {
     });
   };
 
+  function getDefaultName() {
+    let i = 0;
+    const bot = templateId || botName;
+    let defaultName = `${bot}-${i}`;
+
+    while (
+      bots.findIndex(bot => {
```
Comment (compulim) [inline Composer/packages/client/src/CreationFlow/DefineConversation/index.js]: Add a maximum retry for defensive programming reason. I.e. if index > 10000, we shouldn't proceed and throw an error. Otherwise, we will hang the app.

File: Composer/packages/client/src/CreationFlow/DefineConversation/index.js [hunk 4]
```diff
@@ -59,6 +75,22 @@ export function DefineConversation(props) {
     });
   };
 
+  function getDefaultName() {
+    let i = 0;
+    const bot = templateId || botName;
```
Comment (compulim) [inline Composer/packages/client/src/CreationFlow/DefineConversation/index.js]: We are constructing the bot name in two path.

You should use a do-while loop, which should eliminate constructing twice.

File: Composer/packages/client/src/CreationFlow/DefineConversation/index.js [hunk 5]
```diff
@@ -109,7 +136,14 @@ export function DefineConversation(props) {
             />
           </StackItem>
         </Stack>
-        {enableLocationBrowse && <LocationSelectContent onChange={updateLocation} allowOpeningBot={false} />}
+        {enableLocationBrowse && (
+          <LocationSelectContent
+            updateCurrentPath={updateCurrentPath}
+            allowOpeningBot={false}
```
Comment (compulim) [inline Composer/packages/client/src/CreationFlow/DefineConversation/index.js]: If we don't have path for `true`, let's remove this prop and remove unneeded code paths.

File: Composer/packages/client/src/CreationFlow/LocationBrowser/LocationSelectContent.tsx [hunk 6]
```diff
@@ -2,60 +2,19 @@
...
-
 import { jsx } from '@emotion/core';
-import { Fragment, useEffect, useState, useContext, useRef } from 'react';
+import { Fragment, useContext, useRef } from 'react';
 
 import { FileSelector } from './FileSelector';
 import { StoreContext } from './../../store';
 import { FileTypes } from './../../constants';
 
 export function LocationSelectContent(props) {
```
Comment (compulim) [inline Composer/packages/client/src/CreationFlow/LocationBrowser/LocationSelectContent.tsx]: You can write it like this to simplify the code.

```suggestion
export function LocationSelectContent({ onOpen, allowOpeningBot = true, focusedStorageFolder, updateCurrentPath, currentPath }) {
```

File: Composer/packages/client/src/CreationFlow/index.js [hunk 7]
```diff
@@ -21,8 +21,27 @@ export function CreationFlow(props) {
...
+    openBotProject,
+    createProject,
+    saveProjectAs,
+    saveTemplateId,
+    fetchStorages,
+    fetchFolderItemsByPath,
+  } = actions;
+  const { templateId, templateProjects, focusedStorageFolder, storages } = state;
+  const currentStorageIndex = useRef(0);
+  const currentStorageId = storages[currentStorageIndex.current] ? storages[currentStorageIndex.current].id : 'default';
```
Comment (compulim) [inline Composer/packages/client/src/CreationFlow/index.js]: Cache `storages[currentStorageIndex.current]` so we don't need to get it twice.

In JavaScript, every member accessor is very expensive, unlike C#. This is because JavaScript is prototypical object-oriented model, there are no virtual tables. In contrast, C# is inheritance OO model. So when writing code, try to reduce number of `.` (dots), `[]` (indexer), etc.

File: Composer/packages/client/src/CreationFlow/index.js [hunk 8]
```diff
@@ -21,8 +21,27 @@ export function CreationFlow(props) {
...
+  const [currentPath, setCurrentPath] = useState('');
+  useEffect(() => {
+    if (storages && storages.length > 0) {
```
Comment (compulim) [inline Composer/packages/client/src/CreationFlow/index.js]:
```suggestion
    if (storages && storages.length) {
```

File: Composer/packages/client/src/CreationFlow/index.js [hunk 9]
```diff
@@ -21,8 +21,27 @@ export function CreationFlow(props) {
...
+      const storageId = storages[currentStorageIndex.current].id;
```
Comment (compulim) [inline Composer/packages/client/src/CreationFlow/index.js]: Cache `currentStorageIndex.current`.

File: Composer/packages/client/src/CreationFlow/index.js [hunk 10]
```diff
@@ -21,8 +21,27 @@ export function CreationFlow(props) {
...
+      const path = storages[currentStorageIndex.current].path;
+      const formatedPath = Path.normalize(path);
```
Comment (compulim) [inline Composer/packages/client/src/CreationFlow/index.js]:
```suggestion
      const formattedPath = Path.normalize(path);
```

File: Composer/packages/client/src/CreationFlow/index.js [hunk 11]
```diff
@@ -34,6 +53,9 @@ export function CreationFlow(props) {
     });
 
     setBots(botsInCurrentFolder);
+    if (Object.keys(focusedStorageFolder).length > 0) {
```
Comment (compulim) [inline Composer/packages/client/src/CreationFlow/index.js]:
```suggestion
    if (Object.keys(focusedStorageFolder).length) {
```

File: Composer/packages/client/src/CreationFlow/index.js [hunk 12]
```diff
@@ -66,6 +88,18 @@ export function CreationFlow(props) {
     }
   };
 
+  const updateCurrentPath = async (newPath, storageId) => {
+    if (!storageId) {
+      storageId = currentStorageId;
+    }
+    if (newPath) {
+      // const formatedPath = Path.normalize(newPath.replace(/\\/g, '/'));
```
Comment (compulim) [inline Composer/packages/client/src/CreationFlow/index.js]: Remove commented code.

File: Composer/packages/client/src/CreationFlow/index.js [hunk 13]
```diff
@@ -66,6 +88,18 @@ export function CreationFlow(props) {
     }
   };
 
+  const updateCurrentPath = async (newPath, storageId) => {
+    if (!storageId) {
+      storageId = currentStorageId;
+    }
```
Comment (compulim) [inline Composer/packages/client/src/CreationFlow/index.js]: Looks like `storageId` is no longer being used.

File: Composer/packages/client/src/CreationFlow/index.js [hunk 14]
```diff
@@ -66,6 +88,18 @@ export function CreationFlow(props) {
...
+    if (newPath) {
+      // const formatedPath = Path.normalize(newPath.replace(/\\/g, '/'));
+      const formatedPath = Path.normalize(newPath);
+      //await fetchFolderItemsByPath(storageId, formatedPath);
```
Comment (compulim) [inline Composer/packages/client/src/CreationFlow/index.js]: Remove commented code.

File: Composer/packages/client/src/store/action/storage.ts [hunk 15]
```diff
@@ -95,5 +95,15 @@ export const fetchFolderItemsByPath: ActionCreator = async ({ dispatch }, id, pa
 };
 
 export const updateCurrentPath: ActionCreator = async ({ dispatch }, path) => {
-  await httpClient.put(`/storages/currentPath`, { path: path });
+  try {
+    const response = await httpClient.put(`/storages/currentPath`, { path: path });
```
Comment (compulim) [inline Composer/packages/client/src/store/action/storage.ts]:
```suggestion
    const response = await httpClient.put(`/storages/currentPath`, { path });
```

File: Composer/packages/client/src/store/action/storage.ts [hunk 16]
```diff
@@ -95,5 +95,15 @@ export const fetchFolderItemsByPath: ActionCreator = async ({ dispatch }, id, pa
...
+    dispatch({
+      type: ActionTypes.GET_STORAGE_SUCCESS,
+      payload: {
+        response,
+      },
+    });
+  } catch (err) {
+    dispatch({ type: ActionTypes.GET_STORAGE_FAILURE, payload: null, error: err });
```
Comment (compulim) [inline Composer/packages/client/src/store/action/storage.ts]: You can make it simpler by writing it like this.

Also, is `payload: null` required? If we leave it out, it will be more like `payload: undefined`.

```js
  } catch (error) {
    dispatch({ type: ActionTypes.GET_STORAGE_FAILURE, payload: null, error });
```

File: Composer/packages/server/src/controllers/storage.ts [hunk 17]
```diff
@@ -16,8 +16,8 @@ function createStorageConnection(req: Request, res: Response) {
 }
 
 function updateCurrentPath(req: Request, res: Response) {
-  StorageService.updateCurrentPath(req.body.path);
-  res.status(200).json('success');
+  const storages = StorageService.updateCurrentPath(req.body.path);
```
Comment (compulim) [inline Composer/packages/server/src/controllers/storage.ts]: Prefer not to keep one-off result in a constant. You can just pass it in.

But depends on the team or other code, they may like this one.

File: Composer/packages/server/src/services/storage.ts [hunk 18]
```diff
@@ -96,6 +96,7 @@ class StorageService {
   public updateCurrentPath = (path: string) => {
     this.storageConnections[0].path = path;
     Store.set(this.STORE_KEY, this.storageConnections);
+    return this.storageConnections;
```
Comment (compulim) [inline Composer/packages/server/src/services/storage.ts]: I am okay to return this.storageConnections.

But I think you don't need to return this, because the caller should be able to grab it by themselves.

The better approach, which may not applies to this code, is that. If you have an update function that modify a value and return it out. It is better to treat the value immutable. That means, the function get passed in, will not be changed. The returned value will be a new one with modified content.

File: Composer/packages/client/src/CreationFlow/DefineConversation/index.js [hunk 19]
```diff
@@ -29,11 +30,26 @@ const validateForm = data => {
...
+    enableLocationBrowse,
+    focusedStorageFolder,
+    updateCurrentPath,
+    currentPath,
+    bots,
+  } = props;
+
+  const { state } = useContext(StoreContext);
+  const { storages, storageFileLoadingStatus, templateId, botName } = state;
+  const [formData, setFormData] = useState({ name: getDefaultName(), errors: {} });
```
Comment (compulim) [inline Composer/packages/client/src/CreationFlow/DefineConversation/index.js]: Can we split this into `formDataName` and `formDataErrors`?

File: Composer/packages/client/src/CreationFlow/DefineConversation/index.js [hunk 20]
```diff
@@ -29,11 +30,26 @@ const validateForm = data => {
...
   const [disable, setDisable] = useState(false);
 
+  useEffect(() => {
```
Comment (compulim) [inline Composer/packages/client/src/CreationFlow/DefineConversation/index.js]: Put this `useEffect` call below `updateForm` function.

File: Composer/packages/client/src/CreationFlow/DefineConversation/index.js [hunk 21]
```diff
@@ -109,7 +136,14 @@ export function DefineConversation(props) {
             />
           </StackItem>
         </Stack>
-        {enableLocationBrowse && <LocationSelectContent onChange={updateLocation} allowOpeningBot={false} />}
+        {enableLocationBrowse && (
+          <LocationSelectContent
+            updateCurrentPath={updateCurrentPath}
```
Comment (compulim) [inline Composer/packages/client/src/CreationFlow/DefineConversation/index.js]: Instead of passing a function to child component to use. Consider passing a function that the child component can "fire event to".

Although the code is almost the same, probably just name changes, the philosophy of sending events make your code less prone to bugs, compare to passing a function. This is because less coupling between two components.

File: Composer/packages/client/src/CreationFlow/index.js [hunk 22]
```diff
@@ -21,8 +21,27 @@ export function CreationFlow(props) {
...
+  const currentStorageId = storages[currentStorageIndex.current] ? storages[currentStorageIndex.current].id : 'default';
+  const [currentPath, setCurrentPath] = useState('');
+  useEffect(() => {
+    if (storages && storages.length > 0) {
+      const storageId = storages[currentStorageIndex.current].id;
+      const path = storages[currentStorageIndex.current].path;
+      const formatedPath = Path.normalize(path);
+      fetchFolderItemsByPath(storageId, formatedPath);
+    }
+  }, [storages]);
```
Comment (compulim) [inline Composer/packages/client/src/CreationFlow/index.js]: As `currentStorageIndex` is a ref, if it get changed, it will not run `fetchFolderItemsByPath`.

And also, I scanned the code and it seems `currentStorageIndex` never get changed, it is always `0`.

File: Composer/packages/client/src/CreationFlow/DefineConversation/index.js [hunk 23]
```diff
@@ -11,46 +13,77 @@ import { TextField } from 'office-ui-fabric-react/lib/TextField';
...
+      );
+    }
+
+    if (
+      name &&
+      ~bots.findIndex(bot => {
+        const path = Path.join(focusedStorageFolder.parent, focusedStorageFolder.name, name);
+        return bot.path === path;
+      })
+    ) {
```
Comment (a-b-r-o-w-n) [inline Composer/packages/client/src/CreationFlow/DefineConversation/index.js]: const newBotPath = Path.join(focusedStorageFolder.parent, focusedStorageFolder.name, name);

```ts
if (name && bots.find(bot => bot.path === newBotPath) {
```

It's confusing to do a double negation.

File: Composer/packages/client/src/CreationFlow/DefineConversation/index.js [hunk 24]
```diff
@@ -11,46 +13,77 @@ import { TextField } from 'office-ui-fabric-react/lib/TextField';
...
+    focusedStorageFolder,
+    onCurrentPathUpdate,
+    currentPath,
+    bots,
+  } = props;
+
+  const { state } = useContext(StoreContext);
+  const { templateId, botName } = state;
+  const [formData, setFormData] = useState({ name: getDefaultName() });
+  const [formDataErrors, setFormDataErrors] = useState({ errors: {} });
```
Comment (a-b-r-o-w-n) [inline Composer/packages/client/src/CreationFlow/DefineConversation/index.js]: `{ errors: {} }` is a different type than what `setFormDataErrors` is being invoked with. You should convert this file to typescript to catch this kind of thing.

File: Composer/packages/client/src/CreationFlow/DefineConversation/index.js [hunk 25]
```diff
@@ -59,28 +92,22 @@ export function DefineConversation(props) {
...
+    const bot = templateId || botName;
+    let defaultName = '';
+
+    do {
+      i++;
+      defaultName = `${bot}-${i}`;
+    } while (
+      ~bots.findIndex(bot => {
+        return bot.name === defaultName;
+      }) &&
```
Comment (a-b-r-o-w-n) [inline Composer/packages/client/src/CreationFlow/DefineConversation/index.js]: Again, this double negation is confusing. Just use `find` instead.

File: Composer/packages/client/src/CreationFlow/DefineConversation/index.js [hunk 26]
```diff
@@ -59,28 +92,22 @@ export function DefineConversation(props) {
...
+      i < MAXTRYTIMES
+    );
+    return defaultName;
```
Comment (a-b-r-o-w-n) [inline Composer/packages/client/src/CreationFlow/DefineConversation/index.js]: So if `MAXTRYTIMES` is reached without finding a unique name, the default name will be the last computed name and invalid right?

File: Composer/packages/client/src/CreationFlow/LocationBrowser/LocationSelectContent.tsx [hunk 27]
```diff
@@ -2,69 +2,28 @@
...
 import { jsx } from '@emotion/core';
-import { Fragment, useEffect, useState, useContext, useRef } from 'react';
+import { Fragment, useContext, useRef } from 'react';
+
+import { CreationFlowStatus } from '../../constants';
 
 import { FileSelector } from './FileSelector';
 import { StoreContext } from './../../store';
 import { FileTypes } from './../../constants';
+export function LocationSelectContent({ onOpen, focusedStorageFolder, onCurrentPathUpdate, currentPath }) {
```
Comment (a-b-r-o-w-n) [inline Composer/packages/client/src/CreationFlow/LocationBrowser/LocationSelectContent.tsx]: This should have its props interface defined.

File: Composer/packages/client/src/CreationFlow/LocationBrowser/LocationSelectContent.tsx [hunk 28]
```diff
@@ -2,69 +2,28 @@
...
-
 import { jsx } from '@emotion/core';
-import { Fragment, useEffect, useState, useContext, useRef } from 'react';
+import { Fragment, useContext, useRef } from 'react';
+
+import { CreationFlowStatus } from '../../constants';
 
 import { FileSelector } from './FileSelector';
 import { StoreContext } from './../../store';
 import { FileTypes } from './../../constants';
```
Comment (a-b-r-o-w-n) [inline Composer/packages/client/src/CreationFlow/LocationBrowser/LocationSelectContent.tsx]: Please add new line between imports and exports.

File: Composer/packages/client/src/CreationFlow/index.js (hunk 10 above)
Comment (a-b-r-o-w-n) [reply Composer/packages/client/src/CreationFlow/index.js]: This was marked resolved, but was not addressed.

File: Composer/packages/server/src/services/storage.ts [hunk 29]
```diff
@@ -93,9 +93,13 @@ class StorageService {
     }
   };
 
-  public updateCurrentPath = (path: string) => {
-    this.storageConnections[0].path = path;
-    Store.set(this.STORE_KEY, this.storageConnections);
+  public updateCurrentPath = (path: string, storageId: string) => {
+    const index = this.storageConnections.findIndex(s => s.id === storageId);
+    if (~index) {
```
Comment (a-b-r-o-w-n) [inline Composer/packages/server/src/services/storage.ts]: Double negation here again.

File: Composer/packages/client/src/CreationFlow/DefineConversation/index.js (hunk 26 above)
Comment (liweitian) [reply Composer/packages/client/src/CreationFlow/DefineConversation/index.js]: Previously, it will be an endless loop if we cannot find an unique name(probably due to a bug). According to @compulim, we should throw an error when the MAXTIMES reached. But I feel even if this do happen, we should not decrease user's experience. This is a small feature. So I keep the code this way just like what you said. If the code generate a duplicated name, an error message will show.
