### PR TITLE
fix: address a regression in the start bot button that caused final 'get started' bubb not to pop

### LINKED ISSUE #7560: [bubb] Teaching bubble for starting your bot not popping up
## Describe the bug

The teaching bubble prompting to start your bot after setting up LUIS/QnA isn't showing.

image

## Version

Version:  2.0.0-nightly.241915.204a82
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
macOS

## To Reproduce

1. Create conversation core bot
2. Go through LUIS and QnA key setup from rocket menu, selecting existing resources
3. Should get a teaching bubble prompting to start my bot, but it's not popping up for me

cc @Dewain27

### PR DESCRIPTION
**Pull request by benbrown**
## Description

This PR adds an `id` field to the start bot so it can be targetted with the teaching bubble.

## Task Item

Fixes #7560

### CODE REVIEW

**Review by srinaath — APPROVED** [review]

File: Composer/packages/client/src/components/BotRuntimeController/BotController.tsx [hunk 1]
```diff
@@ -232,6 +232,7 @@ const BotController: React.FC<BotControllerProps> = ({ onHideController, isContr
                 },
               },
             }}
+            id={'startbot'}
```
Comment (srinaath) [inline Composer/packages/client/src/components/BotRuntimeController/BotController.tsx:235]: While we are at it would it be better to give it a more specific name? startBotPanelElement or something like that?

Comment (benbrown) [reply Composer/packages/client/src/components/BotRuntimeController/BotController.tsx]: Done!

**Review by srinaath — APPROVED** [review]

**Review by hatpick — APPROVED** [review]

**Review by tdurnford — APPROVED** [review]
