### PR TITLE
fix: fix get history before file persistence

### LINKED ISSUE #3300: Create Publish Profile -> Error: undefined is not a valid publishing target type. There may be a missing plugin.
When creating a new publish profile it always throws this error
image

## Version
ffde16f0

### PR DESCRIPTION
**Pull request by VanyLaw**
## Description

Fix missing plugin issue when creating a new publish profile, and make url redirect to all profile when url error.

Cause: get publish history before settings file persisted to server.
Solution: Add filePersistence.flush after clicking the save button.

## Task Item

close #3300

### CODE REVIEW

File: Composer/packages/client/src/pages/publish/createPublishTarget.tsx [hunk 1]
```diff
@@ -83,6 +84,7 @@ const CreatePublishTarget: React.FC<CreatePublishTargetProps> = (props) => {
     if (targetType) {
       await props.updateSettings(name, targetType, JSON.stringify(config) || '{}');
       props.closeDialog();
+      await filePersistence.flush();
```
Comment (a-b-r-o-w-n) [inline Composer/packages/client/src/pages/publish/createPublishTarget.tsx:87]: I'm not sure I understand the bug that well, but is it possible to do this somewhere else instead of the component? The file persistence layer needs to remain an implementation detail to components. This violates that principle.

Comment (VanyLaw) [reply Composer/packages/client/src/pages/publish/createPublishTarget.tsx]: move it into getHistory action.
