### PR TITLE
fix: export display name and sort order for templates outside of Composer

### LINKED ISSUE #6787: Export display name and template order outside of Composer
Currently composer has a hardcoded sort order that dictates display name and sort order for templates in Composer. This needs to be exported out of Composer to allow for template updates decoupled from Composer releases.

Proposed solution:

- [ ] Export currently hardcoded `templateSortOrder` to be hosted on Github
- [ ] On app start pull template sort order and use that to dictate sort order and display name for templates in Composer

### PR DESCRIPTION
**Pull request by pavolum**
## Description

This PR adds a call to github to get the sort order and display name for templates to be rendered in Composer. If this call fails it defaults to the sort order shipped with the product. 

This feature will enable the template development team to change the order and/or display name of templates without needing to re release Composer. More importantly, it enables new templates to be created and displayed with the correct name and sort order within Composer outside of Composer releases. 

## Task Item

fixes #6787

### CODE REVIEW

**Comment by pavolum** [comment]
There is also a change in the PR to add Ben Brown and myself as code owners for the composer dir repo so we can approve PRs. I have gotten approval from Chris.

File: Composer/packages/server/src/utility/creation.ts [hunk 1]
```diff
@@ -4,21 +4,36 @@
...
+      'microsoft',
+      'BotFramework-Composer',
+      'main',
+      'templates.json'
+    );
+    const templateSortOrderObj = JSON.parse(templateSortOrder);
+    sortOrder =
+      templateSortOrderObj && templateSortOrderObj?.length > 0 ? templateSortOrderObj : backUpTemplateSortOrder;
+  } catch {
+    sortOrder = backUpTemplateSortOrder;
```
Comment (hatpick) [inline Composer/packages/server/src/utility/creation.ts:33]: no need

Comment (hatpick) [reply Composer/packages/server/src/utility/creation.ts:33]: instead log an error so we know something is wrong in either fetching or parsing that json

File: Composer/packages/server/src/utility/creation.ts [hunk 2]
```diff
@@ -4,21 +4,36 @@
...
   { generatorName: '@microsoft/generator-bot-enterprise-assistant', displayName: 'Enterprise assistant' },
   { generatorName: '@microsoft/generator-bot-people', displayName: 'People' },
   { generatorName: '@microsoft/generator-bot-calendar', displayName: 'Calendar' },
   { generatorName: QnABotTemplateId, displayName: 'QnAMaker bot' },
 ];
 
-export const sortTemplates = (templates: BotTemplate[]): BotTemplate[] => {
+export const sortTemplates = async (templates: BotTemplate[]): Promise<BotTemplate[]> => {
   let sortedTemplateList: BotTemplate[] = [];
+  let sortOrder = backUpTemplateSortOrder;
```
Comment (hatpick) [inline Composer/packages/server/src/utility/creation.ts:21]: I'd call this ```defaultWhatever```

File: Composer/packages/server/src/utility/creation.ts [hunk 3]
```diff
@@ -4,21 +4,36 @@
...
+  { generatorName: '@microsoft/generator-bot-conversational-core', displayName: 'Basic bot' },
   { generatorName: '@microsoft/generator-bot-assistant-core', displayName: 'Basic assistant' },
   { generatorName: '@microsoft/generator-bot-enterprise-assistant', displayName: 'Enterprise assistant' },
   { generatorName: '@microsoft/generator-bot-people', displayName: 'People' },
   { generatorName: '@microsoft/generator-bot-calendar', displayName: 'Calendar' },
   { generatorName: QnABotTemplateId, displayName: 'QnAMaker bot' },
 ];
 
-export const sortTemplates = (templates: BotTemplate[]): BotTemplate[] => {
+export const sortTemplates = async (templates: BotTemplate[]): Promise<BotTemplate[]> => {
```
Comment (hatpick) [inline Composer/packages/server/src/utility/creation.ts:19]: this is not sorting templates, it's fetching an array of data with a certain order.

File: .github/CODEOWNERS [hunk 4]
```diff
@@ -4,7 +4,7 @@
 
 /runtime/ @boydc2014 @luhan2017 @carlosscastro @benbrown
 
-/Composer/ @cwhitten @boydc2014 @a-b-r-o-w-n @beyackle @srinaath @tonyanziano @geoffcoxmsft @hatpick
+/Composer/ @cwhitten @boydc2014 @a-b-r-o-w-n @beyackle @srinaath @tonyanziano @geoffcoxmsft @hatpick @benbrown @pavolum
```
Comment (hatpick) [inline .github/CODEOWNERS:7]: can you have a dedicated PR for this? PRs are good because we can revert them if they cause an unwanted issue, this part of the PR has nothing to do with the rest of it.

File: Composer/packages/server/src/utility/creation.ts (hunk 1 above)
Comment (pavolum) [reply Composer/packages/server/src/utility/creation.ts:33]: Handled

File: Composer/packages/server/src/utility/creation.ts (hunk 2 above)
Comment (pavolum) [reply Composer/packages/server/src/utility/creation.ts:21]: Handled

File: Composer/packages/server/src/utility/creation.ts (hunk 3 above)
Comment (pavolum) [reply Composer/packages/server/src/utility/creation.ts:19]: Its passed an unsorted list of templates, uses the sort order which is fetched from its own external source, then uses that sort order to build and return a sorted list of templates.

File: .github/CODEOWNERS (hunk 4 above)
Comment (pavolum) [reply .github/CODEOWNERS:7]: Sure thing!

File: Composer/packages/server/src/utility/creation.ts (hunk 3 above)
Comment (hatpick) [reply Composer/packages/server/src/utility/creation.ts:20]: my bad, it was hiding the unchanged part. :)

**Review by hatpick — APPROVED** [review]

**Review by hatpick — APPROVED** [review]

**Review by hatpick — APPROVED** [review]

**Review by benbrown — APPROVED** [review]
