### PR TITLE
fix: disable telemetry calls in the provision dialog while we investigate …

### LINKED ISSUE #7250: telemetryClient is undefined in azurePublish extension.
## Describe the bug

telemetryClient is undefined in azurePublish extension.
image

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to Design page 
2. Click on `Share as a skill` from `...` 
image

3.  Click `Next` util `Create a publish profile to continue`
4. See error, and can not create a profile when clicking `Done` in the final step.
image

## Expected behavior

Do not show the error and can finish creation logic smooth.

### PR DESCRIPTION
**Pull request by benbrown**
## Description

For some reason, the telemetryclient is sometimes undefined inside the plugin.  This breaks the provision process right now.

## Task Item

Fixes #7250

### CODE REVIEW

**Review by pavolum — APPROVED** [review]

File: extensions/azurePublish/src/components/azureProvisionDialog.tsx [hunk 1]
```diff
@@ -284,6 +284,8 @@ export const AzureProvisionDialog: React.FC = () => {
   } = usePublishApi();
   const telemetryClient: TelemetryClient = useTelemetryClient();
 
+  console.log('TELEMETRY CLIENT', telemetryClient);
```
Comment (GeoffCoxMSFT) [inline extensions/azurePublish/src/components/azureProvisionDialog.tsx:287]: Do you want the console.log left in here?

**Review by GeoffCoxMSFT — APPROVED** [review]
