### PR TITLE
fix: polling logic & some ui bugfix for publish page

### LINKED ISSUE #5262: Publish page UI issues
Screen Shot 2020-12-09 at 10 38 26 AM
Screen Shot 2020-12-09 at 10 38 56 AM
Screen Shot 2020-12-09 at 10 37 41 AM
Screen Shot 2020-12-09 at 3 30 47 PM

### PR DESCRIPTION
**Pull request by alanlong9278**
### bugfix about publish page
- polling continue after completed
- notification card hidden after 5s
- ui bugfix: cancel column resizable & set min width for column.

### remain problem
there still are some columns missing when page width is smaller than detail list.
image

## Task Item

fix #5262 

## Screenshots
image

image

### CODE REVIEW

**Review by cwhitten — APPROVED** [review]

File: Composer/packages/client/src/pages/publish/Publish.tsx [hunk 1]
```diff
@@ -171,16 +174,24 @@ const Publish: React.FC<RouteComponentProps<{ projectId: string; targetName?: st
...
-  const [statusIntervals, setStatusIntervals] = useState<{ [key: string]: NodeJS.Timeout }[]>([]);
-  const getUpdatedStatus = (target, botProjectId): NodeJS.Timeout => {
+
+  const getUpdatedStatus = (target, botProjectId): void => {
     // TODO: this should use a backoff mechanism to not overload the server with requests
     // OR BETTER YET, use a websocket events system to receive updates... (SOON!)
+    if (intervals[`${botProjectId}-${target.name}`]) return;
     getPublishStatus(botProjectId, target);
-    return setInterval(async () => {
+    intervals[`${botProjectId}-${target.name}`] = window.setInterval(async () => {
```
Comment (srinaath) [inline Composer/packages/client/src/pages/publish/Publish.tsx:183]: Use the useInterval hook  in hooks.ts @alanlong9278.
