### PR TITLE
fix: composer proxy support

### LINKED ISSUE #2654: Proxy support
## Describe the bug
I can't see any icons nor edit any values within the Electron version of composer. I assume this has something to do with our proxy, but I havn't found any setttings to configure a proxy for the Electron app

## Version
aca7358
Application SHA  test
SDK runtime packages  4.7.0-preview-191208-1

## Browser
- [ ] Chrome
- [ ] Safari
- [x] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Start Electron app

## Expected behavior

I should be able to edit the different fields and values

## Screenshots

grafik

### PR DESCRIPTION
**Pull request by lei9444**
## Description
1. composer server and extension proxy support

     - make axios and node-fetch to support proxy (fixed)

2. dependencies proxy support

     - bf-lu (fixed)

     - bf-dialog (fixed)

     - bf-orchestrator (fixed)

## Task Item
closes #2654

### CODE REVIEW

File: Composer/packages/server/src/models/bot/feedManager.ts [hunk 1]
```diff
@@ -1,6 +1,6 @@
 // Copyright (c) Microsoft Corporation.
 // Licensed under the MIT License.
-import axios from 'axios';
+import axios from '../../utility/httpClient';
```
Comment (a-b-r-o-w-n) [inline Composer/packages/server/src/models/bot/feedManager.ts:3]: Can this be converted to use fetch instead?

**Review by boydc2014 — APPROVED** [review]

**Review by boydc2014 — APPROVED** [review]
