### PR TITLE
fix: lg tablelist bugfix & regressions

### LINKED ISSUE #3867: Action on "new template" in LG all up will complain error
- Go to LG all up view
- under "All"  tab, click "new template" button
- click 3 dot to delete the template
- errors display 
image

### PR DESCRIPTION
**Pull request by zhixzhan**
## Description

Fix some regression on lg part, and do some refinement, add more unit test.

## Task Item

close #3867

### CODE REVIEW

File: Composer/packages/client/src/recoilModel/dispatchers/lu.ts [hunk 1]
```diff
@@ -174,12 +174,7 @@ export const luDispatcher = () => {
 
           // body change, only update current locale file
         } else {
-          const intentToUpdate: any = { Body: intent.Body };
-          // if current update intent not found in origin luFile, do create.
-          if (!luFile.intents.find((item) => item.Name === intentName)) {
```
Comment (zhixzhan) [inline Composer/packages/client/src/recoilModel/dispatchers/lu.ts:179]: moved this logic to luUtil
