### PR TITLE
chore: fix hover state nodes ui

### LINKED ISSUE #1904: Hoover State on Nodes
Noticed this on a few of the nodes.

ChoiceInput and User Answers - could be more. The Shapes of the nodes and the Hoover outlines
should all have a 2px radius on the top corners.

Another simple one, but it looks a little bit sloppy. Thank you!

## Browser Chrome
What browser are you using?

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS MacOS 10.15.2

Screen Shot 2020-01-27 at 10 26 15 AM

### PR DESCRIPTION
**Pull request by alanlong9278**
## Description

fix hover state nodes ui

image

## Task Item
closes #1904

### CODE REVIEW

File: Composer/packages/extensions/visual-designer/src/components/renderers/ElementWrapper.tsx [hunk 1]
```diff
@@ -21,7 +21,7 @@ const nodeBorderSelectedStyle = css`
 
 // BotAsks, UserAnswers and InvalidPromptBrick nodes selected style
 const nodeBorderDoubleSelectedStyle = css`
-  outline: 2px solid #0078d4;
+  border: 2px solid #0078d4;
```
Comment (yeze322) [inline Composer/packages/extensions/visual-designer/src/components/renderers/ElementWrapper.tsx]: The problem is not entirely fixed. We used `outline` here because of we didn't want to infect the box size.
If you keep clicking between two nodes, you will find the element floating problem.

Comment (yeze322) [reply Composer/packages/extensions/visual-designer/src/components/renderers/ElementWrapper.tsx]: Reference this demo: http://jsfiddle.net/f8q6axgg/
image

It should be helpful.

Comment (alanlong9278) [reply Composer/packages/extensions/visual-designer/src/components/renderers/ElementWrapper.tsx]: Thanks, It's fixed with `box-shadow`
