### PR TITLE
fix: #2692 Tabbing / clicking / returning out of a number field round your input

### LINKED ISSUE #2692: Tabbing / clicking / returning out of a number field round your input
1. in Set properties action node, you are adding a property
2. Set the type of a value to number, and type any number, say 0.4
3. Tab, return, or clicking out of that field round 0.4 to 0. 

The same behavior occurs in Switch node as well. You have to use the spin button to set a number value.

### PR DESCRIPTION
**Pull request by LouisEugeneMSFT**
## Description

The field (Composer/packages/extensions/adaptive-form/src/components/fields/NumberField.tsx) was always rounding numbers to be integers since _onValidate_ calls _updateValue(0)_.
In the case of floats, _updateValue(0)_ would call _getFloat(value, 0)_, which would call _.toFixed(0)_.

This is because the _**step**_ variable was used in different places for different purposes. In the case of _getFloat_ it was used both for incrementing **and** rounding, which is incorrect.

The PR therefore makes the rounding "amount" a separate variable (floatNumberOfDecimals).

## Task Item

fixes #2692

## Screenshots

image

### CODE REVIEW

File: Composer/packages/extensions/adaptive-form/src/components/fields/NumberField.tsx [hunk 1]
```diff
@@ -1,18 +1,19 @@
...
 
+const floatNumberOfDecimals = 1;
+
 const getInt = (value: string, step: number) => {
   return parseInt(value, 10) + step;
 };
 
 const getFloat = (value: string, step: number) => {
-  const fixed = (parseFloat(value) + step).toFixed(step !== 0 ? `${step}`.split('.')[1].length : step);
+  const fixed = (parseFloat(value) + step).toFixed(floatNumberOfDecimals);
```
Comment (GeoffCox) [inline Composer/packages/extensions/adaptive-form/src/components/fields/NumberField.tsx:16]: The issue was that numbers were being rounded to an integer, should we not round at all?

File: Composer/packages/extensions/adaptive-form/src/components/fields/NumberField.tsx [hunk 2]
```diff
@@ -1,18 +1,19 @@
...
 
   return parseFloat(fixed);
```
Comment (GeoffCox) [inline Composer/packages/extensions/adaptive-form/src/components/fields/NumberField.tsx:18]: Why parse the float to turn it into a float, then back to a string to round it, then back to a float.  How about .round if we are rounding the float?

File: Composer/packages/extensions/adaptive-form/src/components/fields/NumberField.tsx [hunk 3]
```diff
@@ -36,7 +37,7 @@ const NumberField: React.FC<FieldProps> = (props) => {
     onChange(newValue);
   };
 
-  const step = type === 'integer' ? 1 : 0.1;
+  const step = type === 'integer' ? 1 : 1 / Math.pow(10, floatNumberOfDecimals);
```
Comment (beyackle) [inline Composer/packages/extensions/adaptive-form/src/components/fields/NumberField.tsx:40]: This could just be `Math.pow(10, -floatNumberOfDecimals)`.

File: Composer/packages/extensions/adaptive-form/src/components/fields/NumberField.tsx [hunk 4]
```diff
@@ -1,18 +1,19 @@
...
-import React from 'react';
-import { SpinButton } from 'office-ui-fabric-react/lib/SpinButton';
 import { FieldProps } from '@bfc/extension';
 import formatMessage from 'format-message';
-
+import { SpinButton } from 'office-ui-fabric-react/lib/SpinButton';
+import React from 'react';
 import { FieldLabel } from '../FieldLabel';
 
+const floatNumberOfDecimals = 1;
```
Comment (beyackle) [inline Composer/packages/extensions/adaptive-form/src/components/fields/NumberField.tsx:9]: Is there a reason we're fixing this at 1? I feel like users might have different use cases where they might need other numbers of decimals (e.g. if they're implementing a "currency" field and need 2, or if they need even more precision).

File: Composer/packages/extensions/adaptive-form/src/components/fields/NumberField.tsx (hunk 3 above)
Comment (LouisEugeneMSFT) [reply Composer/packages/extensions/adaptive-form/src/components/fields/NumberField.tsx:40]: Good point!

File: Composer/packages/extensions/adaptive-form/src/components/fields/NumberField.tsx (hunk 4 above)
Comment (LouisEugeneMSFT) [reply Composer/packages/extensions/adaptive-form/src/components/fields/NumberField.tsx:9]: Agreed. It was set up to a precision of 1 so I didn't want to break anything since I am still new to the codebase. How do we make that decision? If we don't have clear guidance then I agree 2 is a better default.

**Comment by cwhitten** [comment]
@vishwacsena @tomlm can you comment to the introduction of `multipleOf` to specify precision on a number type? See "Validations" on https://cswr.github.io/JsonSchema/spec/basic_types/

**Comment by luhan2017** [comment]
@cwhitten , It seems I have some misunderstanding here, I was trying to say that
For the NumberInput, we can use the outputFormat(=formatNumber(this.value, 2)) property to define the precision of the number type. 
Here is an example:
image
image

This means user can set precision of the output by formatNumber expression in LG. 
This seems not relate to what you want. 
I don't quite understand what is the `multipleOf` used for. Do you mean to define the precision of a number variable in the component schema?

**Comment by cwhitten** [comment]
@luhan2017 @LouisEugeneMSFT let's take this and continue discussion to determine if we want to allow the the number type to include a precision option, so that you don't need to format using lg.
