### PR TITLE
fix: Orchestrator Download Notification

### LINKED ISSUE #5615: Add configuration settings to select / download a non-default Orchestrator model.
The Orchestrator feature will use the default basemodel. This is to track the request to allow selection of alternate model via settings, likely in package configuration.

### PR DESCRIPTION
**Pull request by taicchoumsft**
## Description
Add a notification when Orchestrator is downloading models.   

This is also the start of the work to move Orchestrator model downloading to outside of the publishing pipeline.   It will be possible to trigger the download of the models anytime with the use of the `downloadModel` dispatcher.

## Task
fixes #5615

### CODE REVIEW

File: Composer/packages/client/src/components/Orchestrator/DownloadNotification.tsx [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+`;
+
+const cardDetail = css`
+  margin-left: 8px;
+  flex-grow: 1;
+`;
+
+const infoType = css`
+  margin-top: 4px;
+  color: #0078d4;
```
Comment (lei9444) [inline Composer/packages/client/src/components/Orchestrator/DownloadNotification.tsx:26]: We can use a color from Fluent, I think this color is SharedColors.CyanBlue10

**Comment by lei9444** [comment]
Tested and LGTM

File: Composer/packages/client/src/components/Orchestrator/DownloadNotification.tsx (hunk 1 above)
Comment (taicchoumsft) [reply Composer/packages/client/src/components/Orchestrator/DownloadNotification.tsx]: Thanks @lei9444 , resolved.

**Review by boydc2014 — APPROVED** [review]
