### PR TITLE
fix: call shared deletebot modal from toolbar

### LINKED ISSUE #6131: Link for Delete Bot in Action Menu does not initiate the modal
## Describe the bug

Currently, the link for Delete Bot in the Action Menu in Bot Settings does not launch the delete modal. 

## Version

image

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to Bot Settings
2. Click on Delete Bot in the Action Bar
3. Needs to launch modal for delete, not scroll to the delete button below

## Expected behavior

Clicking on the delete bot button should launch this modal
image

## Additional context

The design of the modal for delete should be updated to proper design as well.

### PR DESCRIPTION
**Pull request by benbrown**
## Description

Open a revised Delete Bot modal from the toolbar directly instead of scrolling to the delete bot section of the settings page.

## Task Item

fixes #6131 

## Screenshots

new modal:
Screen Shot 2021-03-10 at 4 36 59 PM

behavior in place:
4Sk4l7C8LQ

### CODE REVIEW

File: Composer/packages/client/src/pages/botProject/DeleteBotButton.tsx [hunk 1]
```diff
@@ -41,78 +41,34 @@ type DeleteBotButtonProps = {
   scrollToSectionId: string;
 };
 
+export const openDeleteBotModal = async (onConfirm: () => Promise<void>) => {
+  const warningText = formatMessage(
+    'Are you sure you want to delete your bot? This action cannot be undone and your ot and all relsated files in the bot project folder will be permanently deleted. Your Azure resources will remain unchanged.'
```
Comment (a-b-r-o-w-n) [inline Composer/packages/client/src/pages/botProject/DeleteBotButton.tsx:46]:
```suggestion
    'Are you sure you want to delete your bot? This action cannot be undone and your bot and all related files in the bot project folder will be permanently deleted. Your Azure resources will remain unchanged.'
```

**Review by a-b-r-o-w-n — APPROVED** [review]

**Review by a-b-r-o-w-n — APPROVED** [review]

**Comment by a-b-r-o-w-n** [comment]
@benbrown there are some type checks that fail currently.

**Review by hatpick — APPROVED** [review]
