### PR TITLE
fix: Create bot from scratch may create a non-empty bot

### LINKED ISSUE #1814: create a new bot
## Describe the bug
1. create a echoBot(will set global state templateId = echoBot)
2. create a new bot from scratch (should create a new empty bot but create a echoBot)

### PR DESCRIPTION
**Pull request by liweitian**
## Description
when the state templateId is set. Create a bot from scratch will use that templateId. But it should be emptyBot.

## Task Item

Closes #1814 
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have functionally tested my change

## Screenshots

Please include screenshots or gifs if your PR include UX changes.

### CODE REVIEW

File: Composer/packages/client/src/CreationFlow/CreateOptions/index.js [hunk 1]
```diff
@@ -72,10 +72,10 @@ export function CreateOptions(props) {
 
   const handleJumpToNext = () => {
     if (option === 'Create from template') {
-      if (template === null) onNext(templates[0]);
+      if (template === null) onNext(templates[1].key);
```
Comment (boydc2014) [inline Composer/packages/client/src/CreationFlow/CreateOptions/index.js]: let's make it clear by not using a magic number. 

probably explicitly say `emptyBotId = templates[1].key`

Comment (boydc2014) [reply Composer/packages/client/src/CreationFlow/CreateOptions/index.js]: And please investigate, when this template is null, why not we default having a choice set for user.
