### PR TITLE
fix: enable users to select any non multi bot template during add new skills flow

### LINKED ISSUE #7490: Add template selection in add skills flow
Need to allow users to select any non multi bot template in add new skills flow, new spec below 
https://www.figma.com/file/4kfahZUjBdrxdDGZih7PVP/Composer-1.5-E2E-flows?node-id=862%3A53941

Multibot templates will have the following tag `msbot-multibot-project`

### PR DESCRIPTION
**Pull request by pavolum**
## Description

This PR changes the add skills flow in a few ways:
- initial add skills modal no longer has 'add empty bot' and now has 'add new bot' 
- add skills modal has 'add new bot' as deafult selected
- if 'add new bot' is selected the user is routed to the template selection screen where they can select any template that is not marked as a multi bot template
  - multbot template detection added by parsing for the `msbot-multibot-project` keyword in the template generator npm package 

## Task Item

fixed #7490 

## Screenshots

image

image

image
**NOTE: new RCs that add the keyword for multi bot for enterprise assistant are not published yet, when they are published I have validated the existing logic will detect that tag and remove multi bot projs accordingly from this add skills template selection view**
image

### CODE REVIEW

File: Composer/packages/client/src/components/CreationFlow/v2/CreateBot.tsx [hunk 1]
```diff
@@ -199,17 +199,22 @@ export function CreateBotV2(props: CreateBotProps) {
...
     } else if (itemKey === nodeFeedKey) {
-      const newTemplates = templates.filter((template) => {
+      newTemplates = templates.filter((template) => {
         return template.nodeSupport;
       });
-      setDisplayedTemplates(newTemplates);
     }
+    if (creationFlowType === 'Skill') {
+      newTemplates = newTemplates.filter((template) => {
+        return !template.isMultiBotTemplate;
```
Comment (benbrown) [inline Composer/packages/client/src/components/CreationFlow/v2/CreateBot.tsx:214]: why don't you just check template.keywords.includes here?

File: Composer/packages/client/src/components/CreationFlow/v2/AddBotModal.tsx [hunk 2]
```diff
@@ -16,17 +16,17 @@ interface AddBotModalProps {
...
 
-const addExistingKey = 'existing';
-const addBlankKey = 'blank';
+const addExistingBotKey = 'existing';
+const addNewBotKey = 'new';
 
 const addSkillOptions: IChoiceGroupOption[] = [
-  { key: addExistingKey, text: 'Add an existing bot' },
-  { key: addBlankKey, text: 'Create a new blank bot' },
+  { key: addNewBotKey, text: 'Create a new bot' },
```
Comment (hatpick) [inline Composer/packages/client/src/components/CreationFlow/v2/AddBotModal.tsx:23]: these were missing formatMessage originally, can you add them?

File: Composer/packages/server/src/models/asset/assetManager.ts [hunk 3]
```diff
@@ -294,6 +294,7 @@ export class AssetManager {
                 webAppSupported: keywords.includes('bf-js-webapp'),
               };
             }
+            templateToReturn.isMultiBotTemplate = keywords.includes('msbot-multibot-project') ? true : false;
```
Comment (benbrown) [inline Composer/packages/server/src/models/asset/assetManager.ts:297]: do the test during the filter instead of adding fields

File: Composer/packages/types/src/runtime.ts [hunk 4]
```diff
@@ -36,6 +36,7 @@ export type BotTemplate = {
   id: string;
   name: string;
   description: string;
+  isMultiBotTemplate?: boolean;
```
Comment (benbrown) [inline Composer/packages/types/src/runtime.ts:39]: see abpve

**Review by benbrown — CHANGES_REQUESTED** [review]

File: Composer/packages/server/src/models/asset/assetManager.ts (hunk 3 above)
Comment (hatpick) [inline Composer/packages/server/src/models/asset/assetManager.ts:297]: templateToReturn.isMultiBotTemplate = keywords.includes('msbot-multibot-project')

File: Composer/packages/client/src/components/CreationFlow/v2/AddBotModal.tsx [hunk 5]
```diff
@@ -50,7 +50,7 @@ export const AddBotModal: React.FC<AddBotModalProps> = (props) => {
       title={formatMessage('Add a bot')}
       onDismiss={props.onDismiss}
     >
-      <ChoiceGroup required defaultSelectedKey={addExistingKey} options={addSkillOptions} onChange={handleChange} />
+      <ChoiceGroup required defaultSelectedKey={addNewBotKey} options={addSkillOptions} onChange={handleChange} />
```
Comment (beyackle) [inline Composer/packages/client/src/components/CreationFlow/v2/AddBotModal.tsx:53]: Is there a reason we're changing this default?

File: Composer/packages/client/src/components/CreationFlow/v2/CreateBot.tsx [hunk 6]
```diff
@@ -199,17 +199,22 @@ export function CreateBotV2(props: CreateBotProps) {
...
       });
-      setDisplayedTemplates(newTemplates);
     } else if (itemKey === nodeFeedKey) {
-      const newTemplates = templates.filter((template) => {
+      newTemplates = templates.filter((template) => {
         return template.nodeSupport;
       });
-      setDisplayedTemplates(newTemplates);
     }
+    if (creationFlowType === 'Skill') {
```
Comment (beyackle) [inline Composer/packages/client/src/components/CreationFlow/v2/CreateBot.tsx:212]: `else if`?

File: Composer/packages/client/src/components/CreationFlow/v2/CreateBot.tsx [hunk 7]
```diff
@@ -199,17 +199,22 @@ export function CreateBotV2(props: CreateBotProps) {
...
+      newTemplates = newTemplates.filter((template) => {
+        return !template.isMultiBotTemplate;
+      });
+    }
+    setDisplayedTemplates(newTemplates);
```
Comment (beyackle) [inline Composer/packages/client/src/components/CreationFlow/v2/CreateBot.tsx:217]: Is it possible to get down here without any of those three alternatives being true? That would cause `newTemplates` to stay blank, and I don't know if that's a problem or not.

**Review by beyackle — DISMISSED** [review]
Just some minor questions.

File: Composer/packages/client/src/components/CreationFlow/v2/CreateBot.tsx (hunk 1 above)
Comment (pavolum) [reply Composer/packages/client/src/components/CreationFlow/v2/CreateBot.tsx:214]: As it is now keywords are not passed to the front end template object, they are parsed on the server side and the server sets values like template.isMultiBotTemplate or template.dotnetSupport

Comment (pavolum) [reply Composer/packages/client/src/components/CreationFlow/v2/CreateBot.tsx:214]: Like template.keywords doesnt exist

File: Composer/packages/client/src/components/CreationFlow/v2/AddBotModal.tsx (hunk 2 above)
Comment (pavolum) [reply Composer/packages/client/src/components/CreationFlow/v2/AddBotModal.tsx:23]: handled and made it a function

File: Composer/packages/server/src/models/asset/assetManager.ts (hunk 3 above)
Comment (pavolum) [reply Composer/packages/server/src/models/asset/assetManager.ts:297]: Uhh how embarrassing :D

File: Composer/packages/client/src/components/CreationFlow/v2/AddBotModal.tsx (hunk 5 above)
Comment (pavolum) [reply Composer/packages/client/src/components/CreationFlow/v2/AddBotModal.tsx:53]: Yep, Capn' Scott and design requested it

File: Composer/packages/client/src/components/CreationFlow/v2/CreateBot.tsx (hunk 6 above)
Comment (pavolum) [reply Composer/packages/client/src/components/CreationFlow/v2/CreateBot.tsx:212]: Nah, this is intentional you can be in a skill AND be in csharp template feed feed OR node template feed

File: Composer/packages/client/src/components/CreationFlow/v2/CreateBot.tsx (hunk 7 above)
Comment (pavolum) [reply Composer/packages/client/src/components/CreationFlow/v2/CreateBot.tsx:217]: Not possible, `ItemKey` aka `selectedProgLang.props.itemKey` always has a value so one of the first two conditionals is always hit

**Review by benbrown — APPROVED** [review]
