### PR TITLE
fix: UI fixes in getting started rocket panel 

### LINKED ISSUE #6993: Tighten up rocket panel UI
Just a few small updates for the rocket baby. Let me know before submitting to double check spacing/etc.

Figma: https://www.figma.com/file/tvENftrexoAYJngzsJxUbv/EmFig?node-id=3547%3A0 

image

### LINKED ISSUE #7424: default names when you create from template need correction
They should match the following default names
Friendly Name
Generator name
default bot name

Empty Bot
@microsoft/generator-bot-empty
Empty

Core Bot with Language
@microsoft/generator-bot-core-language
CoreWithLanguage

Core Bot with QnA Maker
@microsoft/generator-bot-core-qna
CoreWithQNA

Core Assistant Bot
@microsoft/generator-bot-core-assistant
CoreAssistant

Enterprise Assistant Bot
@microsoft/generator-bot-enterprise-assistant
EnterpriseAssistant

Enterprise Calendar Bot
@microsoft/generator-bot-enterprise-calendar
EnterpriseCalendar

Enterprise People Bot
@microsoft/generator-bot-enterprise-people
EnterprisePeople

### PR DESCRIPTION
**Pull request by pavolum**
## Description

Various css fixes to meet the design changes requested in the below issue

## Task Item

fixes #6993 
fixes #7424

## Screenshots

image

### CODE REVIEW

**Review by tdurnford — APPROVED** [review]

**Review by tdurnford — APPROVED** [review]

**Comment by pavolum** [comment]
@emivers8 is working on getting 'learn more' links for each item in the rocket pane, waiting on those prior to merging, if we do not get those in the next few hours we will merge without them as this needs to get in today per Scotts request

File: Composer/packages/client/src/components/GetStarted/GetStartedTask.tsx [hunk 1]
```diff
@@ -46,7 +46,7 @@ export const GetStartedTask: React.FC<TaskProps> = (props) => {
       >
         {props.step.label}
       </ActionButton>
-      <div css={{ marginLeft: 36, fontSize: 12, color: NeutralColors.gray120 }}>
+      <div css={{ marginLeft: 36, fontSize: 12, color: NeutralColors.gray120, marginTop: '-4px' }}>
```
Comment (tdurnford) [inline Composer/packages/client/src/components/GetStarted/GetStartedTask.tsx:49]: We should pull these styles out into a variable and use `css` or `styled.div()`.

Comment (pavolum) [reply Composer/packages/client/src/components/GetStarted/GetStartedTask.tsx:49]: Handled

File: Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx [hunk 2]
```diff
@@ -126,7 +127,10 @@ const DefineConversationV2: React.FC<DefineConversationProps> = (props) => {
   const normalizeTemplateId = () => {
     if (currentTemplate) {
       // use almost the same patterns as in assetManager.ts
-      return currentTemplate.name.trim().replace(/[-\s]/g, '_').toLocaleLowerCase();
+      const camelCasedName = camelCase(
+        currentTemplate.name.trim().toLocaleLowerCase().replace('bot', '').replace('maker', '').replace(/-/g, ' ')
+      );
+      return camelCasedName.charAt(0).toUpperCase() + camelCasedName.slice(1);
```
Comment (tdurnford) [inline Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx:133]:
```suggestion
      import upperFirst from 'lodash/upperFirst';
      return upperFirst(camelCasedName);
```

File: Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx [hunk 3]
```diff
@@ -126,7 +127,10 @@ const DefineConversationV2: React.FC<DefineConversationProps> = (props) => {
   const normalizeTemplateId = () => {
     if (currentTemplate) {
       // use almost the same patterns as in assetManager.ts
-      return currentTemplate.name.trim().replace(/[-\s]/g, '_').toLocaleLowerCase();
+      const camelCasedName = camelCase(
+        currentTemplate.name.trim().toLocaleLowerCase().replace('bot', '').replace('maker', '').replace(/-/g, ' ')
```
Comment (tdurnford) [inline Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx:131]: Does it make more sense to use case insensitive regex in the replace calls instead of making the name lower case? Might be able to combine the regex for 'bot' and 'maker' too since they're both  
```suggestion
        currentTemplate.name.trim().replaceAll(/bot|maker/gi, '').replace(/-/g, ' ')
```

File: Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx (hunk 2 above)
Comment (pavolum) [reply Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx:133]: Nice catch, I have made the change

File: Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx (hunk 3 above)
Comment (pavolum) [reply Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx:131]: Yeah thats a bit cleaner, I have made the change

File: Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx [hunk 4]
```diff
@@ -126,7 +128,13 @@ const DefineConversationV2: React.FC<DefineConversationProps> = (props) => {
   const normalizeTemplateId = () => {
     if (currentTemplate) {
       // use almost the same patterns as in assetManager.ts
-      return currentTemplate.name.trim().replace(/[-\s]/g, '_').toLocaleLowerCase();
+      const camelCasedName = camelCase(
+        currentTemplate.name
+          .trim()
+          .replace(/bot|maker/gi, '')
```
Comment (tdurnford) [inline Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx:134]: Should this be `replaceAll` instead of `replace`. I think if `currentTemplate.name = 'botMaker'` the result would be `'maker`' instead of an empty string.

**Review by tdurnford — APPROVED** [review]

File: Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx (hunk 4 above)
Comment (pavolum) [reply Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx:134]: Spoke about this offline and resolved te issue
