### PR TITLE
fix: add trigger to the root dialog when adding a new skill

### LINKED ISSUE #7448: When adding a Skill to a project, if you have a dialog selected it adds it to the dialog not the root bot
## Describe the bug

If you have a Bot with a dialog and have this dialog active when adding a Skill, the Skill trigger is incorrectly added to the dialog not the root Bot which is where Orchestrator is configured.

image

## Version

2.0.0-nightly.240366

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new bot
2. Create a new dialog
3. Make this new dialog active
3. Add a skill  - e.g: https://djtest6.azurewebsites.net/manifests/djbfskill1-2-1-manifest.json

## Expected behavior

- Skill trigger added to root bot

### PR DESCRIPTION
**Pull request by lei9444**
## Description

**in the PR**
if the root dialog is orchestrator recognizer type or user chooses orchestrator type before connecting the skill, add the trigger to the root dialog.

## Task Item
closes #7448

## Screenshots
trigger

### CODE REVIEW

**Review by srinaath — APPROVED** [review]

**Comment by srinaath** [comment]
Looks good and compact @lei9444. A unit test to make sure this scenario doesn't break would be great. Lets wait for feedback on the ticket though before we merge it.

File: Composer/packages/client/src/components/AddRemoteSkillModal/CreateSkillModal.tsx [hunk 1]
```diff
@@ -196,16 +198,22 @@ export const CreateSkillModal: React.FC<CreateSkillModalProps> = (props) => {
     TelemetryClient.track('AddNewSkillCompleted');
     // if added remote skill fail, just not addTrigger to root.
     const skillId = location.href.match(/skill\/([^/]*)/)?.[1];
+
+    //if the root dialog is orchestrator recoginzer type or user chooses orchestrator type before connecting,
```
Comment (luhan2017) [inline Composer/packages/client/src/components/AddRemoteSkillModal/CreateSkillModal.tsx:202]: Adding to the root dialog should not depending on the recognizer type. No matter it is luis, orchestrator, regex, we should add the trigger to the root dialog, right?
