### PR TITLE
fix: handle invalid lg parsing on initial page mount

### LINKED ISSUE #1539: LG invalid syntax cause page crash
Complete the necessary portions of this template and delete the rest.

## Describe the bug

load common.lg with error in head, page will crash on lg all up view.

```
hahah
#Hello 
-hi
```

## Version
What version of the Composer are you using? Paste the build SHA found on the about page (`/about`).

## Browser
What browser are you using?

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Screenshots
Screen Shot 2019-11-08 at 8 29 56 PM

### PR DESCRIPTION
**Pull request by zhixzhan**
## Task Item

fix #1539

### CODE REVIEW

File: Composer/packages/client/src/pages/language-generation/table-view.js [hunk 1]
```diff
@@ -31,13 +31,18 @@ export default function TableView(props) {
...
+    try {
+      allTemplates = lgUtil.parse(lgFile.content).map((template, templateIndex) => {
+        return {
+          ...template,
+          index: templateIndex,
+        };
+      });
+      // mute lg file invalid cause page crash, setState is async, this component may render at first
+    } catch (error) {
+      console.error(error);
```
Comment (boydc2014) [inline Composer/packages/client/src/pages/language-generation/table-view.js]: When LG parser failed to parse a file, the error message should contains the diagnostics information to tell us what's wrong, we should direct user to edit mode (in which Manaco will also give out the sample message) to fix that, right?

Comment (zhixzhan) [reply Composer/packages/client/src/pages/language-generation/table-view.js]: if parsing failed, error is handled by upon component, which will navigate to edit mode, and show error directly in monaco editor.
Here try parse is a trick for `setEditMode`, react state set not synchronize change, this `table-view` component may mounted at first time.
