### PR TITLE
fix: set BeginSkill initial value allowInterruptions: 'false',

### LINKED ISSUE #8412: set default allowInterruptions=false in BeginSkill action
## Describe the bug

set default allowInterruptions=false in BeginSkill action 

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

### PR DESCRIPTION
**Pull request by zhixzhan**
## Task Item
fixes #8412

## Screenshots
image

### CODE REVIEW

**Review by luhan2017 — DISMISSED** [review]

**Review by boydc2014 — APPROVED** [review]

File: Composer/packages/lib/shared/src/dialogFactory.ts [hunk 1]
```diff
@@ -90,6 +90,12 @@ const initialDialogShape = () => ({
   [SDKKinds.SendActivity]: {
     activity: '',
   },
+  [SDKKinds.BeginSkill]: {
+    botId: '=settings.MicrosoftAppId',
+    skillHostEndpoint: '=settings.skillHostEndpoint',
+    connectionName: '=settings.connectionName',
+    allowInterruptions: 'false',
```
Comment (srinaath) [inline Composer/packages/lib/shared/src/dialogFactory.ts:97]: This should be a boolean false and not stringified false. @zhixzhan  is there a reason you made it a string?

**Review by srinaath — CHANGES_REQUESTED** [review]

File: Composer/packages/lib/shared/src/dialogFactory.ts (hunk 1 above)
Comment (zhixzhan) [reply Composer/packages/lib/shared/src/dialogFactory.ts]: @srinaath Thanks. it should be boolean.

**Review by boydc2014 — APPROVED** [review]
