### PR TITLE
fix: scroll to settings page component

### LINKED ISSUE #4974: Publish targets in Publish Page
Screen Shot 2020-11-24 at 4 43 21 PM
When "Manage Profiles" is clicked it needs to route to the appropriate settings page and scroll to the publish target section in Settings page. Currently, we just guide them to the settings page. It is hard for the user to know where to add the publishing profile.

### PR DESCRIPTION
**Pull request by liweitian**
## Description
luis or qna key missing error will navigate to settings page and scroll to related fields
Manager Profiles button in publish page will navigate to settings page and scroll to related fields

## Task Item
Closes #4974
## Screenshots
scroll

### CODE REVIEW

File: Composer/packages/client/src/pages/botProject/PublishTargets.tsx [hunk 1]
```diff
@@ -191,10 +194,16 @@ export const PublishTargets: React.FC<PublishTargetsProps> = (props) => {
     }
   }, [projectId]);
 
+  useEffect(() => {
+    if (publishTargetsRef.current && hash === '#addNewPublishProfile') {
+      publishTargetsRef.current.scrollIntoView({ behavior: 'smooth' });
+    }
+  });
```
Comment (hatpick) [inline Composer/packages/client/src/pages/botProject/PublishTargets.tsx:201]: hash dependency

File: Composer/packages/client/src/pages/botProject/PublishTargets.tsx [hunk 2]
```diff
@@ -117,6 +118,8 @@ export const PublishTargets: React.FC<PublishTargetsProps> = (props) => {
   const [addDialogHidden, setAddDialogHidden] = useState(true);
   const [editDialogHidden, setEditDialogHidden] = useState(true);
 
+  const publishTargetsRef = React.useRef<HTMLInputElement>(null);
```
Comment (hatpick) [inline Composer/packages/client/src/pages/botProject/PublishTargets.tsx:121]: did you mean HTMLDivElement?

**Review by hatpick — CHANGES_REQUESTED** [review]
nit: I'd name "hash" something that is conceptually closer to what it's being used for, for example: scrollToSectionId

**Review by hatpick — APPROVED** [review]
