### PR TITLE
a11y: add linkBtn to tab-order

### LINKED ISSUE #2062: [Accessibility][Keyboard - Actions]: 'Action' Button available under the node is not accessible by keyboard.
**User Experience:**
Keyboard dependent users will not be able to use the functionality of the control if the any control is not accessible via keyboard.

**Test Environment**
Browser: Microsoft Edge Canary Version: 82.0.425.0 (Official build)
OS build: 2004 (19564.1005)
Screen Reader: Narrator
URL: [Bot Framework Composer](http://localhost:3000/dialogs/Main)
[**Prerequisite Here**](https://github.com/microsoft/BotFramework-Composer)

**Repro Steps:** 
1. Open the above mentioned URL in EDGE
2. "Bot Framework Composer" homepage will gets opened.
3. Select "Dialog Actions" from the available Bots under 'Examples' and activate it.
4. Navigate the dialog 'Define conversation objective' then press 'Next'.
5. Navigate to already created dialog tree item and activate it. Such as- Greetings, Actions, EndDialog etc.
6. Now, the tree structure appears in the centre. Navigate to already created node.
7. Activate the 'Actions' button available below the name of the node.
8. Observe the issue.

**Actual:** 
"Action" button is not accessible by keyboard. On using mouse, the control are interactive as action is getting performed but its not accessible with keyboard.

**Note:**
Same issue observed with other button's which are present in the node similar to action button's such button's are in "Replacedialog" pane.

**Expected:**
The controls which are accessible with mouse must be accessible with keyboard. So, 'Action' button must be accessible with keyboard.

**MAS Impacted:** [MAS2.1.1](https://microsoft.sharepoint.com/:w:/r/sites/accessibility/_layouts/15/Doc.aspx?sourcedoc=%7B1F29ACF9-A3E7-414F-BD8D-7E3598D877BB%7D&file=MAS%202.1.1%20%E2%80%93%20Keyboard.docx&action=default&mobileredirect=true)

**Attachment:**
[MAS2.1.1_Action is not accesible with keyboard.zip](https://github.com/microsoft/BotFramework-Composer/files/4241323/MAS2.1.1_Action.is.not.accesible.with.keyboard.zip)

### PR DESCRIPTION
**Pull request by alanlong9278**
## Description

Add dialog's linkBtn to tab-order in visual editor. 

## Task Item
fix #2062

## Screenshots

tabcheck

### CODE REVIEW

File: Composer/packages/extensions/visual-designer/src/widgets/DialogRef.tsx [hunk 1]
```diff
@@ -6,22 +6,43 @@ import { jsx } from '@emotion/core';
...
+  const declareElementAttributes = (id: string) => {
+    return {
+      [AttrNames.SelectableElement]: true,
+      [AttrNames.InlineLinkElement]: true,
+      [AttrNames.SelectedId]: `${id}${LinkTag}`,
+    };
+  };
+  useEffect(() => {
+    if (nodeSelected) {
+      linkBtnRef.current && linkBtnRef.current.focus();
```
Comment (beyackle) [inline Composer/packages/extensions/visual-designer/src/widgets/DialogRef.tsx:34]: This can just be `linkBtnRef.current?.focus()`.

File: Composer/packages/extensions/visual-designer/src/utils/cursorTracker/tabMove.ts [hunk 2]
```diff
@@ -32,20 +33,38 @@ function findSelectableParent(element: SelectorElement, elementList: SelectorEle
...
-    const selectableChildren = findSelectableChildren(currentElement, selectableElements);
     if (selectableChildren.length > 0) {
       // Tab to inner selectable element.
       nextElement = selectableChildren[0];
     } else {
-      // Perform like presssing down arrow key.
-      nextElement = locateNearestElement(currentElement, selectableElements, Direction.Down, ['isNode', 'isEdgeMenu']);
+      const hasInlineLinkElement =
+        currentElement.selectedId.endsWith('dot') &&
+        selectableElements.find(element => element.selectedId === selectableParent?.selectedId + 'link');
```
Comment (beyackle) [inline Composer/packages/extensions/visual-designer/src/utils/cursorTracker/tabMove.ts:45]: There's probably a better way to write this without duplicating this expression (on line 48 and also on line 63, although 'link' there is placed with 'dot'). I won't block approval on needing it fixed, but if you could clean it up, it'd be nice.

File: Composer/packages/extensions/visual-designer/src/widgets/DialogRef.tsx (hunk 1 above)
Comment (alanlong9278) [reply Composer/packages/extensions/visual-designer/src/widgets/DialogRef.tsx]: Fixed it.

File: Composer/packages/extensions/visual-designer/src/utils/cursorTracker/tabMove.ts (hunk 2 above)
Comment (alanlong9278) [reply Composer/packages/extensions/visual-designer/src/utils/cursorTracker/tabMove.ts]: Refactor.
