### PR TITLE
fix: wrap parameters for cli commands in quotes

### LINKED ISSUE #5919: Failing to install prerelease packages
My package is marked as preview and an error occurs when trying to install on latest nightly build:

image

### PR DESCRIPTION
**Pull request by benbrown**
## Description

Wrap the parameters used in the cli  to install packages via package manager in quotes.

## Task Item

fixes #5919

### CODE REVIEW

File: extensions/runtimes/src/index.ts [hunk 1]
```diff
@@ -353,15 +353,13 @@ export default async (composer: any): Promise<void> => {
...
-      composer.log(
-        `EXECUTE: dotnet add ${_project.name}.csproj package ${packageName}${version ? ' --version=' + version : ''} `
-      );
-      const { stderr: installError, stdout: installOutput } = await execAsync(
-        `dotnet add ${_project.name}.csproj package ${packageName}${version ? ' --version=' + version : ''}`,
-        {
-          cwd: path.join(runtimePath),
-        }
-      );
+      const command = `dotnet add ${_project.name}.csproj package "${packageName}${
```
Comment (beyackle) [inline extensions/runtimes/src/index.ts:356]: If there's no version number, won't this end up with an unmatched `"` after `package`?

**Review by beyackle — CHANGES_REQUESTED** [review]

File: extensions/runtimes/src/index.ts (hunk 1 above)
Comment (benbrown) [reply extensions/runtimes/src/index.ts]: doh! yes.

**Review by benbrown — COMMENTED** [review]
@beyackle i fixed that!

**Review by beyackle — APPROVED** [review]
