### PR TITLE
fix: error dialog should allow scrolling of error text

### LINKED ISSUE #6727: Error dialog clips error message text
## Describe the bug

I'm using a nightly build of Composer where I can consistent cause the creation process to fail.  When I get an error message, and view the details of that message, the error text is clipped.  See attached screenshot

## Version
Version:  1.4.0-nightly.231667.d104286
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Figure out how to cause an error.  
2. view the details of the error from the error modal.  see attachment

## Expected behavior
The text of the error shouldn't be clipped.

## Screenshots
Screen Shot 2021-04-06 at 2 50 28 PM

## Additional context
I've selected the entire text in the error dialog as that makes it a bit easier to see the text formatting issue.

### PR DESCRIPTION
**Pull request by natalgar**
## Description

Bug: error popup was clipping error messages and the modal title was blank
Refactored formatErrorTitle to default to `Error` instead of blank `''`

## Task Item
 
closes #6727 

## Screenshots

image

error-scroll-gif

### CODE REVIEW

**Review by pavolum — APPROVED** [review]

**Review by benbrown — APPROVED** [review]

File: Composer/packages/client/src/components/ErrorPopup/ErrorPopup.tsx [hunk 1]
```diff
@@ -62,7 +61,7 @@ export const ErrorPopup = (props: ErrorPopupProps) => {
     }
   }, [props.error]);
 
-  const title = props.error ? formatErrorTitle(props.error) : '';
+  const title = props.error && props.error.summary ? formatErrorTitle(props.error.summary) : 'Error';
```
Comment (GeoffCoxMSFT) [inline Composer/packages/client/src/components/ErrorPopup/ErrorPopup.tsx:64]: Consider making this formatErrorTitle(props?.error?.summary) then in formatErrorTitle if !summary then return formatMessage('Error')

**Review by GeoffCoxMSFT — CHANGES_REQUESTED** [review]

**Review by hatpick — APPROVED** [review]

**Review by GeoffCoxMSFT — APPROVED** [review]
