### PR TITLE
a11y:  make focus visible on create node button

### LINKED ISSUE #2061: [Accessibility][Keyboard - Create Node]: Keyboard focus is not visible on 'Create Node' button.
**User Experience:**
Keyboard dependent users would face difficulty if keyboard focus does not visible on the control.

**Test Environment**
Browser: Microsoft Edge Canary Version: 82.0.425.0 (Official build)
OS build: 2004 (19564.1005)
Screen Reader: Narrator
URL: [Bot Framework Composer](http://localhost:3000/dialogs/Main)
[**Prerequisite Here**](https://github.com/microsoft/BotFramework-Composer)

**Repro Steps:** 
1. Open the above mentioned URL in EDGE and set the zoom at 400%.
2. Select 'Design Flow' from left navigation.
3. Now, navigate to the flow chart.
4. Navigate to "+" button available in the flow chart and observe the issue.

**Actual:** 
The keyboard focus is not visible at "+" button i.e. create node button.

**Expected:**
The focus should be clearly visible to each and every control available at the page.

**MAS Guideline:** [MAS2.4.7](https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={3b98b04f-4fab-4d3e-81af-a0906a34849c})

**Attachment:**
[MAS2.4.7_Focus not visible on Add node button.zip](https://github.com/microsoft/BotFramework-Composer/files/4241294/MAS2.4.7_Focus.not.visible.on.Add.node.button.zip)

### PR DESCRIPTION
**Pull request by alanlong9278**
## Description

As Marieke said:
```
Tab = black outline
Selection = blue outline
For the +, the outline should be around the circle, not a square.
```
Add circle outline for `+` button.
iconbutton-demo

## Task Item

fix #2061

### CODE REVIEW

File: Composer/packages/extensions/visual-designer/src/components/menus/IconMenu.tsx [hunk 1]
```diff
@@ -78,6 +80,9 @@ export const IconMenu: React.FC<IconMenuProps> = ({
       },
     };
 
+    const onMenuClick = () => {
+      handleMenuShow && handleMenuShow(true);
```
Comment (a-b-r-o-w-n) [inline Composer/packages/extensions/visual-designer/src/components/menus/IconMenu.tsx:84]: This looks like it never gets set back to false. Seems like a bug to me, but I haven't functionally tested this.

Comment (alanlong9278) [reply Composer/packages/extensions/visual-designer/src/components/menus/IconMenu.tsx:84]: Thanks for point out. I forgot to add callback to set menuSelected to false, fixed it.
