### PR TITLE
fix: luis authoringRegion not update in popup form

### LINKED ISSUE #1757: authoringRegion and defaultLanguage in settings not used in 'Publish LUIS models' dialog
## Describe the bug
The authoringRegion and defaultLanguage entered in /setting/dialog-settings are not used in the 'Publish LUIS models' dialog. While authoringKey is. 

## Version
SHA: test
Branch: stable
Commit hash: 99e87dc1fc26b55dca47aff01c2dc31fdda212f2 

## Browser
What browser are you using?

- [x] Chrome
- [ ] Safari
- [x] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce
1. Go to /setting/dialog-settings
2. Change the AuthoringRegion  to a non-default value
3. Click on 'Start Bot'
4. Wait for error
5. Click again.
4. View the difference.

## Expected behavior
I expected the values to propagate to the 'Publish LUIS models' dialog.

## Screenshots
bot-composer-settings

### PR DESCRIPTION
**Pull request by VanyLaw**
## Description

Fix an issue when changing authoring region or language in setting editor, the form data not changed correspondingly.
Accurate the Error message with Luis publish.

## Task Item

Closes #1757 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code refactor (non-breaking change which improve code quality, clean up, add tests, etc)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Doc update (document update)

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have functionally tested my change

## Screenshots

Please include screenshots or gifs if your PR include UX changes.

### CODE REVIEW

**Comment by boydc2014** [comment]
Can you help rename your PR title to a more descriptive one?

File: Composer/packages/server/src/models/bot/luPublisher.ts [hunk 1]
```diff
@@ -94,7 +94,7 @@ export class LuPublisher {
       });
       await this.saveStatus();
     } catch (error) {
-      throw new Error('Error publishing to LUIS.');
+      throw new Error((error.body && error.body.error && error.body.error.message) || 'Error publishing to LUIS.');
```
Comment (a-b-r-o-w-n) [inline Composer/packages/server/src/models/bot/luPublisher.ts]:
```suggestion
      throw new Error(error?.body?.error?.message ?? 'Error publishing to LUIS.');
```

Comment (VanyLaw) [reply Composer/packages/server/src/models/bot/luPublisher.ts]: done
