### PR TITLE
fix: qna migration bug

### LINKED ISSUE #4168: qna files migration errors.
## Describe the bug
Create a new todoluisbot. Then check global qnaFile state. You can see the number of qnafiles is not the same as dialog files.

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

### PR DESCRIPTION
**Pull request by liweitian**
## Description
We should do migration on server. This pr will check missing qna files, create them and return all files to client.

## Task Item
Closes #4168

### CODE REVIEW

File: Composer/packages/server/src/models/bot/botProject.ts [hunk 1]
```diff
@@ -728,6 +729,46 @@ export class BotProject implements IBotProject {
       fileList.set(file.name, file);
     });
 
+    const migrationFiles = await this._createQnAFilesForOldBot(fileList);
+
+    return new Map<string, FileInfo>([...fileList, ...migrationFiles]);
+  };
+
+  // migration: create qna files for old bots
+  private _createQnAFilesForOldBot = async (files: Map<string, FileInfo>) => {
```
Comment (srinaath) [inline Composer/packages/server/src/models/bot/botProject.ts:738]: I like that this work has been moved to the server to create the qna files for the bot. The code that was replaced in the DesignPage created a new qna file when a new dialog file is created on the client. It looks like this will only handle existing dialogs of the bot.

File: Composer/packages/server/src/models/utilities/util.ts [hunk 2]
```diff
@@ -0,0 +1,16 @@
+// Copyright (c) Microsoft Corporation.
+// Licensed under the MIT License.
+
+export const getDialogFileName = (file: string) => {
+  if (file.endsWith('.dialog')) {
```
Comment (srinaath) [inline Composer/packages/server/src/models/utilities/util.ts:5]: nitpick

I think u can simplify this `file.match(/(.+?)(\.[^.]*$|$)/).`This way u can get the extension and the name of the file in 1 line rather than endsWith and another substring function

File: Composer/packages/server/src/models/bot/botProject.ts (hunk 1 above)
Comment (srinaath) [reply Composer/packages/server/src/models/bot/botProject.ts:738]: The qna files for the new dialogs will are handled in dispatcher/dialogs.

**Review by srinaath — DISMISSED** [review]

File: Composer/packages/server/src/models/bot/botProject.ts (hunk 1 above)
Comment (liweitian) [reply Composer/packages/server/src/models/bot/botProject.ts:738]: 216db8343122f5dbac554463c1fde8c
In dispatchers/dialog.ts line 78. It already handled it.

File: Composer/packages/server/src/models/utilities/util.ts (hunk 2 above)
Comment (liweitian) [reply Composer/packages/server/src/models/utilities/util.ts]: The dialog file is a.dialog, while qna file is a.en-us.qna. The locale cannot be removed. So I change it in another way.

**Review by boydc2014 — APPROVED** [review]
