### PR TITLE
fix: Empty setting for recognizer configuration when switch bot

### LINKED ISSUE #7141: Empty setting for recognizer configuration when switch bot
Under skill branch, I often hit following errors.

- A Bot created with trigger phrases (recognizer is default recognizer)
- start the bot and bot executed as expected
- switch to another bot 
- switch back to A Bot 
- run bot might hit luis utterance can not be triggered.
- deep dive into more . This error more easily hit in multi-lang bot. And recognizer configuration  is not set correctly. 
image

Workaround step
- manually add intent trigger
- and reload this bot again , composer will auto-correct the missing recognizer configuration as below
image

@lei9444 for awareness

### PR DESCRIPTION
**Pull request by lei9444**
### Root cause
Composer move lu and qna parse to the backend, the recognizers may be generated when the lu parse result is empty. 

### Fix 
generate the recognizers after all files are parsed.

## Task Item
closes #7141

### CODE REVIEW

File: Composer/packages/client/src/recoilModel/Recognizers.tsx [hunk 1]
```diff
@@ -26,6 +26,10 @@ import { crossTrainConfigState, filePersistenceState, settingsState } from './at
 import { dialogsSelectorFamily, luFilesSelectorFamily, qnaFilesSelectorFamily } from './selectors';
 import { recognizersSelectorFamily } from './selectors/recognizers';
 
+const isFilesUnparsed = (files: { isContentUnparsed: boolean }[]) => {
```
Comment (hatpick) [inline Composer/packages/client/src/recoilModel/Recognizers.tsx:29]: ```isAnyFileNotParsed```

**Review by hatpick — DISMISSED** [review]

File: Composer/packages/client/src/recoilModel/Recognizers.tsx (hunk 1 above)
Comment (lei9444) [reply Composer/packages/client/src/recoilModel/Recognizers.tsx]: Thanks @hatpick

**Review by hatpick — APPROVED** [review]
