### PR TITLE
fix: reduce usage of tenant id in cache

### LINKED ISSUE #6688: Composer pins tenant id during publish profile creation; keeps alt account from publishing
## Describe the bug

Currently, during publish profile creation, composer caches tenant id after successful login.  Trying then to publish to an account in a different tenant fails as composer tries to use the cached first tenantid.

## Version

Version:  1.4.0-nightly.230964.e5e5020
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1) Create a bot in composer
2) Try to create a publish profile with MSIT creds and fail before completion
3) Try to create a publish profile with non MSIT creds (in my case, personal tenant)

Experience: cannot create publish profile as new ID is not in the tenant cached in step 2. No way also to log out of tenant in step 2 as you're not "logged in".

## Expected behavior

I can switch accounts freely, or explicitly "sign out" to clear cached tenant info.

## Screenshots

image

### LINKED ISSUE #6707: could not sign out during provision
Latest electron nightly
- open a bot which published before
- adding a new publish profile
- click "sign out" 

nothing happened and provision wizard go away.

### PR DESCRIPTION
**Pull request by a-b-r-o-w-n**
## Description

Use tenant id stored in publish profile for provisioning and publishing.

## Task Item

fixes #6707
fixes #6688

### CODE REVIEW

**Comment by a-b-r-o-w-n** [comment]
Testing installers before marking ready.

File: Composer/packages/server/src/controllers/auth.ts [hunk 1]
```diff
@@ -42,13 +45,15 @@ async function getAccessToken(req: GetAccessTokenRequest, res: Response) {
...
+function logOut(req, res) {
   try {
     authService.logOut();
-  } catch {
-    res.status(500);
+    res.status(200).end();
+  } catch (err) {
+    log('Error logging out:');
+    log(err);
+    res.status(500).end();
```
Comment (tonyanziano) [inline Composer/packages/server/src/controllers/auth.ts:55]: nit: it might be useful to send the error object to the client `res.status(500).json(err).end()`

**Review by tonyanziano — APPROVED** [review]

File: Composer/packages/server/src/controllers/auth.ts (hunk 1 above)
Comment (a-b-r-o-w-n) [reply Composer/packages/server/src/controllers/auth.ts:55]: Will do.

File: Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx [hunk 2]
```diff
@@ -165,7 +165,14 @@ export const PublishProfileDialog: React.FC<PublishProfileDialogProps> = (props)
 
       let arm, graph;
       if (!userShouldProvideTokens()) {
-        const tenantId = getTenantIdFromCache();
+        let tenantId = config.tenantId;
+
+        if (!tenantId) {
+          // eslint-disable-next-line no-console
+          console.log('Provision config does not include tenant id, using tenant id from cache.');
```
Comment (cwhitten) [inline Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx:172]: should this get updated?

File: extensions/azurePublish/src/components/azureProvisionDialog.tsx [hunk 3]
```diff
@@ -400,16 +400,23 @@ export const AzureProvisionDialog: React.FC = () => {
         );
       }
     } else {
+      // TODO: handle when existing profile is being edited
```
Comment (cwhitten) [inline extensions/azurePublish/src/components/azureProvisionDialog.tsx:403]: is @GeoffCoxMSFT aware of this?

Comment (a-b-r-o-w-n) [reply extensions/azurePublish/src/components/azureProvisionDialog.tsx:403]: I don't know. I plan on creating an issue to track.

File: Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx (hunk 2 above)
Comment (a-b-r-o-w-n) [reply Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx:172]: This is just in case. This should not be executed anymore with this PR because I am passing in the tenant id when starting a provision.

**Review by cwhitten — APPROVED** [review]
