### PR TITLE
fix: trigger creation LUIS entity labelling

### LINKED ISSUE #7517: Label entity is not enable in create a trigger dialog
## Describe the bug

While creating trigger label entity is not enable in create a trigger dialog , Its possible only after created the trigger

## Version

Version:  2.0.0-nightly.241057.db66154
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

Refer the screenshots 

## Screenshots

Create trigger label entity option is disable.

image

image

### PR DESCRIPTION
**Pull request by zhixzhan**
## Description

Fix by maintain a shadow lufile appending  created trigger intent, then editor will get the context.

## Task Item
close #7517 

## Screenshots
image

### CODE REVIEW

File: Composer/packages/client/src/components/TriggerCreationModal/ResolveTriggerWidget.tsx [hunk 1]
```diff
@@ -1,13 +1,14 @@
 // Copyright (c) Microsoft Corporation.
```
Comment (hatpick) [inline Composer/packages/client/src/components/TriggerCreationModal/ResolveTriggerWidget.tsx:1]: please revert the name changes of file, it's a render function not a component

**Review by hatpick — CHANGES_REQUESTED** [review]

File: Composer/packages/client/src/components/TriggerCreationModal/ResolveTriggerWidget.tsx (hunk 1 above)
Comment (zhixzhan) [reply Composer/packages/client/src/components/TriggerCreationModal/ResolveTriggerWidget.tsx]: Hi @hatpick , I'm using `useState` inside this function, eslint will throw this error.
image

Comment (zhixzhan) [reply Composer/packages/client/src/components/TriggerCreationModal/ResolveTriggerWidget.tsx]: I moved useState to parent components, resolved this error.

**Review by hatpick — APPROVED** [review]
