### PR TITLE
fix: generate responses

### LINKED ISSUE #5295: Composer server should return error information for form dialog generation
## Describe the bug

The generation call is always returning success even when there are problems reported by bf-generate.

## Version

main branch, 2020-12-10

## Browser

- [ ] Electron distribution
- [ X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ X] Windows
- [ ] Ubuntu

## To Reproduce

N/A

## Expected behavior

Return errors from the server.

### PR DESCRIPTION
**Pull request by GeoffCoxMSFT**
## Description

- updated to track errors during and success of generate call
- return reduces payload for generate and deleteDialog (project ID rather than entire project)
- update to add logs to form dialog error state

## Task Item

Closes #5295 

## Screenshots

### CODE REVIEW

File: Composer/packages/server/src/controllers/formDialog.ts [hunk 1]
```diff
@@ -67,9 +67,12 @@ const generate = async (req: Request, res: Response) => {
 
     const templatesDirs = await getTemplateDirs();
 
-    await currentProject.generateDialog(name, templatesDirs);
-    const updatedProject = await BotProjectService.getProjectById(projectId, user);
-    res.status(200).json({ id: projectId, ...updatedProject.getProject() });
+    const result = await currentProject.generateDialog(name, templatesDirs);
+
+    if (!result.success) {
+      res.status(500).json({ id: projectId, errors: result.errors });
```
Comment (hatpick) [inline Composer/packages/server/src/controllers/formDialog.ts:73]: I think you need to return here.

**Review by hatpick — CHANGES_REQUESTED** [review]

**Review by hatpick — APPROVED** [review]
