### PR TITLE
fix: do not preset name when creating a dialog

### LINKED ISSUE #1815: Dot not preset name during creating a dialog
Complete the necessary portions of this template and delete the rest.

## Describe the bug
should not preset a dialog name

### PR DESCRIPTION
**Pull request by liweitian**
## Description
The creating a bot and creating a dialog share the pop up form. I pass into a props to check whether we need to preset name.

## Task Item
Closes #1815 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have functionally tested my change

### CODE REVIEW

File: Composer/packages/client/src/CreationFlow/DefineConversation/index.tsx [hunk 1]
```diff
@@ -42,6 +42,7 @@ interface DefineConversationProps {
   focusedStorageFolder?: StorageFolder;
   currentPath?: string;
   bots?: Bots[];
+  shouldPresetName: boolean;
```
Comment (boydc2014) [inline Composer/packages/client/src/CreationFlow/DefineConversation/index.tsx]: I understand this fix, but we are adding more and more on this `DefineConversation` component to make sure it works both when creating "bot" and "dialog", even when we are now having very different UI for that, right? 

Can you just decouple it, by not sharing such this component at such a high level, or even just remove it? Let's try to make it easier to figure out what happened when "creating a bot", and what happened when "creating a dialog"

File: Composer/packages/client/src/pages/design/new-dialog-modal.tsx [hunk 2]
```diff
@@ -19,12 +20,7 @@ const NewDialogModal: React.FC<NewDialogModalProps> = props => {
 
   return (
     <DialogWrapper isOpen={isOpen} onDismiss={onDismiss} {...DialogCreationCopy.DEFINE_CONVERSATION_OBJECTIVE}>
-      <DefineConversation
-        onSubmit={onSubmit}
-        onDismiss={onDismiss}
-        onGetErrorMessage={onGetErrorMessage}
-        enableLocationBrowse={false}
-      />
+      <DefineDialog onSubmit={onSubmit} onDismiss={onDismiss} onGetErrorMessage={onGetErrorMessage} />
```
Comment (boydc2014) [inline Composer/packages/client/src/pages/design/new-dialog-modal.tsx]: Maybe it's not necessary to split this into two files, given the naming of "defineDialog.tsx" and "new-dialog-modal.tsx" are not clear and not consistenst. 

I think a simple "createDialog.tsx" would work

File: Composer/packages/client/src/pages/design/defineDialog.tsx [hunk 3]
```diff
@@ -0,0 +1,125 @@
...
+interface FormDataError {
+  name?: string;
+}
+
+interface Bots {
+  name: '';
+  path: '';
+}
+
+interface DefineDialogProps {
```
Comment (boydc2014) [inline Composer/packages/client/src/pages/design/defineDialog.tsx]: Let's call this CreateDialog, it would be more accurate.

File: Composer/packages/client/src/pages/design/defineDialog.tsx [hunk 4]
```diff
@@ -0,0 +1,125 @@
...
+import { DialogFooter } from 'office-ui-fabric-react/lib/Dialog';
+import { Stack, StackItem } from 'office-ui-fabric-react/lib/Stack';
+import { TextField } from 'office-ui-fabric-react/lib/TextField';
+
+import { StorageFolder } from '../../store/types';
+import { StoreContext } from '../../store';
+
+import { name, description, styles as wizardStyles } from './styles';
+
+interface FormData {
```
Comment (boydc2014) [inline Composer/packages/client/src/pages/design/defineDialog.tsx]: I would rather call this createDialogParams

File: Composer/packages/client/src/pages/design/defineDialog.tsx [hunk 5]
```diff
@@ -0,0 +1,125 @@
...
+  name: string;
+  description: string;
+  location: string;
+}
+
+interface FormDataError {
```
Comment (boydc2014) [inline Composer/packages/client/src/pages/design/defineDialog.tsx]: why we need an interface for this? which is only one filed, and is optional?

File: Composer/packages/client/src/pages/design/defineDialog.tsx [hunk 6]
```diff
@@ -0,0 +1,125 @@
...
+  name?: string;
+}
+
+interface Bots {
```
Comment (boydc2014) [inline Composer/packages/client/src/pages/design/defineDialog.tsx]: in createDialog, do we need a interface of Bots?

File: Composer/packages/client/src/CreationFlow/DefineConversation/index.tsx [hunk 7]
```diff
@@ -129,8 +127,8 @@ export const DefineConversation: React.FC<DefineConversationProps> = props => {
 
   const handleSubmit = e => {
     e.preventDefault();
-    const errors = validateForm(formData);
-
+    let errors = validateForm(formData);
+    errors = isEmptyName(formData.name);
```
Comment (a-b-r-o-w-n) [inline Composer/packages/client/src/CreationFlow/DefineConversation/index.tsx]: This will always overwrite `errors`. Why doesn't `validateForm` check for an empty name?

File: Composer/packages/client/src/pages/design/createDialog.tsx [hunk 8]
```diff
@@ -0,0 +1,115 @@
...
+  onDismiss: () => void;
+  onCurrentPathUpdate?: (newPath?: string, storageId?: string) => void;
+  focusedStorageFolder?: StorageFolder;
+  currentPath?: string;
+  isOpen: boolean;
+}
+
+const initialFormDataError = {};
+
+export const CreateDialog: React.FC<CreateDialogProps> = props => {
```
Comment (yeze322) [inline Composer/packages/client/src/pages/design/createDialog.tsx]: The component name looks like an action, not a descriptive name. Might be `DialogCreationXXXX` (modal / widget / form).

File: Composer/packages/client/src/pages/design/createDialog.tsx [hunk 9]
```diff
@@ -0,0 +1,115 @@
...
+  const { state } = useContext(StoreContext);
+  const { dialogs } = state;
+  const { onSubmit, onDismiss, isOpen } = props;
+  const initalFormData: CreateDialogParams = { name: '', description: '' };
```
Comment (yeze322) [inline Composer/packages/client/src/pages/design/createDialog.tsx]: typo: `initial`

File: Composer/packages/client/src/pages/design/createDialog.tsx [hunk 10]
```diff
@@ -0,0 +1,115 @@
...
+import { TextField } from 'office-ui-fabric-react/lib/TextField';
+
+import { DialogCreationCopy } from '../../constants';
+import { DialogWrapper } from '../../components/DialogWrapper/index';
+import { StorageFolder } from '../../store/types';
+import { StoreContext } from '../../store';
+
+import { name, description, styles as wizardStyles } from './styles';
+
+interface CreateDialogParams {
```
Comment (yeze322) [inline Composer/packages/client/src/pages/design/createDialog.tsx]: Also naming problem. `xxxParams` is not a meaningful name to a data type. Seems this object represents a collection of form fields (dialog creation form), maybe name it `Dialog` / `DialogData` / `DialogForm`.

File: Composer/packages/client/src/pages/design/createDialog.tsx [hunk 11]
```diff
@@ -0,0 +1,115 @@
...
+interface CreateDialogProps {
+  onSubmit: (createDialogParams: CreateDialogParams) => void;
+  onDismiss: () => void;
+  onCurrentPathUpdate?: (newPath?: string, storageId?: string) => void;
+  focusedStorageFolder?: StorageFolder;
+  currentPath?: string;
+  isOpen: boolean;
+}
+
+const initialFormDataError = {};
```
Comment (yeze322) [inline Composer/packages/client/src/pages/design/createDialog.tsx]: why we define this initial state outside the component? it could be written inline )
```ts
useState({})
```

File: Composer/packages/client/src/pages/design/createDialog.tsx [hunk 12]
```diff
@@ -0,0 +1,115 @@
...
+    const errors: { name?: string } = {};
+    const { name } = data;
+
+    if (name) {
+      if (!nameRegex.test(name)) {
+        errors.name = formatMessage(
+          'Spaces and special characters are not allowed. Use letters, numbers, -, or _., numbers, -, and _'
+        );
+      }
+      if (dialogs.findIndex(dialog => dialog.id === name) > -1) {
```
Comment (yeze322) [inline Composer/packages/client/src/pages/design/createDialog.tsx]: `dialogs.some()`

**Comment by boydc2014** [comment]
Approved and let's on hold merge till @cwhitten and @a-b-r-o-w-n get a chance to take a look.
