### PR TITLE
fix: introduce ability to pick a free or paid tier of QnA

### LINKED ISSUE #6866: QnAMaker creation experience is fixed to free tier
# Describe the bug

After creating a new bot you are prompted where needed to select/create QnAMaker/LUIS keys. When creating a new Qnamaker key it doesn't prompt you for pricing tier, it seems to default to free meaning that if you have exceeded your quota of free keys the feature doesn't work for you.

**Suspect the same issue applies to LUIS resources too.**

## Version

1.4.0-nightly.233776

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new bot (e.g. basic assistant)
2. In rocket ship UX select create a new key
3. Observe no pricing tier option shown
4. If your azure sub has more than 1? free tier qnamaker it will fail to create.

## Expected behavior

1. Pricing tier to be prompted for and used instead of hardcoded (?)

## Screenshots

image

### LINKED ISSUE #7219: Create New QnA Maker resource screen rendering issue
## Describe the bug

When I use the Rocket Ship to create a new QnA Maker in a new resource group, I get a modal that is rendered too small.

image

## Version

Version:  1.4.0-nightly.237504.97571e0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a QnA Maker template bot
2. Go to rocket ship and Click on Add a QnA Maker key
3. Try to create a new one in a new resource group
4. Get weird modal render

## Expected behavior

Modal renders large enough to fit the items needed to select

### PR DESCRIPTION
**Pull request by benbrown**
## Description

Introduces an optional choice of pricing tier for the ManageService widget. This is then plumbed through for the QNA maker version of this to offer a free or paid tier for the underlying QNA services

## Task Item

Fixes #6866 
Fixes #7219

## Screenshots

Screen Shot 2021-04-20 at 4 01 31 PM

### CODE REVIEW

File: Composer/packages/client/src/components/ManageService/ManageService.tsx [hunk 1]
```diff
@@ -592,10 +605,25 @@ export const ManageService = (props: ManageServiceProps) => {
...
+              styles={inputStyles}
               value={resourceName}
               onChange={(e, val) => setResourceName(val || '')}
             />
+            {props.tiers && (
+              <Dropdown
+                required
+                aria-label={formatMessage('Pricing tier')}
+                data-testid={'tier'}
+                disabled={!subscriptionId || loading !== undefined}
```
Comment (GeoffCoxMSFT) [inline Composer/packages/client/src/components/ManageService/ManageService.tsx:617]: This will disabled when loading === true or when loading === false.

**Review by GeoffCoxMSFT — APPROVED** [review]
