### PR TITLE
fix: multiple minor bugs in provision and creation

### LINKED ISSUE #6836: The "provision completed" notification should include a deep link to the publishing action for that newly created environment

### LINKED ISSUE #6871: Create QnA Maker bot Template configuration screen disappears when you leave composer and come back
## Describe the bug

When you are creating a new bot from the QnA Maker template the post configuration screen disappears when you click away from composer and clicks back into composer.  There is no other way to get that configuration screen back either.

## Version

Version:  1.4.0-nightly.233776.7019ef0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

SmallQnADisapperBug

### LINKED ISSUE #6971: Creating New Bot, "Node" tab needs to show "(Preview)"
## Describe the bug

When creating a new Bot, I'm presented with choices in C# and Node. 

The "Node" tab needs to show "Node (Preview)" to indicate it's not GA / Ready. The Node support is *preview* at Build. 

## Version
Version:  1.4.0-nightly.235171.cfc0c11
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## Expected behavior

Node Bots created with Composer are "PREVIEW" at build. The UX needs to reflect this. 

## Screenshots

image

### LINKED ISSUE #7003: UX - Wrong error message in Create a Bot project
## Describe the bug

Enter the project name with empty string ( "space")  , its showing wrong error message
"Bot name cannot not start with a number "

## Version

Version:  1.4.0-nightly.235171.cfc0c11
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1- Go to project template select blank bot 
2- In the name filed .. typo the space.

## Expected behavior

Error message should display  **name is required**

## Screenshots

project

### PR DESCRIPTION
**Pull request by pavolum**
## Description

Various fixes of minor bugs listed below:

## Task Item

fixes #6871 Made create from qna url modal blocking
fixes #6836 Fixed a react state bug to update publish profile options when a new one is created in the new tab view for the publish page
fixes #6971 Added preview text to nod tab text
fixes #7003 Fixed error message terminology for invalid bot name

### CODE REVIEW

File: Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx [hunk 1]
```diff
@@ -154,7 +154,7 @@ const DefineConversationV2: React.FC<DefineConversationProps> = (props) => {
         if (!value || !nameRegexV2.test(`${value}`)) {
           // botName is used as used when generating runtime namespaces which cannot start with a number
           if (value && !isNaN(+value.toString().charAt(0))) {
-            return formatMessage('Bot name cannot not start with a number');
+            return formatMessage('Bot name cannot not start with a number or space');
```
Comment (tonyanziano) [inline Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx:157]: `cannot not` seems really confusing, is this intended or a typo?

**Review by tonyanziano — CHANGES_REQUESTED** [review]

File: Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx (hunk 1 above)
Comment (pavolum) [reply Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx:157]: Ah oops, I have removed the extra `not`

**Review by tonyanziano — APPROVED** [review]
