### PR TITLE
fix: Update provision & publishing copy (#7583)

### LINKED ISSUE #7583: Fit & finish - UI Copy | Provision and publish
Fit & finish - UI Copy | Provision and publish

White cells = existing copy
Yellow/blue cells = new copy (replace existing copy with this)
Orange = P0 | MUST UPDATE

Link to 'live' copy on ' Provision and publish ' tab: 
https://microsoft.sharepoint.com/:x:/r/teams/ConversationalAI785/_layouts/15/Doc.aspx?sourcedoc=%7B6B1FACBD-B5FE-4AD2-A35B-995635C1696B%7D&file=glossary.xlsx&action=edit&mobileredirect=true&wdPreviousSession=36539654-a42b-4b87-be1b-de96507b4422&wdOrigin=TEAMS-ELECTRON.teams.undefined&cid=676cf454-61e0-4182-bd27-39044bb51cea

Create profile
Generate instructions
Provide details
Review
Select additional services
Configure and create
Add new provisioning profile -  long
Publish to PVA
Add new provisoning profile - create
Add new publishing profile_new
Add publishing profile

### PR DESCRIPTION
**Pull request by natalgar**
This is the updated copy for provisioning and publishing P0 items as of 5/4/21.

Fixes #7583 

Screenshots

image
image
image
image
image
image
image

### CODE REVIEW

File: extensions/azurePublish/src/components/ChooseProvisionAction.tsx [hunk 1]
```diff
@@ -100,40 +100,48 @@ const CreateActionContent = () => {
...
+        </Instruction>
+        <Instruction>
+          <InstructionTitle>{formatMessage('Step 4')}</InstructionTitle>
+          <InstructionDetails>
+            <Text>{formatMessage('Review and confirm resources to be created')}</Text>
           </InstructionDetails>
         </Instruction>
       </Details>
+      <Summary>
+        <Text>{formatMessage('Once provisioned, your new resources will be available in the Azure portal. ')}</Text>
```
Comment (tdurnford) [inline extensions/azurePublish/src/components/ChooseProvisionAction.tsx:120]: We shouldn't add spaces to the end of `formatMessage` to add space between links - it could easily get lost in translation. We should either add a space with `{' '}` or use `formatMessage.rich` take a look at https://github.com/microsoft/BotFramework-Composer/blob/b45b4c8a06d513285c289efcd70ddda1ee30e009/Composer/packages/client/src/pages/botProject/AllowedCallers.tsx#L149

File: extensions/azurePublish/src/components/ChooseProvisionAction.tsx [hunk 2]
```diff
@@ -100,40 +100,48 @@ const CreateActionContent = () => {
...
+            {formatMessage(
+              'Select this option if you have access to existing Azure resources and their associated values.'
+            )}
+          </Text>
         </p>
         <p>
           <Text>
             {formatMessage(
-              'Edit the JSON file in the Publish Configuration field. You will need to find the values of associated resources in your Azure portal. A list of required and optional resources may include:'
+              'Copy and paste the JSON file containing the values of your existing Azure resources, from the Azure portal. This file includes values for some or all of the following:'
```
Comment (tdurnford) [inline extensions/azurePublish/src/components/ChooseProvisionAction.tsx:144]: Grammatically, that comma is incorrect. 
```suggestion
              'Copy and paste the JSON file containing the values of your existing Azure resources from the Azure portal. This file includes values for some or all of the following:'
```

File: extensions/azurePublish/src/components/azureProvisionDialog.tsx [hunk 3]
```diff
@@ -167,9 +167,9 @@ const DialogTitle = {
     ),
   },
   REVIEW: {
-    title: formatMessage('Review & create'),
+    title: formatMessage('Review resources to be created'),
     subText: formatMessage(
-      'Please review the resources that will be created for your bot. Once these resources are provisioned, they will be available in your Azure portal.'
+      'The following resources will be created and provisioned for your bot. Once provisioned, they will be available in the Azure portal. '
```
Comment (tdurnford) [inline extensions/azurePublish/src/components/azureProvisionDialog.tsx:172]: Do not add spaces to the end of `formatMessage`

File: extensions/azurePublish/src/components/azureProvisionDialog.tsx [hunk 4]
```diff
@@ -376,8 +376,9 @@ export const AzureProvisionDialog: React.FC = () => {
     } --createLuisResource=${createLuisResource} --createLuisAuthoringResource=${createLuisAuthoringResource} --createCosmosDb=${createCosmosDb} --createStorage=${createStorage} --createAppInsights=${createAppInsights} --createQnAResource=${createQnAResource}`;
 
     const instructions = formatMessage(
-      'I am working on a Microsoft Bot Framework project, and I now require some Azure resources to be created.' +
-        ' Please follow the instructions below to create these resources and provide them to me.\n\n' +
+      'I am creating a conversational experience using Microsoft Bot Framework project. For my project to work,' +
```
Comment (tdurnford) [inline extensions/azurePublish/src/components/azureProvisionDialog.tsx:379]: Why are we using multiple strings instead of just one long string? Readability?

File: extensions/azurePublish/src/node/resourceTypes.ts [hunk 5]
```diff
@@ -28,7 +28,7 @@ export const AzureResourceDefinitions = {
   },
   [AzureResourceTypes.BOT_REGISTRATION]: {
     description:
-      'Your own Bot hosted where you want, registered with the Azure Bot Service. Build, connect, and manage Bots to interact with your users wherever they are - from your app or website to Cortana, Skype, Messenger and many other services.',
+      'When registered with the Azure Bot Service,  you can host your bot in any environment and enable customers from a variety of channels, such as your app or website, Direct Line Speech, Microsoft Teams and more.',
```
Comment (tdurnford) [inline extensions/azurePublish/src/node/resourceTypes.ts:31]: Remove extra space
```suggestion
      'When registered with the Azure Bot Service, you can host your bot in any environment and enable customers from a variety of channels, such as your app or website, Direct Line Speech, Microsoft Teams and more.',
```

File: extensions/azurePublish/src/node/resourceTypes.ts [hunk 6]
```diff
@@ -58,8 +58,7 @@ export const AzureResourceDefinitions = {
     key: AzureResourceTypes.COSMOSDB,
   },
   [AzureResourceTypes.APPINSIGHTS]: {
-    description:
-      'Application performance, availability and usage information at your fingertips. Used for Bot chatting data analyzing.',
+    description: 'Application Insights allows you to monitor and analyze usage and performance of your bot. ',
```
Comment (tdurnford) [inline extensions/azurePublish/src/node/resourceTypes.ts:61]: Don't use trailing spaces in `formatMessage`

File: extensions/azurePublish/src/node/resourceTypes.ts [hunk 7]
```diff
@@ -83,7 +82,7 @@ export const AzureResourceDefinitions = {
   },
   [AzureResourceTypes.BLOBSTORAGE]: {
     description:
-      'Microsoft Azure provides scalable, durable cloud storage, backup, and recovery solutions for any data, big or small. Used for bot transcripts logging.',
+      'Azure blob storage provides scalable cloud storage, backup and recovery solutions for any data, including bot transcript logs. ',
```
Comment (tdurnford) [inline extensions/azurePublish/src/node/resourceTypes.ts:85]: Don't use trailing spaces in formatMessage

**Review by tdurnford — CHANGES_REQUESTED** [review]

File: Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx [hunk 8]
```diff
@@ -54,14 +54,10 @@ export const PublishProfileDialog: React.FC<PublishProfileDialogProps> = (props)
...
   const { provisionToTarget, addNotification } = useRecoilValue(dispatcherState);
-
-  const [dialogTitle, setTitle] = useState({
-    title: current ? formatMessage('Edit publishing profile') : formatMessage('Add new publishing profile'),
-    subText: formatMessage('A publishing profile provides the secure connectivity required to publish your bot. '),
-  });
-
   const [selectedType, setSelectType] = useState<PublishType | undefined>();
 
+  const [dialogTitle, setTitle] = useState(formatDialogTitle());
```
Comment (GeoffCoxMSFT) [inline Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx:59]: As we discussed, the formatDialogTitle needs to be moved up so it is declared before it is used.

File: extensions/azurePublish/src/components/ChooseProvisionAction.tsx (hunk 1 above)
Comment (GeoffCoxMSFT) [reply extensions/azurePublish/src/components/ChooseProvisionAction.tsx:120]: I would add &nbsp; between </Text> and <LearnMoreLink>.

File: extensions/azurePublish/src/components/ChooseProvisionAction.tsx (hunk 2 above)
Comment (GeoffCoxMSFT) [reply extensions/azurePublish/src/components/ChooseProvisionAction.tsx:144]: Whatever Marieke wants, Marieke gets :)

File: extensions/azurePublish/src/components/azureProvisionDialog.tsx (hunk 4 above)
Comment (GeoffCoxMSFT) [reply extensions/azurePublish/src/components/azureProvisionDialog.tsx:379]: Yes for readability.  We could probably use a line continuation backslash but that can introduce whitespace issues.

File: Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx [hunk 9]
```diff
@@ -131,6 +124,16 @@ export const PublishProfileDialog: React.FC<PublishProfileDialogProps> = (props)
     }
   }, [current, projectId]);
 
+  function formatDialogTitle() {
```
Comment (tdurnford) [inline Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx:127]: Can you change this to arrow function? Also, we should move this out of the scope of the component and pass `current` as a parameter.

File: extensions/azurePublish/src/components/ChooseProvisionAction.tsx (hunk 2 above)
Comment (cwhitten) [reply extensions/azurePublish/src/components/ChooseProvisionAction.tsx:144]: @mareekuh can you comment here?

File: extensions/azurePublish/src/components/azureProvisionDialog.tsx (hunk 4 above)
Comment (tdurnford) [reply extensions/azurePublish/src/components/azureProvisionDialog.tsx:379]: I think breaking them into sentences would be best

File: extensions/azurePublish/src/components/ChooseProvisionAction.tsx (hunk 1 above)
Comment (tdurnford) [reply extensions/azurePublish/src/components/ChooseProvisionAction.tsx:120]: What's the benefit of `&nbsp;` over `{' '}`? Since the link is not nested in the text I think we should use either `&nbsp;` or `{' '}` to add the space and not `formatMessage.rich`

**Comment by mareekuh** [comment]
I've not been using oxford commas.
The user experience objective for  'UI copy + Learn more' is for people to easily distinguish what is instruction and what is a link for more info. We do this by adding a space or a soft return.

In the xls I did not intend to infer an implementation. So if @tdurnford  recommended solution offer a reliable, tracaeble manner to do so, this works for me (-:

File: Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx (hunk 9 above)
Comment (natalgar) [reply Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx]: done

File: Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx (hunk 8 above)
Comment (natalgar) [reply Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx]: done

File: extensions/azurePublish/src/components/azureProvisionDialog.tsx (hunk 4 above)
Comment (natalgar) [reply extensions/azurePublish/src/components/azureProvisionDialog.tsx]: broke into sentences 👍

File: Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx [hunk 10]
```diff
@@ -38,6 +38,16 @@ const Page = {
   ConfigProvision: Symbol('config'),
 };
 
+const formatDialogTitle = (current) => {
+  return {
+    title: current ? formatMessage('Edit publishing profile') : formatMessage('Create a publishing profile'),
+    subText: formatMessage(`To test, run and publish your bot, it needs Azure resources such as app registration,
+          hosting and channels. Other resources, such as language understanding and storage are optional.
+          A publishing profile contains all of the information necessary to provision and publish your bot,
+          including its Azure resources. `),
```
Comment (tdurnford) [inline Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx:47]: It looks like there is also a trailing space here.

File: extensions/azurePublish/src/components/ChooseProvisionAction.tsx (hunk 1 above)
Comment (GeoffCoxMSFT) [reply extensions/azurePublish/src/components/ChooseProvisionAction.tsx:120]: `&nbsp;` is standard HTML, the `{' '}` requires running code and context switching from HTML to JS.  It doesn't make much difference.

File: Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx [hunk 11]
```diff
@@ -38,6 +38,17 @@ const Page = {
   ConfigProvision: Symbol('config'),
 };
 
+const formatDialogTitle = (current) => {
```
Comment (hatpick) [inline Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx:41]: Please change ```current``` here to ```isEditing: boolean```

File: Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx [hunk 12]
```diff
@@ -54,14 +65,10 @@ export const PublishProfileDialog: React.FC<PublishProfileDialogProps> = (props)
...
   const { provisionToTarget, addNotification } = useRecoilValue(dispatcherState);
-
-  const [dialogTitle, setTitle] = useState({
-    title: current ? formatMessage('Edit publishing profile') : formatMessage('Add new publishing profile'),
-    subText: formatMessage('A publishing profile provides the secure connectivity required to publish your bot. '),
-  });
-
   const [selectedType, setSelectType] = useState<PublishType | undefined>();
 
+  const [dialogTitle, setTitle] = useState(formatDialogTitle(current));
```
Comment (hatpick) [inline Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx:70]: after making the type of formatDialogTitle boolean, change this to ```formatDialogTitle(!!current)```

File: Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx [hunk 13]
```diff
@@ -89,10 +96,7 @@ export const PublishProfileDialog: React.FC<PublishProfileDialogProps> = (props)
     PluginAPI.publish.closeDialog = closeDialog;
     PluginAPI.publish.onBack = () => {
       setPage(Page.ProfileForm);
-      setTitle({
-        title: current ? formatMessage('Edit publishing profile') : formatMessage('Add new publishing profile'),
-        subText: formatMessage('A publishing profile provides the secure connectivity required to publish your bot. '),
-      });
+      setTitle(formatDialogTitle(current));
```
Comment (hatpick) [inline Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx:99]: same comment L70

File: Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx (hunk 11 above)
Comment (GeoffCoxMSFT) [reply Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx:41]: Will need to pick this up in a future PR.

File: Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx (hunk 12 above)
Comment (GeoffCoxMSFT) [reply Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx:70]: Will need to pick this up in a future PR.

File: Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx (hunk 13 above)
Comment (GeoffCoxMSFT) [reply Composer/packages/client/src/pages/botProject/create-publish-profile/PublishProfileDialog.tsx:99]: Will need to pick this up in a future PR.

**Review by tdurnford — APPROVED** [review]
