### PR TITLE
fix: unify display name function in client, visual editor

### LINKED ISSUE #5383: Trigger labels in bot tree, breadcrumbs, and property don't match
## Describe the bug

1.3.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

I noticed this when I generated a form dialog:

image

image

But also in the LUIS To Do sample:

image

## Expected behavior

In general, the name should be the same in the tree, breadcrumbs, and property pane.
For a form dialog, the form dialog should not have "main dialog" in the breadcrumbs because it is not a main dialog.

### PR DESCRIPTION
**Pull request by alanlong9278**
## Description

bugfix: dialog name & trigger name mismatch in left menu,  breadcumbs & editors.

### solution

- [x]  Unify display name function. use `getFriedlyName` in client & editors, Shared the function in `bfc/shared` module.
- [x] Refactor breadcrumbs display name hook. It will auto change the display name when changing the name in form editor including dialog name, trigger name & action name.
 name
- [x] prefer using `designer.name` instead of dialog file name for dialog displayName in left menu  @zhixzhan 
  (if update name in property editor, for perf consideration, project tree won't real-time refresh )

## Task Item

closes #5383

### CODE REVIEW

File: Composer/packages/adaptive-flow/src/adaptive-flow-renderer/widgets/TriggerSummary/TriggerSummary.tsx [hunk 1]
```diff
@@ -26,10 +25,15 @@ function getLabel(data: any): string {
 }
 
 function getName(data: any): string {
```
Comment (yeze322) [inline Composer/packages/adaptive-flow/src/adaptive-flow-renderer/widgets/TriggerSummary/TriggerSummary.tsx:27]: It can be retired by the `getFriendlyName` in the @bfc/shared lib

**Comment by yeze322** [comment]
Looks good to extract a new shared function `getFriendlyName`.

File: Composer/packages/client/src/pages/design/DesignPage.tsx [hunk 2]
```diff
@@ -311,6 +310,30 @@ const DesignPage: React.FC<RouteComponentProps<{ dialogId: string; projectId: st
...
   }, [location]);
 
+  // get newest label for breadcrumbs
+  useEffect(() => {
+    if (currentDialog.content) {
+      setBreadcrumbs((prev) => {
+        return prev.map((b) => {
+          const separatorIndex = b.key.indexOf('-');
+          const type = b.key.substr(0, separatorIndex);
+          const name = b.key.substr(separatorIndex + 1);
```
Comment (beyackle) [inline Composer/packages/client/src/pages/design/DesignPage.tsx:320]: You can use a Regexp here - try something like
```
const regexp = /(?<type>[a-z]+)-(?<name>.*)/;
const { type, name } = match?.groups;
```

Since the `type` is something we have full control over, we know the match will succeed, but there might be some additional guards that need to be there so TS doesn't complain.

**Review by beyackle — DISMISSED** [review]
Looks mostly good - just one change I'd like to see.

File: Composer/packages/client/src/pages/design/DesignPage.tsx (hunk 2 above)
Comment (alanlong9278) [reply Composer/packages/client/src/pages/design/DesignPage.tsx:320]: I have checked the `type` variable. It is just set & use in the design page, we can add new type if have additional guards. I  create a const variable `types` to manager the type. 
```
const Types = {
  Dialog: 'dialog',
  Trigger: 'trigger',
  Action: 'action',
};
```

File: Composer/packages/client/src/pages/design/DesignPage.tsx [hunk 3]
```diff
@@ -80,6 +80,13 @@ type BreadcrumbItem = {
   onClick?: () => void;
 };
 
+// field types
+const Types = {
+  Dialog: 'dialog',
+  Trigger: 'trigger',
+  Action: 'action',
+};
+
```
Comment (beyackle) [inline Composer/packages/client/src/pages/design/DesignPage.tsx:89]: See below comment - I'm wondering about changing this slightly so we don't have to worry about that "unsafe regex" linter rule.

File: Composer/packages/client/src/pages/design/DesignPage.tsx [hunk 4]
```diff
@@ -313,17 +320,17 @@ const DesignPage: React.FC<RouteComponentProps<{ dialogId: string; projectId: st
     if (currentDialog.content) {
       setBreadcrumbs((prev) => {
         return prev.map((b) => {
-          const separatorIndex = b.key.indexOf('-');
-          const type = b.key.substr(0, separatorIndex);
-          const name = b.key.substr(separatorIndex + 1);
+          // eslint-disable-next-line security/detect-unsafe-regex
+          const regexp = new RegExp(/(?<type>[a-z]+)-(?<name>.*)/);
+          const { type, name } = b.key.match(regexp)?.groups || {};
```
Comment (beyackle) [inline Composer/packages/client/src/pages/design/DesignPage.tsx:325]: Seeing the linter need to be disabled here made me wonder if there were a simpler way to test this, and I think I have an idea how we could. This is an optional fix, but it will both get rid of the linter and make this a little faster.

Because we control the values of that Types enum and they aren't being exported anywhere, we could make the values a fixed length - say, single letters "D", "T", and "A" for dialog, trigger, and action (so a key would be `D-nameOfDialog`, for example). Then we'll always know the length of the type prefix and won't need any kind of searching or regex matching. The type would always be `b.key.charAt(0)` (or just `b.key[0]`), and the name would be `b.key.substr(2)`.

Comment (alanlong9278) [reply Composer/packages/client/src/pages/design/DesignPage.tsx:325]: Good idea, thanks

**Comment by alanlong9278** [comment]
@beyackle Could u pls merge it if there is no problem? Thanks

**Review by yeze322 — APPROVED** [review]
Confirmed to be working

**Review by yeze322 — DISMISSED** [review]
validated on my local PC

File: Composer/packages/client/src/pages/design/VisualEditorHeader.tsx [hunk 5]
```diff
@@ -40,6 +35,13 @@ type VisualEditorHeaderProps = {
   pluginConfig?: PluginConfig;
 };
 
+// field types
+const Types = {
```
Comment (a-b-r-o-w-n) [inline Composer/packages/client/src/pages/design/VisualEditorHeader.tsx:39]: Let's give this a better name.

File: Composer/packages/client/src/pages/design/VisualEditorHeader.tsx [hunk 6]
```diff
@@ -116,29 +117,35 @@ const useBreadcrumbs = (projectId: string, pluginConfig?: PluginConfig) => {
...
+            b.label = getFriendlyName(get(currentDialog.content, `triggers[${name}]`));
+            break;
+          case Types.Action:
+            b.label = getActionName(get(currentDialog.content, name));
+            break;
+        }
+        return b;
+      });
+    }
+  }, [currentDialog?.content]);
```
Comment (a-b-r-o-w-n) [inline Composer/packages/client/src/pages/design/VisualEditorHeader.tsx:148]: This looks like an anti-pattern. Should `breadcrumbArray` be in state?

File: Composer/packages/client/src/pages/design/VisualEditorHeader.tsx (hunk 5 above)
Comment (yeze322) [reply Composer/packages/client/src/pages/design/VisualEditorHeader.tsx:39]: what about `BreadcrumbKeyPrefix`?

File: Composer/packages/client/src/pages/design/VisualEditorHeader.tsx (hunk 6 above)
Comment (yeze322) [reply Composer/packages/client/src/pages/design/VisualEditorHeader.tsx:148]: @alanlong9278 `useMemo` should work

Comment (alanlong9278) [reply Composer/packages/client/src/pages/design/VisualEditorHeader.tsx]: Use `useMemo`

File: Composer/packages/client/src/pages/design/VisualEditorHeader.tsx (hunk 5 above)
Comment (alanlong9278) [reply Composer/packages/client/src/pages/design/VisualEditorHeader.tsx]: use `BreadcrumbKeyPrefix`

**Comment by yeze322** [comment]
#5427

File: Composer/packages/client/src/pages/design/VisualEditorHeader.tsx [hunk 7]
```diff
@@ -85,10 +86,10 @@ const useBreadcrumbs = (projectId: string, pluginConfig?: PluginConfig) => {
   const focusPath = getFocusPath(selected, focused);
   const trigger = triggerIndex != null && dialogData.triggers[triggerIndex];
 
-  let breadcrumbArray: Array<BreadcrumbItem> = [];
+  const array: Array<BreadcrumbItem> = [];
```
Comment (yeze322) [inline Composer/packages/client/src/pages/design/VisualEditorHeader.tsx:89]: `array` is an ambiguous name! in some programming language it's even a reserved word

File: Composer/packages/client/src/pages/design/VisualEditorHeader.tsx [hunk 8]
```diff
@@ -115,30 +116,37 @@ const useBreadcrumbs = (projectId: string, pluginConfig?: PluginConfig) => {
...
-
-    breadcrumbArray = [...breadcrumbArray.slice(0, 2), { key: 'action-' + actionName, label: actionName }];
-  }
-
+  // get newest label for breadcrumbs
+  const breadcrumbArray = useMemo(() => {
+    if (currentDialog.content) {
+      array.map((b) => {
+        const prefix = b.key.charAt(0);
+        const name = b.key.substr(2);
```
Comment (yeze322) [inline Composer/packages/client/src/pages/design/VisualEditorHeader.tsx:132]: I recommend that defining a pair of functions to parse / build the key, no matter how the key is parsed / built.

```
// Remember to make it typed
const buildKey = () => {};
const parseKey = () => {};
```

**Review by yeze322 — CHANGES_REQUESTED** [review]
Generally good, left two comments.

File: Composer/packages/client/src/pages/design/VisualEditorHeader.tsx (hunk 8 above)
Comment (alanlong9278) [reply Composer/packages/client/src/pages/design/VisualEditorHeader.tsx]: use parse/build key function

**Review by yeze322 — APPROVED** [review]
