### PR TITLE
fix: router cache bug

### LINKED ISSUE #4639: click setting page will show "data loading"
## Describe the bug

Open bot from homepage "history", and then click bot setting. it will show error.
But if you click  each tab in bot setting, it can load appsetting.json correctly.

image

## Version
latest main

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

### PR DESCRIPTION
**Pull request by liweitian**
## Description
bug: router cache saved url with previous projectId
need to clean all router cache data after switching project
## Task Item
Closes #4639 

## Screenshots
aaaa

### CODE REVIEW

**Review by boydc2014 — DISMISSED** [review]

File: Composer/packages/client/src/utils/hooks.ts [hunk 1]
```diff
@@ -50,10 +50,17 @@ export const useLinks = () => {
 };
 
 export const useRouterCache = (to: string) => {
+  const projectId = useRecoilValue(currentProjectIdState);
```
Comment (lei9444) [inline Composer/packages/client/src/utils/hooks.ts:53]: image
currentProjectId looks like the active bot id

**Review by boydc2014 — APPROVED** [review]
