### PR TITLE
fix: Check the name without a number at the beginning when creating a new dialog

### LINKED ISSUE #4246: Dialogs with name starting with numbers cause "extraneous input ‘01’ expecting IDENTIFIER"
## Describe the bug
Using LUIS to extract data from user responses cause "extraneous input ‘01’ expecting IDENTIFIER" in case of Dialog name starting with a number, eg: `01-my-dialog`

## Version

1.1.1-nightly.168593.d361ddb
## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new bot selecting template "Todo with LUIS"
2. Create a new dialog and name it `01-new-dialog`
3. Copy and paste `userprofile` -> `BeginDialog` content into `01-new-dialog` -> `BeginDialog`
4. Add a new trigger to the main dialog: 
  -- name = 01-new-dialog, 
  -- type = Intent recognized
5. Add `Begin a new dialog` action and link to `01-new-dialog`dialog
6. Add any trigger phrase eg: `start dialog`
7. Start bot and open emulator

In the emulator
1. Type `01-new-dialog` trigger phrase
2. Type `my name is anyName`
3. Error: "extraneous input ‘01’ expecting IDENTIFIER"

## Screenshots

Screenshot 2020-09-23 at 19 03 58

Screenshot 2020-09-23 at 19 04 07

Screenshot 2020-09-23 at 18 58 52

### PR DESCRIPTION
**Pull request by lei9444**
## Description
image

## Task Item
closes #4246

### CODE REVIEW

File: Composer/packages/client/src/constants.ts [hunk 1]
```diff
@@ -210,6 +210,8 @@ export const QnABotTemplateId = 'QnASample';
 
 export const nameRegex = /^[a-zA-Z0-9-_]+$/;
 
+export const dialogNameRegex = /^[a-zA-Z][a-zA-Z0-9-_]*$/;
```
Comment (zhixzhan) [inline Composer/packages/client/src/constants.ts:213]: Instead of maintain another regex, can we make `nameRegex` more strict to meet this requirements?

Comment (zhixzhan) [reply Composer/packages/client/src/constants.ts:213]: I remember in server also have a `nameRegex`

**Review by boydc2014 — DISMISSED** [review]

File: Composer/packages/client/src/constants.ts (hunk 1 above)
Comment (lei9444) [reply Composer/packages/client/src/constants.ts]: Thanks @zhixzhan , I moves this to shared, and updated the server check. The nameRegex is also used by intent and trigger. I not sure if we can update the regex.

**Review by boydc2014 — APPROVED** [review]

**Review by cwhitten — APPROVED** [review]
