### PR TITLE
fix: adding fields for runtime language and choice in migrate flow

### LINKED ISSUE #7091: [bot runtime migration] UX should show bot runtime type
- create a bot against legacy bot template 
- open in bot runtime migration branch
- start to convert old bot will hit following 
image

Runtime type should not be empty

### PR DESCRIPTION
**Pull request by pavolum**
## Description

This PR checks if the user is in the migrate flow and conditionally renders the runtime language field if so. This PR also fixes the population of the runtime choice field in the migrate flow

## Task Item

fixes #7091

### CODE REVIEW

**Review by a-b-r-o-w-n — APPROVED** [review]

File: Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx [hunk 1]
```diff
@@ -64,6 +64,11 @@ const stackinput = {
   ],
 };
 
+const RuntimeLanguageOptions: IDropdownOption[] = [
```
Comment (hatpick) [inline Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx:67]: camelCase the name and make it a function, otherwise it wont pick up locale changes for node option

**Review by hatpick — CHANGES_REQUESTED** [review]

File: Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx (hunk 1 above)
Comment (hatpick) [reply Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx:67]: you can also move it inside the component and use useMemo

**Review by benbrown — APPROVED** [review]

File: Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx (hunk 1 above)
Comment (pavolum) [reply Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx]: handled

File: Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx [hunk 2]
```diff
@@ -122,6 +127,7 @@ const DefineConversationV2: React.FC<DefineConversationProps> = (props) => {
       return t.id === templateId;
     }
   });
+  const inBotMigration = props?.path?.indexOf('migrate') !== -1;
```
[the remark this answers is not in the document]
Comment (pavolum) [reply Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx]: Handled
