### PR TITLE
fix: Webchat Inspector behavior

### LINKED ISSUE #6249: Webchat Inspector behavior improvements
On a new error in the conversation between user and bot through the Webchat Inspector. The following needs to happen

- A red indicator appears on the tab header
- Webchat Inspector Panel opens with Web Chat tab selected
- Content always scrolls when a new  item comes in otherwise the scroll position holds
- When the Webchat Inspector tab is active the Red indicator disappears.
@garypretty @mewa1024

### PR DESCRIPTION
**Pull request by srinaath**
## Description

1.  Webchat Inspector tab behavior
2.  Automatically open the start bot controller when a bot fails to start (regression error)

This fix does break accessibility by switching tab to Webchat inspector and auto scrolls to the new issue. We are going to rectify this behavior with a more elegant solution in R13.

@garypretty @mewa1024

## Task Item

Fixes #6249 #6215 #6133

## Screenshots

error-viewer

### CODE REVIEW

File: Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebchatLog/WebchatLogContent.tsx [hunk 1]
```diff
@@ -3,23 +3,64 @@
...
+  const webChatContainerRef = useRef<HTMLDivElement | null>(null);
+
+  const webChatItems = useMemo(() => {
+    const updatedItems = displayedLogs.map((log, idx) => <WebchatLogItem key={`webchatLog-${idx}`} item={log} />);
+    setLogItemCount(displayedLogs.length);
+    return updatedItems;
+  }, [displayedLogs]);
+
+  const navigateToNewestLogEntry = () => {
+    if (currentLogItemCount && webChatContainerRef?.current) {
```
Comment (hatpick) [inline Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebchatLog/WebchatLogContent.tsx:30]: webChatContainerRef always has value, webChatContainerRef.current can be null.

File: Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebchatLog/WebchatLogContent.tsx [hunk 2]
```diff
@@ -3,23 +3,64 @@
...
+    }
+  }, [isActive]);
+
+  useEffect(() => {
+    if (isActive) {
+      navigateToNewestLogEntry();
+    } else {
+      navigateToLatestEntryWhenActive(true);
+    }
+  }, [currentLogItemCount]);
```
Comment (hatpick) [inline Composer/packages/client/src/pages/design/DebugPanel/TabExtensions/WebchatLog/WebchatLogContent.tsx:49]: add isActive to dependency? why currentLogItemCount a dependency?

**Review by cwhitten — DISMISSED** [review]
