### PR TITLE
fix: refine the error message when the bot is deleted

### LINKED ISSUE #3671: Error message in modal after project deletion
## Describe the bug

If a directory containing a project is deleted and the project is edited afterward, an unclear error message can appear:

```
project 68384.6497895014 not found in cache
```

## Version

1.0.2

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a project
2. Remove the folder from the filesystem
3. Perform some change to the project
4. See modal with unclear error message

### PR DESCRIPTION
**Pull request by lei9444**
## Description
refine the message to "path" doesn't seems to be exists anymore.

Kapture 2021-02-03 at 01 34 44

## Task Item
closes #3671

### CODE REVIEW

File: Composer/packages/server/src/services/project.ts [hunk 1]
```diff
@@ -254,7 +254,7 @@ export class BotProjectService {
       if (!(await StorageService.checkBlob('default', path, user))) {
         BotProjectService.deleteRecentProject(path);
         BotProjectService.removeProjectIdFromCache(projectId);
-        throw new Error(`file ${path} does not exist`);
+        throw new Error(`${path} doesn't seems to be exists anymore`);
```
Comment (cwhitten) [inline Composer/packages/server/src/services/project.ts:257]: Can you make this string: 

`${path} doesn't seem to be exist any longer`

File: Composer/packages/server/src/services/project.ts [hunk 2]
```diff
@@ -304,7 +304,7 @@ export class BotProjectService {
         if (!(await StorageService.checkBlob('default', path, user))) {
           BotProjectService.deleteRecentProject(path);
           BotProjectService.removeProjectIdFromCache(matchingProjectId);
-          throw new Error(`file ${path} does not exist`);
+          throw new Error(`${path} doesn't seems to be exists anymore`);
```
Comment (cwhitten) [inline Composer/packages/server/src/services/project.ts:307]: Can you make this string: 

`${path} doesn't seem to be exist any longer`

**Review by cwhitten — APPROVED** [review]
