### PR TITLE
fix: Updated release version on about page

### LINKED ISSUE #1773: Preview 2 still says 'Preview 1.0' in the About page
Using the latest stable branch for Composer and visiting the About page in the app, the version number still says 'Preview 1.0'.

### PR DESCRIPTION
**Pull request by tdurnford**
## Description
Added COMPOSER_VERSION to env variables

## Task Item
Closes #1773 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have functionally tested my change

## Screenshots

image

### CODE REVIEW

File: Composer/packages/client/config/env.js [hunk 1]
```diff
@@ -89,7 +89,8 @@ function getClientEnvironment(publicUrl) {
         GIT_SHA: getGitSha()
           .toString()
           .replace('\n', ''),
-        SDK_PACKAGE_VERSON: '4.6.0-preview2', // TODO: change this when Composer supports custom schema/custom runtime
+        SDK_PACKAGE_VERSION: '4.6.0-preview2', // TODO: change this when Composer supports custom schema/custom runtime
```
Comment (cwhitten) [inline Composer/packages/client/config/env.js]: can you update this to `4.7.0-preview-191208-1` please? We merged updated packages last night into `master`.
