### PR TITLE
fix: only support en-us on qna for tmp use

### LINKED ISSUE #5004: [MCS-DE-GO] Dialog creation error in qna-filename when language is not "en-us"
When selecting a Bot with a default language (set as only language) which is not "en-us", the .qna-Files are still created with the "en-us"-extension which causes Composer to produce an error that it could not find the .qna-File.

@joaollq @goergenj @sgellock @benbrown @Bindsi @cwhitten

### PR DESCRIPTION
**Pull request by liweitian**
## Description
QnA only support en-us at this moment. It causes some bugs when we have multi-locale.

## Task Item
Closes #5004

### CODE REVIEW

**Comment by liweitian** [comment]
@luhan2017 Could you help checking this PR?

**Review by luhan2017 — APPROVED** [review]

File: Composer/packages/client/src/recoilModel/dispatchers/qna.ts [hunk 1]
```diff
@@ -50,7 +50,9 @@ export const createQnAFileState = async (
 ) => {
   const { set, snapshot } = callbackHelpers;
   const qnaFiles = await snapshot.getPromise(qnaFilesState(projectId));
-  const locale = await snapshot.getPromise(localeState(projectId));
+  //const locale = await snapshot.getPromise(localeState(projectId));
+  //To do: support other languages
+  const locale = 'en-us';
```
Comment (zhixzhan) [inline Composer/packages/client/src/recoilModel/dispatchers/qna.ts:55]: For other methods in this dispatcher should also use fixed locale en-us.
`removeQnAFileState`
`renameKBFileState`
`updateQnAFileState`

**Review by zhixzhan — CHANGES_REQUESTED** [review]

File: Composer/packages/client/src/recoilModel/dispatchers/qna.ts (hunk 1 above)
Comment (liweitian) [reply Composer/packages/client/src/recoilModel/dispatchers/qna.ts:56]: solved. And it seems createQnAKBFromScratch and createQnAKBFromUrl should use fixed locale en-us
