### PR TITLE
fix: undo/redo

### LINKED ISSUE #4620: Undo/Redo
## Describe the bug

Undo/ Redo is broken

1. Undo/Redo needs to handle the new encoded paths in url
2. Undo/Redo commits changes before the selector value is updated
3. Undo/Redo needs to be supported for skills

### PR DESCRIPTION
**Pull request by lei9444**
## Description
1. move unchange commit to lg inline Editor
2. update the navigate url with new encoded paths
3. add design page location to the snapshot
4. add selector for canUndo and canRedo

This PR is based on #4604, please merge #4604 first.

## Task Item
closes #4620

### CODE REVIEW

File: Composer/packages/client/src/recoilModel/undo/history.ts [hunk 1]
```diff
@@ -33,6 +35,15 @@ export const undoFunctionState = atomFamily<IUndoRedo, string>({
   dangerouslyAllowMutability: true,
 });
 
+export const undoStatusState = atomFamily<{ canUndo: boolean; canRedo: boolean }, string>({
+  key: 'undoStatus',
+  default: {
+    canRedo: false,
```
Comment (srinaath) [inline Composer/packages/client/src/recoilModel/undo/history.ts:41]: Can we just create two botstate  canUndo and canRedo. The dangerouslyAllowMutability seems risky for changes that a component is subscribing to. If we move it to botstates, history.ts  can just set it and other components can subscribe to it

**Review by srinaath — CHANGES_REQUESTED** [review]

**Review by srinaath — DISMISSED** [review]

**Review by srinaath — APPROVED** [review]
