### PR TITLE
fix: redesign get started widget to solve some ux problems

### LINKED ISSUE #6064: bug: long path can break its container on get started widget
## Describe the bug

Screen Shot 2021-03-01 at 4 03 48 PM

### LINKED ISSUE #6085: On smaller resolution screens the Getting Started Experience takes most of the Canvas
## Describe the bug

When using a screen size like 1080p you will be presented the Getting Started on the Bot Settings page.  There is no way to collapse and/or scroll the area that has bot info / Next steps / Guides and References. making a very small area to perform bot settings.  It should either be collapsible by the user and/or scrollable to allow for better use of the screen.

## Version

image

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [X] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Open a Bot Project
2. Go to the Bot Settings page (Issue)

## Expected behavior

Should have the area below the action menu to scroll and possibly allow the collapse of the bot info and getting started section.

## Screenshots

image

### LINKED ISSUE #6115: Getting Started Action Bar Disappears
## Describe the bug

When you go to add the publishing profile and you are redirected to the Bot Settings page, the Action Bar for Getting Started disappears. 

## Version

image

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Open a Bot Project
2. Click on Publish on Left Navigation
3. In drop down list under Publish Target select manage profiles

## Expected behavior

I expect that you are taken to the right place in the Bot Settings, however the Action Bar should not disappear.

## Screenshots

image

### LINKED ISSUE #6116: Manage Connections button does nothing
## Describe the bug

When you click the Manage Connections button on the Action Bar in Getting Started experience, nothing happens.

## Version

image

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to Bot Settings Page
2. Click on Manage Connections and nothing happens

## Expected behavior

I should be taken to the place in bot settings to add adapters and channels

## Screenshots

image

### PR DESCRIPTION
**Pull request by benbrown**
## Description

This is a redesign of the get started widget that appears at the end of the new creation flow.

Instead of a large always visible area, the actions and follow-up content are now in a slide out.

There is also now a teaching bubble that will appear at the end of creation to highlight this content.

## Task Item

Fixes #6115 
Fixes #6085 
Fixes #6116 
Fixes #6064 

## Screenshots

TJbKlvHVR3

# Also includes

#6088
#6118

### CODE REVIEW

File: Composer/packages/client/src/components/GetStarted/GetStarted.tsx [hunk 1]
```diff
@@ -3,22 +3,22 @@
...
 import TelemetryClient from '../../telemetry/TelemetryClient';
-import { navigateTo } from '../../utils/navigation';
 
-import { wrapperStyle, buttonStyles, h2Style, h3Style, ulStyle, ulStyleGuides, linkStyle, liStyle } from './styles';
+import { h2Style, h3Style, ulStyle, ulStyleGuides, linkStyle, liStyle } from './styles';
 
 type GetStartedProps = {
-  toolbarItems?: IToolbarItem[];
+  isOpen: boolean;
+  onDismiss: any;
```
Comment (hatpick) [inline Composer/packages/client/src/components/GetStarted/GetStarted.tsx:21]: () => void instead of any 😃

File: Composer/packages/client/src/components/GetStarted/GetStarted.tsx [hunk 2]
```diff
@@ -46,129 +45,69 @@ export const GetStarted: React.FC<GetStartedProps> = (props) => {
...
-                <li style={liStyle}>
-                  <Link href={linkToPublish} styles={linkStyle} onClick={linkClick}>
-                    {formatMessage('Publish updates to the cloud')}
-                  </Link>
-                </li>
-              </ul>
-            </Stack.Item>
-          </Stack>
+          {formatMessage('Customize')}
+          <ul style={ulStyle}>
```
Comment (hatpick) [inline Composer/packages/client/src/components/GetStarted/GetStarted.tsx:74]: nit: I suggest putting all your urls and their texts in an array:
```
const data = React.useMemo(() => [{url: ..., text: formatMessage(...)}, ...], []);
...
...
data.map(item => <li style={liStyle}><Link href={item.url} ...>{item.text}</Link></li>
```
so you dont repeat yourself.

File: Composer/packages/client/src/components/GetStarted/GetStartedToolbar.tsx [hunk 3]
```diff
@@ -0,0 +1,67 @@
+// Copyright (c) Microsoft Corporation.
+// Licensed under the MIT License.
+
+/** @jsx jsx */
+import { jsx } from '@emotion/core';
+const items: IToolbarItem[] = [
```
Comment (hatpick) [inline Composer/packages/client/src/components/GetStarted/GetStartedToolbar.tsx]: convert this to a function so those formatMessages get executed in the context of a component for them to get picked up by localization.

getToolbarItems = () => items

File: Composer/packages/client/src/components/GetStarted/styles.ts [hunk 4]
```diff
@@ -2,11 +2,11 @@
 // Licensed under the MIT License.
 import { FontSizes } from '@uifabric/fluent-theme';
 export const linkStyle = {
-  root: { color: '#56CCF2', selectors: { ':hover': { color: '#56CCF2' } } },
+  // root: { color: '#56CCF2', selectors: { ':hover': { color: '#56CCF2' } } },
```
Comment (hatpick) [inline Composer/packages/client/src/components/GetStarted/styles.ts:5]: remove commented

**Comment by benbrown** [comment]
Screen Shot 2021-03-03 at 1 28 11 PM
Screen Shot 2021-03-03 at 1 28 05 PM

File: Composer/packages/client/src/components/GetStarted/GetStartedToolbar.tsx (hunk 3 above)
Comment (benbrown) [reply Composer/packages/client/src/components/GetStarted/GetStartedToolbar.tsx]: this file was removed

File: Composer/packages/client/src/components/GetStarted/styles.ts (hunk 4 above)
Comment (benbrown) [reply Composer/packages/client/src/components/GetStarted/styles.ts:5]: cleaned up

**Comment by Dewain27** [comment]
@emivers8  and I agree on this wording:
image

File: Composer/packages/client/src/components/GetStarted/GetStarted.tsx (hunk 2 above)
Comment (benbrown) [reply Composer/packages/client/src/components/GetStarted/GetStarted.tsx:74]: The form and format of these are rapidly changign right now. I'll come back and optimize the handling of this content later.

**Review by hatpick — APPROVED** [review]

**Review by cwhitten — APPROVED** [review]
