### PR TITLE
fix: Updated skill manifest schema version

### LINKED ISSUE #4696: Update skills manifest versions
## Describe the bug

image

`"$schema": "https://schemas.botframework.com/schemas/skills/skill-manifest-2.1.preview-1.json"`
should be replaced with 
`$schema": https://schemas.botframework.com/schemas/skills/v2.1/skill-manifest.json`

## Version

[v1.1.1-nightly.182095.d5b2950](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.182095.d5b2950)

## Browser

- [x] Electron distribution

## OS

- [x] Windows

## Expected behavior

Should use [v2.1](https://github.com/microsoft/botframework-sdk/tree/main/schemas/skills/v2.1).

### PR DESCRIPTION
**Pull request by tdurnford**
## Description
Updated skill manifest schemas to include v2.1.

## Task Item
Closes #4696

## Screenshots
image

image

### CODE REVIEW

File: Composer/packages/client/src/pages/design/exportSkillModal/constants.tsx [hunk 1]
```diff
@@ -21,10 +21,10 @@ import {
   SelectTriggers,
 } from './content';
 
-export const VERSION_REGEX = /\d\.\d\.(\d+|preview-\d+)/i;
+export const VERSION_REGEX = /\d\.\d(\.\d+|preview-\d+)|\d\.\d/i;
```
Comment (beyackle) [inline Composer/packages/client/src/pages/design/exportSkillModal/constants.tsx:24]: This needs a tweak to handle version strings like "1.10" (put a `+` after the second `d` and that should work).

**Review by beyackle — CHANGES_REQUESTED** [review]
Looks mostly good, just needs a small tweak.

File: Composer/packages/client/src/pages/design/exportSkillModal/constants.tsx (hunk 1 above)
Comment (tdurnford) [reply Composer/packages/client/src/pages/design/exportSkillModal/constants.tsx:24]: Good call

**Review by beyackle — APPROVED** [review]
