### PR TITLE
fix: export bot include v2 project structure files

### LINKED ISSUE #7231: Export fails: .csproj is missing from destination
## Repro
1. Create a bot project (in my case with qna/luis/remote-skill)
2. Export
3. Extract .zip
4. Restart Composer
5. Navigate to new location
6. Try to build
7. Error: No .csproj: ```Command failed : The project file '...\OrchestratorDispatch\OrchestratorDispatch.csproj'  does not exist.```

## Build Error
```
Error occurred building the bot

Message:
Command failed: dotnet user-secrets init --project OrchestratorDispatch.csproj
Command failed : The project file 'c:\workspace\botroot\sdk\Orchestrator\Samples\Composer\OrchestratorDispatch\OrchestratorDispatch.csproj' does not exist.
Command:
dotnet user-secrets init --project OrchestratorDispatch.csproj
Stack Trace:
Error: Command failed: dotnet user-secrets init --project OrchestratorDispatch.csproj
Command failed : The project file 'c:\workspace\botroot\sdk\Orchestrator\Samples\Composer\OrchestratorDispatch\OrchestratorDispatch.csproj' does not exist.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
Output:
System.IO.FileNotFoundException: The project file 'c:\workspace\botroot\sdk\Orchestrator\Samples\Composer\OrchestratorDispatch\OrchestratorDispatch.csproj' does not exist.
   at Microsoft.Extensions.SecretManager.Tools.Internal.MsBuildProjectFinder.FindMsBuildProject(String project)
   at Microsoft.Extensions.SecretManager.Tools.Internal.InitCommand.ResolveProjectPath(String name, String path)
   at Microsoft.Extensions.SecretManager.Tools.Internal.InitCommand.Execute(CommandContext context)
   at Microsoft.Extensions.SecretManager.Tools.Internal.InitCommand.Execute(CommandContext context, String workingDirectory)
   at Microsoft.Extensions.SecretManager.Tools.Internal.InitCommandFactory.Execute(CommandContext context, String workingDirectory)
   at Microsoft.Extensions.SecretManager.Tools.Program.RunInternal(String[] args)
   at Microsoft.Extensions.SecretManager.Tools.Program.TryRun(String[] args, Int32& returnCode)
Killed:
Code:
1
Stderr:
Command failed : The project file 'c:\workspace\botroot\sdk\Orchestrator\Samples\Composer\OrchestratorDispatc
```

### PR DESCRIPTION
**Pull request by zhixzhan**
## Description
Fix export bot include v2 project structure files.

Note:
After download, to run the exported bot, the bot root folder name should be rename  to correct bot name.

image

## Task Item
close #7231

### CODE REVIEW

**Comment by cwhitten** [comment]
@zhixzhan we need to consider the JS runtime export as well. Can you make sure to include this? Sans node_modules

**Comment by zhixzhan** [comment]
> @zhixzhan we need to consider the JS runtime export as well. Can you make sure to include this? Without node_modules

@cwhitten updated. I have tested both JS & C# runtime bot, files are all included.

File: Composer/packages/server/src/models/storage/localDiskStorage.ts [hunk 1]
```diff
@@ -162,22 +162,39 @@ export class LocalDiskStorage implements IFileStorage {
...
+      '/form-dialogs/',
       '/knowledge-base/',
+      '/language-generation/',
+      '/language-understanding/',
+      '/media/',
+      '/Properties/',
       '/recognizers/',
-      '/form-dialogs/',
+      '/schemas/',
       '/scripts/',
```
Comment (hatpick) [inline Composer/packages/server/src/models/storage/localDiskStorage.ts:175]: on my mac it's ```Scripts```, are these case-sensitive? (asking since you have ```Controllers```)

File: Composer/packages/server/src/models/storage/localDiskStorage.ts [hunk 2]
```diff
@@ -162,22 +162,39 @@ export class LocalDiskStorage implements IFileStorage {
...
     const directoriesToInclude = defaultDirectories.filter((elem) => {
       return exclusions?.directories == undefined || exclusions?.directories?.indexOf(elem) == -1;
     });
 
-    const defaultFiles = [`*${FileExtensions.BotProject}`, `*${FileExtensions.Dialog}`, 'README.md', '.gitignore'];
+    const defaultFiles = [
+      `*${FileExtensions.BotProject}`,
+      `*${FileExtensions.Dialog}`,
+      `*.csproj`,
+      `*.botproj`,
```
Comment (hatpick) [inline Composer/packages/server/src/models/storage/localDiskStorage.ts:189]: duplicate? (```*${FileExtensions.BotProject}```)

File: Composer/packages/server/src/models/storage/localDiskStorage.ts (hunk 1 above)
Comment (zhixzhan) [reply Composer/packages/server/src/models/storage/localDiskStorage.ts:175]: The glob pattern we used is case-insensitive. I noticed some of the template bots is `Scripts` and some is `scripts`. maybe need align them in bot templates side;

File: Composer/packages/server/src/models/storage/localDiskStorage.ts (hunk 2 above)
Comment (zhixzhan) [reply Composer/packages/server/src/models/storage/localDiskStorage.ts]: thanks, removed

**Review by cwhitten — APPROVED** [review]
