### PR TITLE
fix: lu/lg editor update strategy

### LINKED ISSUE #2982: LUIS trigger phrases fail to show in the inline editor after trigger creation
Describe the bug
I selected LUIS as a recognizer type and created an Intent Recognized trigger. 
I enter the intent name and trigger phrases in the **Create a trigger** window, but after submit, the data is now shown on the Properties panel. 
Note: the data can be published to LUIS. It's just that they are not shown in the inline lu editor as they are supposed to. 

## Version
Latest master branch.

## Browser
- [x] Chrome

## OS
- [x] Windows

## To Reproduce

1. Select LUIS as a recognizer type
2. Select **+ Add** then **+ Add new trigger** in the toolbar to create an Intent Recognized trigger. 
3. Enter the intent name and trigger phrases, select **Submit**.
4. After creation, in the **Properties** panel on the right side, you cannot see the trigger phrases you created. The lu editor is empty. 

## Expected behavior
Should be able to show the trigger phrases in inline lu editor after creating the intent recognized trigger.

## Screenshots
* Create Intent Recognzied trigger with trigger phrases. 
image

* After creation, the inline lu editor was empty. 
image

* Was able to publish the training data to LUIS. 
image

### PR DESCRIPTION
**Pull request by zhixzhan**
## Description

Removed form-editor previous maintained localValue( for performance consideration ), let `BaseEditor` handle it, it would check `id` to see need update from external value or not. 

Because of no `localValue` anymore, we also don't need `sync` method.

## Task Item

close #2982 
refs #2627 
refs #2904 

## Screenshots
Untitled1

### CODE REVIEW

File: Composer/packages/ui-plugins/luis/src/LuisIntentEditor.tsx [hunk 1]
```diff
@@ -20,13 +20,12 @@ const LuisIntentEditor: React.FC<FieldProps<string>> = props => {
...
     (luFile && luFile.intents.find(intent => intent.Name === intentName)) ||
-      ({
-        Name: intentName,
-        Body: '',
-      } as LuIntentSection)
-  );
+    ({
+      Name: intentName,
+      Body: '',
+    } as LuIntentSection);
```
Comment (a-b-r-o-w-n) [inline Composer/packages/ui-plugins/luis/src/LuisIntentEditor.tsx:28]: How does this perform in a large bot with many intents?
