### PR TITLE
fix: Moved field descriptions into tooltip

### LINKED ISSUE #1830: Some tooltips are written inline
Some of the tooltips in the property editor are written inline instead of being wrapped in tooltip bubbles.

- Dialog | Language Understanding
- Begin a new dialog | Options
- Cancel all dialogs | Event value
- Replace this dialog | Options
- Repeat this dialog | Options
- Send an HTTP request | Body, Headers
- Connect to QnA Knowledgebase | Strict Filters

### PR DESCRIPTION
**Pull request by tdurnford**
## Description
Some descriptions in the form editor were written inline instead of being contained in a description callout. Updated the `BaseField` component to use the `WidgetLabel` to resolve the issue.

## Task Item
Closes #1830 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have functionally tested my change

### Before 
image

### After
image

### CODE REVIEW

File: Composer/packages/extensions/obiformeditor/src/Form/fields/BaseField.tsx [hunk 1]
```diff
@@ -75,23 +76,13 @@ export function BaseField<T = any>(props: BaseFieldProps<T>): JSX.Element {
...
-              )}
-            </p>
-          )}
-        </div>
+        <WidgetLabel
+          label={getTitle()}
+          description={getDescription()}
+          helpLink={helpLink}
+          helpLinkText={helpLinkText}
+          {...props.schema}
```
Comment (a-b-r-o-w-n) [inline Composer/packages/extensions/obiformeditor/src/Form/fields/BaseField.tsx]: Is this necessary?

Comment (tdurnford) [reply Composer/packages/extensions/obiformeditor/src/Form/fields/BaseField.tsx]: nope
