### PR TITLE
fix: when add remote skill show manifest json parse error

### LINKED ISSUE #6899: Localhost skill manifest is inaccessible in composer but it is in browser
While developing a skill we need to access a localhost skill manifest. See below how skill manifest is available in browser but inaccessible in Composer.

skillmanifest

### PR DESCRIPTION
**Pull request by zhixzhan**
## Description
when add remote skill show manifest json parse error

## Task Item
close #6899 

## Screenshots
image

### CODE REVIEW

**Review by boydc2014 — APPROVED** [review]

File: Composer/packages/client/src/components/AddRemoteSkillModal/CreateSkillModal.tsx [hunk 1]
```diff
@@ -63,7 +63,12 @@ export const getSkillManifest = async (projectId: string, manifestUrl: string, s
     });
     setSkillManifest(data);
   } catch (error) {
-    setFormDataErrors({ ...error, manifestUrl: formatMessage('Manifest URL can not be accessed') });
+    const httpMessage = error?.response?.data?.message;
+    const message = httpMessage?.match('Unexpected string in JSON')
+      ? formatMessage("Error attempting to parse Skill manifest. There could be an error in it's format.")
+      : formatMessage('Manifest URL can not be accessed');
```
Comment (zhixzhan) [inline Composer/packages/client/src/components/AddRemoteSkillModal/CreateSkillModal.tsx:69]: Hi @cwhitten , I made some update base on your change here . Is this your intention?

Comment (cwhitten) [reply Composer/packages/client/src/components/AddRemoteSkillModal/CreateSkillModal.tsx:69]: Yes thank you @zhixzhan !
