### PR TITLE
fix: Added copy from profile button and dialog

### LINKED ISSUE #7206: Provisioning App Registration for a Root Bot doesn't set the AppId/Password in local appsettings
## Describe the bug

There are a number of scenarios where an AppId/Secret is required in order for certain features to work, remote skills is one as this is used for the S2S authentication.

When connecting a Root Bot to a remote skill, I chose to provision an App Registration which completed successfully.  However the generated AppId and Secret were not applied to my local bot configuration meaning that when starting the bot and trying to use remote skills they didn't work.

At this point the user doesn't have easy access to go find the AppId/secret unless they:
- go to the azure portal
- go to active directory
- go to app registrations
- search for the name of their created app
- go into secrets
- generate a new secret (can't see the password for something newly created)
- copy/paste into local bot settings along with AppId (there are a few Ids so confusion happens)

## Version

1.4.0-nightly.237504

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new Empty Bot
2. Connect a remote skill: https://djtest6.azurewebsites.net/manifests/djbfskill1-2-1-manifest.json
3. Observe 401 error (no AppId/Secret)
4. Provision azure resources including app registration
5. start bot, same 401 error

## Expected behavior

The AppId and Secret to be applied to my local configuration so this scenario works. Or at the very least if we are concerned about side-affecting a users configuration provide an option after provisioning to apply these resources to my local configuration.

## Additional context

The same issue exists for telemetry, I can go ahead and provision AppInsights, launch my bot and can't run queries/analysis against telemetry as a developer which itself is a key problem. The same expected behaviour above should be used for this.

### PR DESCRIPTION
**Pull request by GeoffCoxMSFT**
## Description

Added the button to copy app ID and password from profile per the design in the linked issue.

## Task Item

fixes #7206

## Screenshots

image

image

image

image

### CODE REVIEW

File: Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx [hunk 1]
```diff
@@ -0,0 +1,125 @@
...
+  const [selectedKey, setSelectedKey] = useState<string | number | undefined>();
+
+  const dialogTitle = {
+    title: formatMessage('Add from publishing profile'),
+    subText: formatMessage('Select the publishing profile you’d like to add a Microsoft App ID and Secret from.'),
+  };
+
+  const getAppInfo = (profile: PublishTarget) => {
+    if (profile) {
+      const config = JSON.parse(profile.configuration);
```
Comment (benbrown) [inline Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx:42]: might want to try/catch this parse just in case?

**Review by benbrown — APPROVED** [review]

File: Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx (hunk 1 above)
Comment (GeoffCoxMSFT) [reply Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx:42]: I could but I don't know what to do with the error.  The provisioning wizard shouldn't be writing unparsable stuff to the settings file. Plus this was partially parsed by the profile loading when the bot was opened.

**Comment by GeoffCoxMSFT** [comment]
Note about the screenshots - Based on reviewing with Em, I've updated to use password instead of secret since that is the consistent term.

File: Composer/packages/client/src/pages/botProject/AppIdAndPassword.tsx [hunk 2]
```diff
@@ -107,7 +111,11 @@ export const AppIdAndPassword: React.FC<AppIdAndPasswordProps> = (props) => {
       <div css={title}>{formatMessage('Microsoft App ID')}</div>
       <div css={subtext}>
         {formatMessage.rich(
-          'A Microsoft App ID is required for your local Azure resources. If you’ve created an App ID already, you can add here. If not, your App ID and secret will be created when you provision resources for this bot. <a>Learn more.</a>',
+          'A Microsoft App ID is required for your local Azure resources.' +
```
Comment (hatpick) [inline Composer/packages/client/src/pages/botProject/AppIdAndPassword.tsx:114]: use backtick ``

File: Composer/packages/client/src/pages/botProject/AppIdAndPassword.tsx [hunk 3]
```diff
@@ -140,7 +148,34 @@ export const AppIdAndPassword: React.FC<AppIdAndPasswordProps> = (props) => {
           onChange={handleAppPasswordOnChange}
           onRenderLabel={onRenderLabel}
         />
+        <PrimaryButton
+          disabled={false}
```
Comment (hatpick) [inline Composer/packages/client/src/pages/botProject/AppIdAndPassword.tsx:152]: why?

File: Composer/packages/client/src/pages/botProject/AppIdAndPassword.tsx [hunk 4]
```diff
@@ -140,7 +148,34 @@ export const AppIdAndPassword: React.FC<AppIdAndPasswordProps> = (props) => {
...
+          styles={{ root: { width: '230px', marginTop: '15px' } }}
+          text={formatMessage('Add from publishing profile')}
+          onClick={() => {
+            setShowImportDialog(true);
+          }}
+        />
       </div>
+      {showImportDialog && (
```
Comment (hatpick) [inline Composer/packages/client/src/pages/botProject/AppIdAndPassword.tsx:160]: this and hidden are redundant, first one is enough imo

File: Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx [hunk 5]
```diff
@@ -0,0 +1,125 @@
...
+    subText: formatMessage('Select the publishing profile you’d like to add a Microsoft App ID and Password from.'),
+  };
+
+  const getAppInfo = (profile: PublishTarget) => {
+    if (profile) {
+      const config = JSON.parse(profile.configuration);
+      const appId = config?.settings?.MicrosoftAppId;
+      const appPassword = config?.settings?.MicrosoftAppPassword;
+
+      if (appId) {
```
Comment (hatpick) [inline Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx:46]: why this check on appId only

File: Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx [hunk 6]
```diff
@@ -0,0 +1,125 @@
...
+  projectId: string;
+  hidden?: boolean;
+  onOK: (info: AppInfo) => void;
+  onCancel: () => void;
+};
+
+export const GetAppInfoFromPublishProfileDialog: React.FC<Props> = (props) => {
+  const { projectId, hidden, onOK: onAdd, onCancel } = props;
+  const { publishTargets } = useRecoilValue(settingsState(projectId));
+  const [publishTargetOptions, setPublishTargetOptions] = useState<IDropdownOption[]>([]);
```
Comment (hatpick) [inline Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx:31]: why is this a state? it can simple be a variable with useMemo

File: Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx [hunk 7]
```diff
@@ -0,0 +1,125 @@
...
+        ?.map((p) => {
+          return { key: p.name, text: p.name, data: getAppInfo(p) };
+        })
+        .filter((p) => p.data !== undefined) || [];
+
+    setPublishTargetOptions(options);
+  }, [publishTargets, projectId]);
+
+  useEffect(() => {
+    if (publishTargetOptions.length === 0) {
```
Comment (hatpick) [inline Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx:68]: this can be a memo from the other memo I mentioned above

File: Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx [hunk 8]
```diff
@@ -0,0 +1,125 @@
...
+        <DialogFooter>
+          <PrimaryButton
+            disabled={!!publishTargetsErrorMessage || !selectedKey}
+            text={formatMessage('Add App ID and Password')}
+            onClick={handleAdd}
+          />
+          <DefaultButton text={formatMessage('Cancel')} onClick={onCancel} />
+        </DialogFooter>
+      </Dialog>
+    </Fragment>
```
Comment (hatpick) [inline Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx:120]: fragment not required

File: Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx [hunk 9]
```diff
@@ -0,0 +1,125 @@
...
+  );
+};
+
+//onChange={onSelectProfile}
```
Comment (hatpick) [inline Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx:124]: remove

File: Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx [hunk 10]
```diff
@@ -0,0 +1,125 @@
...
+import { settingsState } from '../../recoilModel/atoms/botState';
+
+type AppInfo = {
+  appId: string;
+  appPassword?: string;
+};
+
+type Props = {
+  projectId: string;
+  hidden?: boolean;
```
Comment (hatpick) [inline Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx:23]: is it needed?

File: Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx (hunk 1 above)
Comment (hatpick) [reply Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx:42]: no try and catch = app crash probably

File: Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx [hunk 11]
```diff
@@ -0,0 +1,125 @@
...
+    // generate options
+    const options: IDropdownOption[] =
+      publishTargets
+        ?.map((p) => {
+          return { key: p.name, text: p.name, data: getAppInfo(p) };
+        })
+        .filter((p) => p.data !== undefined) || [];
+
+    setPublishTargetOptions(options);
+  }, [publishTargets, projectId]);
```
Comment (hatpick) [inline Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx:65]: project id is not needed

File: Composer/packages/client/src/pages/botProject/AppIdAndPassword.tsx (hunk 2 above)
Comment (GeoffCoxMSFT) [reply Composer/packages/client/src/pages/botProject/AppIdAndPassword.tsx]: For line continuation or for string templating?  (formatMessage.rich can take a regular string).  I moved it to be a single line.

File: Composer/packages/client/src/pages/botProject/AppIdAndPassword.tsx (hunk 4 above)
Comment (GeoffCoxMSFT) [reply Composer/packages/client/src/pages/botProject/AppIdAndPassword.tsx:155]: I wish - the way the hidden state works within the fragment containing the dialog needs to reset its state otherwise the dialog will never open again.

File: Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx (hunk 5 above)
Comment (GeoffCoxMSFT) [reply Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx:46]: It may be that with the new integration security model that the password is empty in the future.  If it has an app ID that is enough to have it in the list.

File: Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx (hunk 10 above)
Comment (GeoffCoxMSFT) [reply Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx:23]: What is it? Do you mean should hidden be required?

File: Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx (hunk 6 above)
Comment (GeoffCoxMSFT) [reply Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx:31]: something borrowed, something blue.

File: Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx (hunk 10 above)
Comment (hatpick) [reply Composer/packages/client/src/pages/botProject/GetAppInfoFromPublishProfileDialog.tsx:23]: the dialog is rendered conditionally, controlling hidden from outside almost never happens, so it's not needed.

**Review by hatpick — APPROVED** [review]
