### PR TITLE
fix: one lg template error mess up others

### LINKED ISSUE #1732: lg template error cannot parse
## Describe the bug
Error in one LG template  mess up all template the the related filed in visual editor become blank

## Version
What version of the Composer are you using? Paste the build SHA found on the about page (`/about`).

## Browser
What browser are you using?

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Screenshots
If applicable, add screenshots/gif/video to help explain your problem.
image

### PR DESCRIPTION
**Pull request by zhixzhan**
## Description

Greed try parse lgFile, fix one lg template error cause others blank field

If this is a bug fix, please describe the root cause and analysis of this problem.

## Task Item

Fix #1732 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code refactor (non-breaking change which improve code quality, clean up, add tests, etc)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Doc update (document update)

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have functionally tested my change

## Screenshots

Please include screenshots or gifs if your PR include UX changes.
image

### CODE REVIEW

File: Composer/packages/lib/indexers/src/lgIndexer.ts [hunk 1]
```diff
@@ -58,14 +58,11 @@ function index(files: FileInfo[]): LgFile[] {
       const id = getBaseName(name, '.lg');
       const diagnostics = check(content, id);
       let templates: LgTemplate[] = [];
-      if (isValid(diagnostics)) {
-        try {
-          templates = parse(file.content, '');
-        } catch (err) {
-          diagnostics.push(new Diagnostic(err.message, id, DiagnosticSeverity.Error));
-        }
+      try {
```
Comment (boydc2014) [inline Composer/packages/lib/indexers/src/lgIndexer.ts]: I know there is some confusing and inconvenience how LG library provide features like validation and parsing, the core issue is parsing is not as tolerant as checker and CRUD functions. 

Here is a thread in LG side, that we will consolidate the interface in LG side, and unify the experience, especially on the assumption of when we throw errors, https://github.com/microsoft/botbuilder-dotnet/issues/3084. 

Hopefully with this work, the code in Composer will be simplified significantly.  Please take a look, and leave your opinions.
