### PR TITLE
fix: read me view additions to be inline with design spec

### LINKED ISSUE #6021: Creation modal readme formatting is inconsistent and needs improved copy + fix link
## Describe the bug

**Formatting**
When selecting a template, the readme section displays content with inconsistent formatting, ie title font size change, presence of sub-headers, links as text or URL.

Each readme should follow the same formatting. Follow the formatting convention being used for Conversational Core, Empty, and QnA. Smaller header. Sub-headers for Packages, Languages, and Azure Resource Deployment. Links as text. 

**Missing elements**
Each template should also include a icon/logo (align with package manager), version number, and link to documentation (and github?). Additionally, between the list and the readme section there should be a light grey line (see design below).

**External link**
Ensure each link in the readme triggers a new tab, otherwise the Composer window is hijacked and it's impossible to go back. External links should have external link icon (see below).

**Copy**
Description copy for each template needs improvement--Em, Ben, and Dewain will work together on that.

## Version

v1.3.1 special creation release

## Browser

- [x] Electron distribution

## OS

- [x] macOS

## To Reproduce

For external link specifically:
1. Go to create modal
2. Click on 'component model'
3. Land in github, can't get back to composer

## Screenshots
**Formatting No:**
image
image

**Formatting Yes:**
image
image
image

**Icons etc**
image

**Naughty link**
Click on component model:
image

App turns into Github and no back button (wahhhh)
so it needs to open in a new tab, and have an external link icon
image

### PR DESCRIPTION
**Pull request by pavolum**
## Description

PR to address the UX request to change the template picker view. 
- Added MSFT icon next to first party template names
- Added a stylized title bar owned by Composer and stripping out the title from the pulled npm package read me

## Task Item

fixes #6021 (composer portion), changes need to also be made to the readMe of each package in the components repo, tracked at issue [680](https://github.com/microsoft/botframework-components/issues/680)  in components repo

## Screenshots

image

### CODE REVIEW

File: Composer/packages/client/src/components/CreationFlow/v2/CreateOptions.tsx [hunk 1]
```diff
@@ -173,6 +174,12 @@ export function CreateOptionsV2(props: CreateOptionsProps) {
       onRender: (item) => (
         <div data-is-focusable css={tableCell}>
           <div css={content} tabIndex={-1}>
+            <img
+              alt={formatMessage('Composer Logo')}
```
Comment (benbrown) [inline Composer/packages/client/src/components/CreationFlow/v2/CreateOptions.tsx:178]: change this to Microsoft logo

File: Composer/packages/client/src/components/CreationFlow/v2/TemplateDetailView.tsx [hunk 2]
```diff
@@ -3,15 +3,69 @@
...
+  template?: BotTemplate;
   readMe: string;
 };
 
 export const TemplateDetailView: React.FC<TemplateDetailViewProps> = (props) => {
-  return <ReactMarkdown>{props.readMe}</ReactMarkdown>;
+  // readMe comes from npm where first line is the template title.
+  // Composer formats and displays its own template title and strips out the first line to avoid redundent titles
+  const getStrippedReadMe = () => {
+    const lines = props.readMe.split('\n');
```
Comment (benbrown) [inline Composer/packages/client/src/components/CreationFlow/v2/TemplateDetailView.tsx:51]: maybe just do this all on one line?

return props.readMe.split(/\n/).splice(0,1).join('\n')

Comment (benbrown) [reply Composer/packages/client/src/components/CreationFlow/v2/TemplateDetailView.tsx:51]: Actually, this will only work if the title is the ABSOLUTE first line of the returned readme. 

We may want to do a regular expression, something like `props.readMe.replace(/^# (.*?)\n/)`. which should replace the first instance of `# (something)\n`

File: Composer/packages/client/src/components/CreationFlow/v2/CreateOptions.tsx (hunk 1 above)
Comment (pavolum) [reply Composer/packages/client/src/components/CreationFlow/v2/CreateOptions.tsx:178]: handled

File: Composer/packages/client/src/components/CreationFlow/v2/TemplateDetailView.tsx (hunk 2 above)
Comment (pavolum) [reply Composer/packages/client/src/components/CreationFlow/v2/TemplateDetailView.tsx:51]: handled

**Review by benbrown — APPROVED** [review]

**Review by boydc2014 — APPROVED** [review]
