### PR TITLE
fix: add a new help URL to the Expression editor

### LINKED ISSUE #2792: Validation issues - can we get some features back?
## Describe the bug
* Users are NOT able to expand the incomplete error message in the Language Generation inline editor. 
image

* Users are NOT able to expand the incomplete error message in the Language Understanding inline editor. 
image

* Users are able to expand the incomplete error message but need a link pointing to the [Adaptive Expressions](https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/common-expression-language) reference doc.
image

## Version

Latest master branch

## Browser
- [x] Chrome

## OS
- [x] Windows

## To Reproduce

1. Produce an error on purpose in the LG/LU inline editor
2. Click on the generated error message
3. See error

## Expected behavior
- Should allow users to expand the error message.
- Should provide corresponding reference docs for syntax. 

## Additional
What we used to have:
* **lg**
lg-inline-error

* **lu**
lu-inline-error

* **Expressions**
expand-expression-error

### PR DESCRIPTION
**Pull request by beyackle**
## Description

Adds in a help URL to the expression editor, plus some plumbing to make it easy to decorate other sorts of fields with whatever other syntax help URLs we need.

## Task Item

closes #2792

## Screenshots

image

### CODE REVIEW

File: Composer/packages/extensions/adaptive-form/src/components/FormRow.tsx [hunk 1]
```diff
@@ -59,6 +59,9 @@ const FormRow: React.FC<FormRowProps> = props => {
 
   const { required = [] } = schema;
 
+  const HELP_URL =
+    'https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/common-expression-language';
+
```
Comment (a-b-r-o-w-n) [inline Composer/packages/extensions/adaptive-form/src/components/FormRow.tsx:64]: This should probably exist in the expression plugin package.

**Comment by beyackle** [comment]
Hang on - this is still not quite right.

File: Composer/packages/extensions/adaptive-form/src/components/SchemaField.tsx [hunk 2]
```diff
@@ -34,9 +34,10 @@ const SchemaField: React.FC<FieldProps> = props => {
     ...rest
   } = props;
   const pluginConfig = usePluginConfig();
+
   const schema = resolveRef(baseSchema, definitions);
   const uiOptions = {
-    ...getUISchema(schema, pluginConfig.formSchema),
+    ...getUIOptions(schema, pluginConfig.formSchema, pluginConfig.roleSchema[schema.$role || '']),
```
Comment (a-b-r-o-w-n) [inline Composer/packages/extensions/adaptive-form/src/components/SchemaField.tsx:40]: `pluginConfig.roleSchema[schema.$role || '']` should happen inside of `getUIOptions` just like formSchema

File: Composer/packages/extensions/adaptive-form/src/utils/getUIOptions.ts [hunk 3]
```diff
@@ -0,0 +1,15 @@
+// Copyright (c) Microsoft Corporation.
+// Licensed under the MIT License.
+import { UISchema, UIOptions, JSONSchema7 } from '@bfc/extension';
+/**
+ * Merges overrides and plugins into default ui schema and returns the UIOptions
+ */
+export function getUIOptions(schema?: JSONSchema7, uiSchema?: UISchema, pluginOptions?: UIOptions): UIOptions {
```
Comment (a-b-r-o-w-n) [inline Composer/packages/extensions/adaptive-form/src/utils/getUIOptions.ts:7]:
```suggestion
export function getUIOptions(schema?: JSONSchema7, uiSchema?: UISchema, roleSchema?: UIOptions): UIOptions {
```

File: Composer/packages/extensions/adaptive-form/src/utils/getUIOptions.ts [hunk 4]
```diff
@@ -0,0 +1,15 @@
...
+  const { $kind } = schema?.properties || {};
+
+  const kind = $kind && typeof $kind === 'object' && ($kind.const as string);
+
+  const formOptions = uiSchema && kind && uiSchema[kind] ? uiSchema[kind] : {};
+
+  return { ...formOptions, ...pluginOptions };
```
Comment (a-b-r-o-w-n) [inline Composer/packages/extensions/adaptive-form/src/utils/getUIOptions.ts:14]: Let's invert this so that formOptions override pluginOptions.

Comment (beyackle) [reply Composer/packages/extensions/adaptive-form/src/utils/getUIOptions.ts:14]: Will do, although intuitively it feels to me like a plugin should be able to overwrite defaults.

**Comment by beyackle** [comment]
I have no idea why fixing conflicts causes it to replay all of the commits back in this weird snowballing fashion.

File: Composer/packages/extensions/adaptive-form/src/utils/getUIOptions.ts (hunk 4 above)
Comment (a-b-r-o-w-n) [reply Composer/packages/extensions/adaptive-form/src/utils/getUIOptions.ts]: These are the merged result of all the plugins. Which have overwritten the defaults already.

Just in this case, I think that specifying something on a particular field should take precedence over an override for a role.

File: Composer/packages/extensions/adaptive-form/package.json [hunk 5]
```diff
@@ -17,6 +17,7 @@
   },
   "license": "MIT",
   "peerDependencies": {
+    "@bfc/ui-plugin-expressions": "*",
```
Comment (a-b-r-o-w-n) [inline Composer/packages/extensions/adaptive-form/package.json:20]: This should be removed.

File: Composer/packages/client/src/pages/design/PropertyEditor.tsx [hunk 6]
```diff
@@ -57,7 +57,7 @@ const PropertyEditor: React.FC = () => {
   }, []);
 
   const $uiSchema = useMemo(() => {
-    return getUISchema($schema, pluginConfig.formSchema);
+    return getUIOptions($schema, pluginConfig.formSchema);
```
Comment (a-b-r-o-w-n) [inline Composer/packages/client/src/pages/design/PropertyEditor.tsx:60]: This is missing passing `pluginConfig.roleSchema`

File: Composer/packages/extensions/adaptive-form/src/utils/getUIOptions.ts [hunk 7]
```diff
@@ -0,0 +1,16 @@
...
+/**
+ * Merges overrides and plugins into default ui schema and returns the UIOptions
+ */
+export function getUIOptions(schema?: JSONSchema7, uiSchema?: UISchema, roleSchema?: RoleSchema): UIOptions {
+  const { $kind } = schema?.properties || {};
+
+  const kind = $kind && typeof $kind === 'object' && ($kind.const as string);
+
+  const formOptions = uiSchema && kind && uiSchema[kind] ? uiSchema[kind] : {};
+  const pluginOptions = roleSchema && kind && roleSchema[kind] ? roleSchema[kind] : {};
```
Comment (a-b-r-o-w-n) [inline Composer/packages/extensions/adaptive-form/src/utils/getUIOptions.ts:13]:
```suggestion
  const roleOptions = roleSchema && kind && roleSchema[kind] ? roleSchema[kind] : {};
```

Comment (a-b-r-o-w-n) [reply Composer/packages/extensions/adaptive-form/src/utils/getUIOptions.ts:13]: This will also need to get the $role  from the schema to index into the `roleSchema` instead of kind.
