### PR TITLE
fix: rephrase no-recent-bots box

### LINKED ISSUE #8337: Missing link on the Composer welcome screen
Repro:

Download and run BotFramework-Composer-2.0.0-nightly.258070.287a4dc-windows-setup.exe.
Displayed on the first screen is "Welcome to Bot Framework Composer".
Also displayed is "Open the product tour to learn about Bot Framework Composer or create a new bot".
"create a new bot" is a link.

Expected: A link for "Open the product tour". 
Actual: Can't find any link to something called "product tour" on the screen.

### PR DESCRIPTION
**Pull request by beyackle**
## Description

Replaces the no-longer-current "open the product tour" text on the home screen when there are no projects loaded with a rephrased link to starting a new bot.

## Task Item

closes #8337

## Screenshots

image

### CODE REVIEW

File: Composer/packages/client/src/pages/home/Home.tsx [hunk 1]
```diff
@@ -189,22 +189,19 @@ const Home: React.FC<RouteComponentProps> = () => {
...
-                            onClickNewBot();
-                            TelemetryClient.track('ToolbarButtonClicked', { name: 'new' });
-                          }}
-                        >
-                          {children}
-                        </Link>
-                      ),
-                    }
-                  )}
+                  {formatMessage.rich('<Link>Create a new bot to get started</Link>', {
```
Comment (srinaath) [inline Composer/packages/client/src/pages/home/Home.tsx:192]: nit: Just looking at this should the link part just be for the "Create a new bot".

**Review by srinaath — APPROVED** [review]
