### PR TITLE
fix: Added missing flag to prevent concurrent downloads of the same update.

### LINKED ISSUE #2226: Implement Auto-Update UX for Composer Electron
Work with @DesignPolice to implement in-app UX for automatic application updates.

### PR DESCRIPTION
**Pull request by tonyanziano**
## Description

This PR adds a line that flips a flag to prevent multiple downloads of the same update.

(Must have missed this in the original auto update PR 😮)

[This check was already there](https://github.com/microsoft/BotFramework-Composer/blob/master/Composer/packages/electron-server/src/appUpdater.ts#L49), but nothing was ever flipping `downloadingUpdate` to `true`.

## Task Item

fixes #2226

### CODE REVIEW

File: Composer/packages/electron-server/src/appUpdater.ts [hunk 1]
```diff
@@ -57,6 +57,7 @@ export class AppUpdater extends EventEmitter {
 
   public downloadUpdate() {
     if (!this.downloadingUpdate) {
+      this.downloadingUpdate = true;
```
Comment (cwhitten) [inline Composer/packages/electron-server/src/appUpdater.ts:60]: do we need to set this to false when it's finished?

Comment (tonyanziano) [reply Composer/packages/electron-server/src/appUpdater.ts:60]: It already is being set to false in [`resetToIdle()`](https://github.com/microsoft/BotFramework-Composer/blob/master/Composer/packages/electron-server/src/appUpdater.ts#L120) which is called on error, finished downloading, or update unavailable.
