### PR TITLE
fix: [#9492] Fix WebChat createGetAttachmentHandler image file serving

### LINKED ISSUE #9492: Bug : Bot composer - web chat throws an exception connecting to Form Recognizer
## Describe the bug

Bot composer - web chat throws an exception
In Bot Framework Emulator is working fine.

## Version

Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1 . Connect to Form Recognizer(written custom action) 
2.  Upload the file via Web chat ( In bot composer) throws an exception

**Invalid request.

Status: 400 (Bad Request)

ErrorCode: InvalidRequest

Content:

{“error”:{“code”:“InvalidRequest”,“message”:“Invalid request.”,“innererror”:{“code”:“InvalidContent”,“message”:“The file is corrupted or format is unsupported. Refer to documentation for the list of supported formats.”}}}

Headers:

x-envoy-upstream-service-time: 393

apim-request-id: 523579a1-9792-40f4-95f9-9ed02011c29b

Strict-Transport-Security: max-age=31536000; includeSubDomains; preload

X-Content-Type-Options: nosniff

x-ms-region: REDACTED

Date: Sun, 22 Jan 2023 15:03:48 GMT

Content-Length: 221

Content-Type: application/json; charset=utf-8**

## Expected behaviour 

It should work like Bot Framework Emulator

## Screenshots

https://user-images.githubusercontent.com/16264167/213924071-a1e127ea-dea7-458f-a138-9b6bd8cdcbe5.mp4

### PR DESCRIPTION
**Pull request by sw-joelmut**
## Description

This PR fixes an issue when uploading an image file from Composer's WebChat and then accessing it through the `/v3/attachments/<attachment id>/views/original` endpoint failed on displaying it (saying `it cannot be displayed because it contains errors`).

**Detailed changes**
- Send only one value through the `Response.send` function.
- Support other data types than just JSON strings in the `logNetworkTraffic` file.

## Task Item

Fixes #9492

## Screenshots
The following image shows both Emulator and WebChat working as expected.
image

### CODE REVIEW

File: Composer/packages/server/src/middleware/logNetworkTraffic.ts [hunk 1]
```diff
@@ -18,9 +18,11 @@ export function logNetworkTraffic(req: Request, res: Response, next?: NextFuncti
   // when the request finishes, log the payload and status code to the client
   res.once('finish', () => {
     let data: ConversationNetworkErrorItem | ConversationNetworkTrafficItem | undefined;
+    let payload = (res as any).sentData;
+    payload = typeof payload === 'string' ? JSON.parse(payload || '{}') : payload;
```
Comment (srinaath) [inline Composer/packages/server/src/middleware/logNetworkTraffic.ts:22]: Wrapping anything with JSON.parse around a try catch would be defensive. JSON.parse(null/undefined) would throw

**Review by srinaath — APPROVED** [review]
