### PR TITLE
fix: allow extension to register multiple publish targets

### LINKED ISSUE #4394: "Publish bot to Azure" choice has no text
## Describe the bug
No text for the first entry in the dropdown

image

## Version
Version:  1.1.1-nightly.172371.8d1fc5a

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Publish'
2. Click on 'Add new Profile'
3. See the value is missing

## Expected behavior
Should show something like "Publish bot to Azure"

## Screenshots
image

### PR DESCRIPTION
**Pull request by a-b-r-o-w-n**
## Description

Requires name and description for publish targets.

## Task Item

fixes #4394 

## Screenshots

image

### CODE REVIEW

File: extensions/sample-ui-plugin/src/node/index.ts [hunk 1]
```diff
@@ -1,15 +1,26 @@
...
-  registration.addPublishMethod(plugin);
+  const plugin2 = {
+    name: 'samplePublishPlugin2',
+    description: 'Publish using custom UI (2)',
+    bundleId: 'publish2' /** we have custom UI to host */,
+    publish,
+    getStatus,
+  };
+  registration.addPublishMethod(plugin1);
+  registration.addPublishMethod(plugin2);
```
Comment (tonyanziano) [inline extensions/sample-ui-plugin/src/node/index.ts:23]: sweet!

**Review by tonyanziano — APPROVED** [review]
Looks good to me!

File: Composer/packages/extension/package.json [hunk 2]
```diff
@@ -25,6 +24,7 @@
   },
   "dependencies": {
     "@botframework-composer/types": "*",
+    "@types/passport": "^1.0.3",
```
Comment (hatpick) [inline Composer/packages/extension/package.json:27]: it's a dev dep right?

File: Composer/packages/extension/src/extensionRegistration.ts [hunk 3]
```diff
@@ -58,12 +58,17 @@ export class ExtensionRegistration {
    * Publish related features
    *************************************************************************************/
   public async addPublishMethod(plugin: PublishPlugin) {
-    log('registering publish method', this.name);
-    this.context.extensions.publish[plugin.customName || this.name] = {
+    if (this.context.extensions.publish[plugin.name]) {
+      throw new Error(`Duplicate publish method. Cannot register publish method with name ${plugin.name}.`);
```
Comment (hatpick) [inline Composer/packages/extension/src/extensionRegistration.ts:62]: nit: if this is surfaced to the UI, maybe use formatMessage

File: extensions/azurePublish/src/index.ts [hunk 4]
```diff
@@ -6,8 +6,8 @@ import path from 'path';
 import { v4 as uuid } from 'uuid';
```
Comment (hatpick) [inline extensions/azurePublish/src/index.ts:6]: I highly recommend avoid using arrow functions for class methods.

File: Composer/packages/extension/src/extensionRegistration.ts (hunk 3 above)
Comment (a-b-r-o-w-n) [reply Composer/packages/extension/src/extensionRegistration.ts:62]: Couple of things:

- It doesn't get to the UI. It will end up in the terminal if this is thrown.
- Our server is not yet set up to handle i18n.

Comment (beyackle) [reply Composer/packages/extension/src/extensionRegistration.ts:62]: As far as I've seen, messages that get thrown out to the console (like those inside exceptions) don't need to be localized. Only strings that get displayed to a normal user do.

File: extensions/localPublish/src/index.ts [hunk 5]
```diff
@@ -36,12 +38,14 @@ interface PublishConfig {
 
 const isWin = process.platform === 'win32';
 
-class LocalPublisher {
+class LocalPublisher implements PublishPlugin<PublishConfig> {
+  public name = 'localPublisher';
+  public description = 'Publish bot to local runtime';
   static runningBots: { [key: string]: RunningBot } = {};
```
Comment (hatpick) [inline extensions/localPublish/src/index.ts:44]: nit: Record<string, RunningBot>

File: extensions/azurePublish/src/index.ts (hunk 4 above)
Comment (a-b-r-o-w-n) [reply extensions/azurePublish/src/index.ts:6]: Noted. I just did minimal updates to this file, so feel free to open a PR with that change.

File: Composer/packages/extension/package.json (hunk 2 above)
Comment (a-b-r-o-w-n) [reply Composer/packages/extension/package.json:27]: This actually needs to be in the dependencies because we reference it in an exported type.

File: extensions/localPublish/src/index.ts (hunk 5 above)
Comment (a-b-r-o-w-n) [reply extensions/localPublish/src/index.ts:44]: I always forget about `Record`. However, since this PR is scoped to the publishing name and description, I am going to leave as is.
