### PR TITLE
fix: Goto Begin Dialog after clicking dialog

### LINKED ISSUE #3070: Cannot edit dialog properties, always jump to 'dialog started' trigger
## Describe the bug
bug-cannot-focusdialog

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

### PR DESCRIPTION
**Pull request by tdurnford**
## Description
The `designPageLocation` object being included in the `usEffect` dependency array causes the selected trigger to be set to the `BeginDialog` trigger after the user selects the dialog because `designPageLocation.selected` gets set to null when a trigger isn't selected which causes the hook to execute unnecessarily. Removing `designPageLocation` from the `usEffect` dependency array resolves the issue.

## Task Item
Closes #3070

## Screenshots
recording

### CODE REVIEW

File: Composer/packages/client/src/pages/design/index.tsx [hunk 1]
```diff
@@ -130,11 +130,12 @@ const DesignPage: React.FC<RouteComponentProps<{ dialogId: string; projectId: st
   }, [dialogId, dialogs, location]);
 
   useEffect(() => {
+    console.log(designPageLocation);
```
Comment (cwhitten) [inline Composer/packages/client/src/pages/design/index.tsx:133]: can you remove this?

Comment (tdurnford) [reply Composer/packages/client/src/pages/design/index.tsx]: I shouldn't open PR's before I've had coffee.
