### PR TITLE
fix: in setting botId not consistence with MicrosoftAppId

### LINKED ISSUE #3849: botid serialization need manual update
Go to skill page, 
- Input "skill host endpoint"
- Input bot password
- Input bot id
sounds like app id has not been serialized into "botid" field but "MicrosoftAppid" is correctly set.
Go to setting page and manually update botid can solve the warning sign. 
image
image
image

### LINKED ISSUE #3853: Upgrade from 1.02 to latest shows warnings that seem benign or misleading
## Describe the bug
Upgraded to nightly build. Using a composer bot pointing to skills.

## Version
Daily build (8/14)

## Browser
- [ X] Electron distribution

## OS
- [ X] Windows

## To Reproduce

Upgrade to latest with a bot using skills.

## Screenshots

composerwarn2

composerwarn

---

{
  "feature": {
    "UseShowTypingMiddleware": false,
    "UseInspectionMiddleware": false,
    "RemoveRecipientMention": false
  },
  "MicrosoftAppPassword": "asdf",
  "MicrosoftAppId": "000ad8f3-asdf-asdf-asdf-asdfasdfasdf",
  "cosmosDb": {
    "authKey": "",
    "collectionId": "botstate-collection",
    "cosmosDBEndpoint": "",
    "databaseId": "botstate-db"
  },
  "applicationInsights": {
    "InstrumentationKey": ""
  },
  "blobStorage": {
    "connectionString": "",
    "container": "transcripts"
  },
  "luis": {
    "name": "",
    "authoringKey": "",
    "authoringEndpoint": "",
    "endpointKey": "",
    "endpoint": "",
    "authoringRegion": "westus",
    "defaultLanguage": "en-us",
    "environment": "composer"
  },
  "publishTargets": [],
  "qna": {
    "knowledgebaseid": "",
    "endpointkey": "",
    "hostname": ""
  },
  "telemetry": {
    "logPersonalInformation": false,
    "logActivities": true
  },
  "runtime": {
    "customRuntime": false,
    "path": "",
    "command": ""
  },
  "downsampling": {
    "maxImbalanceRatio": 10,
    "maxUtteranceAllowed": 15000
  },
  "botId": "",
  "skillHostEndpoint": "http://asdfasdf.ngrok.io/api/skills",
  "skill": [
    {
      "manifestUrl": "http://localhost:3979/manifests/SurveyBot-2-1-preview-1-manifest.json",
      "name": "SurveyBotSkill"
    },
    {
      "manifestUrl": "https://asdfasdf.azurewebsites.net/wwwroot/echo-bot-manifest.json",
      "name": "EricEchoSkill"
    }
  ],
  "defaultLanguage": "en-us",
  "languages": [
    "en-us"
  ]
}

### PR DESCRIPTION
**Pull request by zhixzhan**
## Task Item

close #3849 
close #3853

### CODE REVIEW

**Review by a-b-r-o-w-n — APPROVED** [review]

File: Composer/packages/client/src/pages/skills/skill-settings.tsx [hunk 1]
```diff
@@ -39,8 +39,13 @@ const SkillSettings: React.FC<ISkillFormProps> = (props) => {
...
       [event.target.id]: event.target.value,
     };
+
+    // auto fill `botId` with `MicrosoftAppId`
+    if (event.target.id === 'MicrosoftAppId') {
+      localSettings.botId = event.target.value;
+    }
+
     setSkillSettings({ ...localSettings });
-    console.log('ehh', localSettings);
```
Comment (cwhitten) [inline Composer/packages/client/src/pages/skills/skill-settings.tsx:43]: thanks
