### PR TITLE
fix: update left nav and top bar strings

### LINKED ISSUE #7569: Fit  & finish - UI Copy | Chrome and left nav
**Chrome & left nav UI Copy**
White cells = existing copy
Yellow/blue cells = new copy

Link to 'live' copy on 'Chrome & nav' tab: https://microsoft.sharepoint.com/:x:/r/teams/ConversationalAI785/_layouts/15/Doc.aspx?sourcedoc=%7B6B1FACBD-B5FE-4AD2-A35B-995635C1696B%7D&file=glossary.xlsx&action=edit&mobileredirect=true&wdPreviousSession=36539654-a42b-4b87-be1b-de96507b4422&wdOrigin=TEAMS-ELECTRON.teams.undefined&cid=676cf454-61e0-4182-bd27-39044bb51cea

Home_copy

Leftnav_copy

### PR DESCRIPTION
**Pull request by beyackle**
## Description

Rearranges and rephrases the top bar and the left nav to fit the new strings.

## Task Item

fixes #7569 

## Screenshots

image
image

### CODE REVIEW

File: Composer/packages/client/src/components/BotRuntimeController/BotController.tsx [hunk 1]
```diff
@@ -275,7 +275,7 @@ const BotController: React.FC<BotControllerProps> = ({ onHideController, isContr
         </DisableFeatureToolTip>
         <div ref={onboardRef} css={[iconSectionContainer, disableStartBots ? disabledStyle : '']}>
           <IconButton
-            ariaDescription={formatMessage('Open start bots panel')}
+            ariaDescription={formatMessage('Start and stop local bot runtimes')}
```
Comment (tdurnford) [inline Composer/packages/client/src/components/BotRuntimeController/BotController.tsx:278]: Should we move the formatMessage out into a variable and reuse it for the title below?

File: Composer/packages/client/src/utils/pageLinks.ts [hunk 2]
```diff
@@ -42,17 +42,17 @@ export const topLinks = (
     {
       to: linkBase + `dialogs/${openedDialogId}`,
```
Comment (tdurnford) [inline Composer/packages/client/src/utils/pageLinks.ts:43]: Can you update all the `to` links to use string interpolation instead of using the addition operator? 
```suggestion
      to: `${linkBase}dialogs/${openedDialogId}`,
```

File: Composer/packages/client/src/utils/pageLinks.ts [hunk 3]
```diff
@@ -42,17 +42,17 @@ export const topLinks = (
...
       match: /(bot\/[0-9.]+)$|(bot\/[0-9.]+\/skill\/[0-9.]+)$/,
       isDisabledForPVA: false,
     },
     {
-      to: linkBase + `language-generation/${openedDialogId}`,
-      iconName: 'Robot',
-      labelName: formatMessage('Bot responses'),
-      disabled: !botLoaded || skillIsRemote,
-      match: /language-generation\/[a-zA-Z0-9_-]+$/,
+      to: `/bot/${rootProjectId || projectId}/botProjectsSettings`,
```
Comment (tdurnford) [inline Composer/packages/client/src/utils/pageLinks.ts:51]: Why aren't you using the link base?

Comment (beyackle) [reply Composer/packages/client/src/utils/pageLinks.ts:51]: The project settings page only makes sense to be called from a root bot, not a skill. The rootProjectId, if it exists, is the ID of the root of a project, while "projectId" refers to the current bot we're looking at whether it's a root or a skill. It's a slightly clumsy workaround, but it works.

**Comment by tdurnford** [comment]
@mareekuh @beyackle Do the page title need to be updated as well? For example, the 'Configure' menu option takes you to 'Bot management and configurations'. Sightly confusing. 

image

**Comment by beyackle** [comment]
> @mareekuh @beyackle Do the page title need to be updated as well? For example, the 'Configure' menu option takes you to 'Bot management and configurations'. Sightly confusing.
> 
> image

I wasn't asked to change those, so I assume they're fine.

**Comment by benbrown** [comment]
> > @mareekuh @beyackle Do the page title need to be updated as well? For example, the 'Configure' menu option takes you to 'Bot management and configurations'. Sightly confusing.
> > image
> 
> I wasn't asked to change those, so I assume they're fine.

I changed the title of the settings page in my PR that has now merged

File: Composer/packages/client/src/components/BotRuntimeController/BotController.tsx (hunk 1 above)
Comment (benbrown) [inline Composer/packages/client/src/components/BotRuntimeController/BotController.tsx:278]: yay

**Review by benbrown — DISMISSED** [review]

**Review by tdurnford — DISMISSED** [review]

File: extensions/packageManager/package.json [hunk 4]
```diff
@@ -52,7 +52,7 @@
     "@emotion/core": "^10.0.35",
     "@microsoft/bf-dialog": "4.13.1",
     "@uifabric/fluent-theme": "^7.1.4",
-    "axios": "^0.19.2",
+    "axios": "^0.21.0",
```
[the remark this answers is not in the document]
Comment (tdurnford) [reply extensions/packageManager/package.json:55]: @a-b-r-o-w-n Already has a PR to do this. 
https://github.com/microsoft/BotFramework-Composer/issues/7647

[the remark this answers is not in the document]
Comment (beyackle) [reply extensions/packageManager/package.json:55]: To solve a security issue that just came up and is preventing PRs from passing.

[the remark this answers is not in the document]
Comment (tdurnford) [reply extensions/packageManager/package.json:55]: Can you revert those changes and wait for Andy's PR to merge? It's already shiproom approved.

**Review by tdurnford — APPROVED** [review]
