### PR TITLE
fix: Fixes Cards template

### LINKED ISSUE #2709: Responding with cards sample no renderer for adaptive card
## Describe the bug
Choose adaptive card self, it works. But when you select all cards, the last card will show No renderer for this attachment.

## Version

composer stable

## Screenshots

image

image

### PR DESCRIPTION
**Pull request by cwhitten**
closes #2709

Also does some minor styling cleanup around in <Header />

### CODE REVIEW

File: Composer/packages/client/src/components/Header/index.jsx [hunk 1]
```diff
@@ -35,8 +35,11 @@ export const Header = props => {
         src={composerIcon}
       />
       <div css={title}>{formatMessage('Bot Framework Composer')}</div>
-      <div css={divider} />
-      <div css={botName}>{props.botName}</div>
+      {props.botName && (
+          <div css={divider} />
+          <span css={botName}>{`${props.botName}(${props.locale}}`}</span>
```
Comment (a-b-r-o-w-n) [inline Composer/packages/client/src/components/Header/index.jsx:40]: Incorrect closing tag
```suggestion
          <span css={botName}>{`${props.botName} (${props.locale})`}</span>
```
