### PR TITLE
fix: only selected row has enabled toggle in feed modal

### LINKED ISSUE #7028: Prer... Button activates when you click on a custom row, but is disabled when you try and click on it.
## Describe the bug

The Prer... buttons (whatever those are) are disabled, until you click on a custom feed, then ALL of them are enabled, but when you try to click on them they are disabled again. Confusing as heck.
## Version

image

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. createproject 
2. go to feeds
3. Prer.. buttons are disabled
4. click on a custom feed, **Pre...** buttons are enabled on ALL rows.

## Expected behavior
a. to be able to turn on and off "official" feeds
 
## Screenshots

image
image

### PR DESCRIPTION
**Pull request by benbrown**
## Description

correct the enabled/disabled state on the feed management modal in package manager so that only the selected row is enabled

## Task Item

fixes #7028

## Screenshots

rySjLjxF9C

### CODE REVIEW

**Review by beyackle — APPROVED** [review]

**Review by GeoffCoxMSFT — APPROVED** [review]

File: extensions/packageManager/src/components/FeedModal.tsx [hunk 1]
```diff
@@ -187,7 +187,7 @@ export const FeedModal: React.FC<WorkingModalProps> = (props) => {
           <Toggle
             ariaLabel={formatMessage('Include prerelease versions')}
             checked={item ? item.defaultQuery?.prerelease : false}
-            disabled={!selectedItem || selectedItem.readonly}
+            disabled={!selectedItem || item.key !== selectedItem.key || selectedItem.readonly}
```
Comment (a-b-r-o-w-n) [inline extensions/packageManager/src/components/FeedModal.tsx:190]: Can the first check be removed altogether? And should the `readonly` check be on the item, not the selected item?
```suggestion
            disabled={item.key !== selectedItem.key || item.readonly}
```

Comment (benbrown) [reply extensions/packageManager/src/components/FeedModal.tsx]: I applied this change here and in a few other places.

**Review by a-b-r-o-w-n — APPROVED** [review]
