### PR TITLE
fix: silently ignore ResizeObserver errors

### LINKED ISSUE #8361: [R14 bugbash] Resizing the Composer window gets ResizeObserver loop limit exceeded
Resizing Composer from full screen, I got a popup saying "ResizeObserver loop ..." ... "ResizeObserver loop limit exceeded".

What I did: 
Composer was on its "Home" page.
The window was maximized on my computer screen.
I moved it over to my external monitor. It maximized itself.
I clicked the resize button in top right corner. Error occurred.

### PR DESCRIPTION
**Pull request by beyackle**
## Description

This will cause all ResizeObserver errors to get swallowed by the window's custom error handler. These events are harmless and have been leading to issues.

## Task Item

close #8361

### CODE REVIEW

File: Composer/packages/client/src/components/ErrorBoundary.tsx [hunk 1]
```diff
@@ -57,6 +57,11 @@ export class ErrorBoundary extends Component<ErrorBoundaryProps, ErrorBoundarySt
   }
 
   onErrorHandler(message, source, lineno, colno, error) {
+    const patternsToIgnore = [/ResizeObserver/g];
```
Comment (tdurnford) [inline Composer/packages/client/src/components/ErrorBoundary.tsx:60]: Move `patternsToIgnore` outside of the function definition.

File: Composer/packages/client/src/components/ErrorBoundary.tsx [hunk 2]
```diff
@@ -57,6 +57,11 @@ export class ErrorBoundary extends Component<ErrorBoundaryProps, ErrorBoundarySt
...
+    if (patternsToIgnore.some((regex) => regex.test(message))) {
+      // skip the console and application-level steps and just say we handled it
+      return true;
+    }
     console.error({ message, source, lineno, colno, error });
```
Comment (tdurnford) [inline Composer/packages/client/src/components/ErrorBoundary.tsx:65]: We should log the error to the console. Move the `console.log` before the if-statement. We don't want to hide errors from the developer.

**Review by tdurnford — CHANGES_REQUESTED** [review]

**Review by tdurnford — APPROVED** [review]
