### PR TITLE
fix: do not create duplicated qnamatcher trigger

### LINKED ISSUE #4059: Qna dialog code keep dup when click "Create Kb from scratch"
## Describe the bug

Qna dialog code keep dup when click "Create Kb from scratch"

## Version

latest main

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. 
image

2. 
image

3. 
image

keep operate like this, you will have the adaptive dialog dup with the same code

## Expected behavior

do not dup

### PR DESCRIPTION
**Pull request by liweitian**
## Description
do not create duplicated qnamaker kind trigger through Add new knowledge base on {dialogName}

## Task Item
Closes #4059 

## Screenshots
aaa1

### CODE REVIEW

**Comment by boydc2014** [comment]
@liweitian can you resolve the conflict?

**Review by yeze322 — CHANGES_REQUESTED** [review]
It's not necessary to change the interface of triggerApi. Consider fix the issue in another way,

File: Composer/packages/client/src/shell/triggerApi.ts [hunk 1]
```diff
@@ -28,7 +28,7 @@ function createTriggerApi(
     return value.substring(startIndex + 1, endIndex);
   };
 
-  const createTriggerHandler = async (id, formData, url) => {
+  const createTriggerHandler = async (id, formData, url, checkDuplicatedKind) => {
```
Comment (yeze322) [inline Composer/packages/client/src/shell/triggerApi.ts:31]: Don't fix the issue by changing the interface of `createTriggerHandler`, it shoudn't be affected by this issue.
Hoist `checkDuplicatedKind` logic to invoker (DesignPage in your case).

File: Composer/packages/client/src/pages/design/DesignPage.tsx [hunk 2]
```diff
@@ -585,7 +585,7 @@ const DesignPage: React.FC<RouteComponentProps<{ dialogId: string; projectId: st
     };
     if (dialogId) {
       const url = `/bot/${projectId}/knowledge-base/${dialogId}`;
-      createTrigger(dialogId, formData, url);
+      createTrigger(dialogId, formData, url, true);
```
Comment (yeze322) [inline Composer/packages/client/src/pages/design/DesignPage.tsx:588]: Check the existence of QnA trigger here.

File: Composer/packages/client/src/shell/triggerApi.ts [hunk 3]
```diff
@@ -38,24 +38,38 @@ function createTriggerApi(
...
-        LgTemplateSamples.TextInputPromptForQnAMatcher(designerId1) as LgTemplate,
-        LgTemplateSamples.SendActivityForQnAMatcher(designerId2) as LgTemplate,
-      ];
-      await createLgTemplates({ id: lgFile.id, templates: lgTemplates });
+      let shouldCreate = true;
+      if (checkDuplicatedKind) {
+        const triggers = get(dialog, 'triggers', []);
+        shouldCreate = !triggers.find((t) => t.type === qnaMatcherKey);
+      }
+      if (shouldCreate) {
```
Comment (yeze322) [inline Composer/packages/client/src/shell/triggerApi.ts:57]: low quality boolean chain

File: Composer/packages/client/src/shell/triggerApi.ts [hunk 4]
```diff
@@ -38,24 +38,38 @@ function createTriggerApi(
...
-      );
-      const lgTemplates: LgTemplate[] = [
-        LgTemplateSamples.TextInputPromptForQnAMatcher(designerId1) as LgTemplate,
-        LgTemplateSamples.SendActivityForQnAMatcher(designerId2) as LgTemplate,
-      ];
-      await createLgTemplates({ id: lgFile.id, templates: lgTemplates });
+      let shouldCreate = true;
+      if (checkDuplicatedKind) {
+        const triggers = get(dialog, 'triggers', []);
+        shouldCreate = !triggers.find((t) => t.type === qnaMatcherKey);
```
Comment (yeze322) [inline Composer/packages/client/src/shell/triggerApi.ts:55]: some()

**Review by yeze322 — CHANGES_REQUESTED** [review]
Fix this issue by invoking `createTriggerHandler` conditionally instead of patching the triggerApi

File: Composer/packages/client/src/pages/design/DesignPage.tsx [hunk 5]
```diff
@@ -564,9 +572,15 @@ const DesignPage: React.FC<RouteComponentProps<{ dialogId: string; projectId: st
       regEx: '',
       triggerPhrases: '',
     };
-    if (dialogId) {
+    const dialog = dialogs.find((d) => d.id === dialogId);
+    if (dialogId && dialog) {
```
Comment (hatpick) [inline Composer/packages/client/src/pages/design/DesignPage.tsx:576]: nit: ```if(dialog)``` is sufficient

Comment (liweitian) [reply Composer/packages/client/src/pages/design/DesignPage.tsx:576]: need to check dialogId because of createTrigger(dialogId, formData): Argument of type 'string | undefined' is not assignable to parameter of type 'string'.

**Review by yeze322 — DISMISSED** [review]
looks neat now

**Comment by cwhitten** [comment]
@liweitian please resolve conflicts

**Comment by liweitian** [comment]
> @liweitian please resolve conflicts

done

**Review by cwhitten — APPROVED** [review]
