### PR TITLE
fix: various form bugs

### LINKED ISSUE #2535: SetProperty 'type' not work when setting default values
## Describe the bug
When I SetProperty and change type to int or number, 0 cannot be set.
image
Maybe because default value cannot be set.

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

### LINKED ISSUE #2562: Value will be cleared in Headers with only one backspace hit
## Describe the bug

I just hit backspace only once:
cnhbNK3xu2
It happens when this is edited at first time(e.g. after refresh)

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

### LINKED ISSUE #2566: Http request header disappeared when I click other item
## Describe the bug

I have a header in the http request, and I want to change it. But after I change it, click another form and then click back, the header disappeared
headerbug

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

### LINKED ISSUE #2575: scroll bar works incorrectly and disappears
## Describe the bug

Should not show in this case:
image
Should show in this case (there are interruption etc. at the bottom):
image

## Version

aca735819a63caed7bfcdf6ce1ebba3611d00c1b

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

### PR DESCRIPTION
**Pull request by a-b-r-o-w-n**
## Description

Fixes a few issues in the form filed recently.

## Task Item

closes #2575
closes #2566
closes #2562
closes #2535

### CODE REVIEW

File: Composer/packages/extensions/adaptive-form/src/components/fields/OpenObjectField/ObjectItem.tsx [hunk 1]
```diff
@@ -0,0 +1,110 @@
...
+      iconProps: { iconName: 'Cancel' },
+      key: 'remove',
+      onClick: onDelete,
+      text: 'Remove',
+    },
+  ];
+
+  const handleBlur = useCallback(() => {
+    if (!name || name === '') {
+      setErrorMessage('Key cannot be blank');
```
Comment (tdurnford) [inline Composer/packages/extensions/adaptive-form/src/components/fields/OpenObjectField/ObjectItem.tsx:49]: Should the error messages be formatted with `formatMessage`?

File: Composer/packages/extensions/adaptive-form/src/components/fields/OpenObjectField/ObjectItem.tsx [hunk 2]
```diff
@@ -0,0 +1,110 @@
...
+      <div css={item}>
+        <EditableField
+          transparentBorder
+          depth={0}
+          id={`${name}.value`}
+          name="value"
+          placeholder={initialValue || formatMessage('Add a new value')}
+          schema={{}}
+          styles={{
+            root: { margin: '7px 0 7px 0' },
```
Comment (srinaath) [inline Composer/packages/extensions/adaptive-form/src/components/fields/OpenObjectField/ObjectItem.tsx:89]: Can be margin: 7px 0?

File: Composer/packages/extensions/adaptive-form/src/components/fields/OpenObjectField/ObjectItem.tsx [hunk 3]
```diff
@@ -0,0 +1,110 @@
...
+          onChange={onValueChange}
+          ariaLabel={formatMessage('value')}
+        />
+      </div>
+      <IconButton
+        ariaLabel={formatMessage('Edit Property')}
+        menuIconProps={{ iconName: 'MoreVertical' }}
+        menuProps={{ items: contextItems }}
+        styles={{
+          root: { margin: '7px 0 7px 0' },
```
Comment (srinaath) [inline Composer/packages/extensions/adaptive-form/src/components/fields/OpenObjectField/ObjectItem.tsx:102]: 7px 0?
