### PR TITLE
fix: add disk names

### LINKED ISSUE #2257: Load project from X: hard drive
Hi all,
I need to load project from D drive!
From the GUI, I cannot select a different drive than C:

image

### PR DESCRIPTION
**Pull request by liweitian**
## Description
1. The bug only exists on windows because of hard disk partition.
2. The parent of root disk will be This PC. Go to 'This PC', it will show all existing disk names.
3. Note that this is a corner case, Path module does not recognize 'This PC' as a valid path.
## Task Item
Closes #2257 
## Screenshots
aaaaa

### CODE REVIEW

File: Composer/packages/server/src/settings/index.ts [hunk 1]
```diff
@@ -18,8 +19,12 @@ interface Settings {
   runtimeFrameworkVersion: string;
   botsFolder: string;
   appDataPath: string;
+  isWindows: boolean;
+  validDiskNames: string[];
 }
 
+const diskNames = ['C:/', 'D:/', 'E:/', 'F:/', 'G:/', 'H:/', 'I:/', 'J:/', 'K:/'];
```
Comment (boydc2014) [inline Composer/packages/server/src/settings/index.ts]: let's talk about this later, see if we can avoid a hard code here

Comment (boydc2014) [reply Composer/packages/server/src/settings/index.ts]: The suggestion is, no matter what the implementation is, it's would be necessary to update the protocol, adding new state or settings, we should use existing abstraction, and treat disk part in windows just as normal folders.

**Comment by boydc2014** [comment]
Looks way better now.

File: Composer/packages/server/src/services/storage.ts [hunk 2]
```diff
@@ -68,6 +68,20 @@ class StorageService {
   // return connent for file
   // return children for dir
   public getBlob = async (storageId: string, filePath: string) => {
+    if (filePath === 'This PC') {
+      const diskNames = ['C:/', 'D:/', 'E:/', 'F:/', 'G:/', 'H:/', 'I:/', 'J:/', 'K:/'].filter(n => fs.existsSync(n));
```
Comment (yeze322) [inline Composer/packages/server/src/services/storage.ts]: have you tested the behavior if I rename 'This PC' to another name?

Comment (yeze322) [reply Composer/packages/server/src/services/storage.ts]: image

Comment (liweitian) [reply Composer/packages/server/src/services/storage.ts]: This PC is a sample name. I think we just need a way for users to switch disk here.

Comment (yeze322) [reply Composer/packages/server/src/services/storage.ts]: At least we need to verify 2 scenarios to know your code's limitation:
1. does it work after user renamed the PC name?
2. does it work for users in different regions whose system language is not English?

Even if we don't care about these two scenarios, the string 'This PC' shouldn't be hard-coded and appears in two different files.

Comment (liweitian) [reply Composer/packages/server/src/services/storage.ts]: I updated code to take scenarios 2 into consideration and translated 'this PC'. It should be good now.

**Comment by cwhitten** [comment]
@liweitian please address conflicts

**Comment by liweitian** [comment]
> @liweitian please address conflicts

done

File: Composer/packages/lib/shared/src/constant.ts [hunk 3]
```diff
@@ -10,3 +11,5 @@ export const FieldNames = {
   DefaultCase: 'default',
   Cases: 'cases',
 };
+
+export const thisPC = formatMessage('This PC');
```
Comment (a-b-r-o-w-n) [inline Composer/packages/lib/shared/src/constant.ts]: This can't be statically export using `formatMessage`. You should see this in the browser console as a warning. Any usage of `formatMessage` must be at runtime because it uses runtime settings for determining the locale.

File: Composer/packages/server/src/services/storage.ts [hunk 4]
```diff
@@ -70,6 +72,20 @@ class StorageService {
   // return connent for file
   // return children for dir
   public getBlob = async (storageId: string, filePath: string, user?: UserIdentity) => {
+    if (filePath === thisPC) {
+      const diskNames = ['C:/', 'D:/', 'E:/', 'F:/', 'G:/', 'H:/', 'I:/', 'J:/', 'K:/'].filter(n => fs.existsSync(n));
```
Comment (a-b-r-o-w-n) [inline Composer/packages/server/src/services/storage.ts]: Couldn't disk names be arbitrary?

File: Composer/packages/lib/shared/src/constant.ts (hunk 3 above)
Comment (a-b-r-o-w-n) [reply Composer/packages/lib/shared/src/constant.ts]: Have you considered using `/` instead of `This PC`? I'm concerned that by translating this string at runtime, there may be some hidden bugs due to the translation. Also, the server is not configured for i18n at this point, so it would not get translated on the server.

Comment (boydc2014) [reply Composer/packages/lib/shared/src/constant.ts]: yes, i was also thinking about "/" don't require any extra explanation

File: Composer/packages/server/src/services/storage.ts (hunk 4 above)
Comment (boydc2014) [reply Composer/packages/server/src/services/storage.ts]: We should call some system api, if not, use some commands should also be fine.

File: Composer/packages/lib/shared/src/constant.ts (hunk 3 above)
Comment (liweitian) [reply Composer/packages/lib/shared/src/constant.ts]: switched to /.

File: Composer/packages/server/src/services/storage.ts (hunk 4 above)
Comment (liweitian) [reply Composer/packages/server/src/services/storage.ts]: Googled about this problem. Actually we cannot have an arbitrary names but we can change the label of disks. The Path C:/.../... won't change to Label:/.../... if we give it a label. So do we really need to show something like C:(label)/..?
Or are you suggesting I should remove the hard code here? I added a cmd script in env.ts which will get all disks names.
