### PR TITLE
fix: Display Orchestrator Selection Dialog for Local Skills

### LINKED ISSUE #7485: When adding a local bot to a project, Orchestrator should be installed
Similar to when connecting a remote skill, we should also run through the same installation steps to pull in Orchestrator when local bots are added to the project.

### PR DESCRIPTION
**Pull request by taicchoumsft**
## Description
Copy the Orchestrator Dialog to `modals.tsx`.  Fire the dialog at the end of the local skill flows.  Did not modify existing remote skill orch dialogs to avoid breaking an existing working scenario, so there is some small duplication.

## Task Item
fixes #7485

### CODE REVIEW

File: Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx [hunk 1]
```diff
@@ -1,62 +1,79 @@
...
+import { useRecoilValue } from 'recoil';
+
+import { dispatcherState } from '../../recoilModel';
+import { enableOrchestratorDialog } from '../../constants';
+
+import { importOrchestrator } from './helper';
+
+const learnMoreUrl = 'https://aka.ms/bf-composer-docs-publish-bot';
+
+interface OrchestratorProps {
```
Comment (hatpick) [inline Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx:19]: use type

File: Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx [hunk 2]
```diff
@@ -1,62 +1,79 @@
...
+        </Stack.Item>
+        <Stack.Item align="end">
+          <span>
+            <DefaultButton styles={{ root: { marginRight: '8px' } }} text={formatMessage('Skip')} onClick={onSubmit} />
+            <PrimaryButton
+              text={formatMessage('Continue')}
+              onClick={(event) => {
+                onSubmit(event, enableOrchestrator);
+                if (enableOrchestrator) {
+                  // TODO. show notification
```
Comment (hatpick) [inline Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx:61]: keep track of these TODOs via an issue and keep the issue number here in your TODO comment

File: Composer/packages/client/src/components/Orchestrator/OrchestratorForSkillsDialog.tsx [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+  designPageLocationState,
+  dispatcherState,
+  localeState,
+  orchestratorForSkillsDialogState,
+  rootBotProjectIdSelector,
+} from '../../recoilModel';
+import { recognizersSelectorFamily } from '../../recoilModel/selectors/recognizers';
+import { Orchestrator } from '../AddRemoteSkillModal/Orchestrator';
+
+export const OrchestratorForSkillsDialog = (props) => {
```
Comment (hatpick) [inline Composer/packages/client/src/components/Orchestrator/OrchestratorForSkillsDialog.tsx:20]: props is not used, remove it

File: Composer/packages/client/src/components/Orchestrator/OrchestratorForSkillsDialog.tsx [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+  const handleOrchestratorSubmit = async (event: any, enable?: boolean) => {
+    event.preventDefault();
+    if (enable) {
+      // update recognizor type to orchestrator
+      await updateRecognizer(rootProjectId, dialogId, SDKKinds.OrchestratorRecognizer);
+    }
+    setShowOrchestratorDialog(false);
+  };
+
+  const isVisible = () => {
```
Comment (hatpick) [inline Composer/packages/client/src/components/Orchestrator/OrchestratorForSkillsDialog.tsx:43]: this function is doing more than determining if something is visible or not, it's mutating a local state, can you name it better?

File: Composer/packages/client/src/components/Orchestrator/OrchestratorForSkillsDialog.tsx [hunk 5]
```diff
@@ -0,0 +1,76 @@
...
+
+  const onDismissHandler = (event: any) => {
+    setShowOrchestratorDialog(false);
+  };
+
+  return (
+    <DialogWrapper
+      dialogType={DialogTypes.CreateFlow}
+      isOpen={isVisible()}
+      subText={formatMessage('Enable Orchestrator as the recognizer at the root level to add this skill')}
```
Comment (hatpick) [inline Composer/packages/client/src/components/Orchestrator/OrchestratorForSkillsDialog.tsx:62]: nit: a better message to explain would be something like:
In order to add this skill, you must enable Orchestrator as the recognizer at the root level bot.
(check with UX folks)

File: Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx [hunk 6]
```diff
@@ -1,62 +1,79 @@
...
-                // TODO. update notification
-              }
-            }}
-          />
-        </span>
-      </Stack>
-    </Stack>
-  );
-};
+// Copyright (c) Microsoft Corporation.
```
Comment (hatpick) [inline Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx:1]: can you name this ```EnableOrchestrator``` or something like that? Orchestrator doesn't reflect the purpose of the component

File: Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx [hunk 7]
```diff
@@ -1,62 +1,79 @@
...
+import { Stack, StackItem } from 'office-ui-fabric-react/lib/Stack';
+import { PrimaryButton, DefaultButton } from 'office-ui-fabric-react/lib/Button';
+import { useRecoilValue } from 'recoil';
+
+import { dispatcherState } from '../../recoilModel';
+import { enableOrchestratorDialog } from '../../constants';
+
+import { importOrchestrator } from './helper';
+
+const learnMoreUrl = 'https://aka.ms/bf-composer-docs-publish-bot';
```
Comment (hatpick) [inline Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx:17]: this url has info about how to publish a bot, are you sure this is the right url?

File: Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx [hunk 8]
```diff
@@ -1,62 +1,79 @@
...
+
+interface OrchestratorProps {
+  projectId: string;
+  onSubmit: (event: any, userSelected?: boolean) => Promise<void>;
+  onBack: (event: any) => void;
```
Comment (hatpick) [inline Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx:22]: avoid any, use appropriate type

File: Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx [hunk 9]
```diff
@@ -1,62 +1,79 @@
...
+        <Checkbox
+          defaultChecked
+          label={formatMessage('Make Orchestrator my preferred recognizer for multi-bot projects')}
+          styles={{ root: { margin: '20px 0' } }}
+          onChange={onChange}
+        />
+      </StackItem>
+      <Stack horizontal horizontalAlign="space-between">
+        <Stack.Item>
+          {!props.hideBackButton && <DefaultButton text={formatMessage('Back')} onClick={onBack} />}
```
Comment (hatpick) [inline Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx:51]: nit: destructure hideBackButton and default it to false on line 27

Comment (hatpick) [reply Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx:51]: this will render the stack.item when hideBackButton is true, is that expected?

File: Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx [hunk 10]
```diff
@@ -1,62 +1,79 @@
...
+        </Stack.Item>
+        <Stack.Item align="end">
+          <span>
```
Comment (hatpick) [inline Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx:54]: why you need this span?

File: Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx [hunk 11]
```diff
@@ -1,62 +1,79 @@
...
+              }}
+            />
+          </span>
+        </Stack.Item>
+      </Stack>
+    </Stack>
+  );
+};
+
+Orchestrator.defaultProps = {
```
Comment (hatpick) [inline Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx:75]: It's more readable if you set the default value on top of the component code when you destructure it (my other comment)

File: Composer/packages/client/src/components/Orchestrator/OrchestratorForSkillsDialog.tsx [hunk 12]
```diff
@@ -0,0 +1,76 @@
...
+      title={formatMessage('Enable Orchestrator')}
+      onDismiss={onDismissHandler}
+    >
+      <Orchestrator
+        hideBackButton
+        projectId={rootProjectId}
+        onBack={() => {
```
Comment (hatpick) [inline Composer/packages/client/src/components/Orchestrator/OrchestratorForSkillsDialog.tsx:69]: you are hiding the back button then you have a callback for onBack? I'm confused.

**Review by hatpick — CHANGES_REQUESTED** [review]

File: Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx (hunk 1 above)
Comment (taicchoumsft) [reply Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx]: Addressed.

File: Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx (hunk 2 above)
Comment (taicchoumsft) [reply Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx]: Addressed. Ticket #7531 created to track this.

File: Composer/packages/client/src/components/Orchestrator/OrchestratorForSkillsDialog.tsx (hunk 3 above)
Comment (taicchoumsft) [reply Composer/packages/client/src/components/Orchestrator/OrchestratorForSkillsDialog.tsx]: done.

File: Composer/packages/client/src/components/Orchestrator/OrchestratorForSkillsDialog.tsx (hunk 4 above)
Comment (taicchoumsft) [reply Composer/packages/client/src/components/Orchestrator/OrchestratorForSkillsDialog.tsx]: renamed to `setVisible` for lack of imagination.

File: Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx (hunk 8 above)
Comment (taicchoumsft) [reply Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx]: addressed

File: Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx (hunk 9 above)
Comment (taicchoumsft) [reply Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx]: Thanks, done.  Yes rendering empty stack because without this empty element (when we hide the back button), the two rightmost buttons jump to the left.

File: Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx (hunk 10 above)
Comment (taicchoumsft) [reply Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx]: Didn't need it, thanks, it was in the original implementation, removed now after using `stack.item`.

File: Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx (hunk 11 above)
Comment (taicchoumsft) [reply Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx]: addressed. Removed this completely

File: Composer/packages/client/src/components/Orchestrator/OrchestratorForSkillsDialog.tsx (hunk 12 above)
Comment (taicchoumsft) [reply Composer/packages/client/src/components/Orchestrator/OrchestratorForSkillsDialog.tsx]: dumb mistake.  Removed the `onBack` handler here.  Thanks @hatpick  for great feedback.

File: Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx (hunk 7 above)
Comment (taicchoumsft) [reply Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx:17]: This was in original implementation done by remote skill crew, I'll check with UX team on this.

File: Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx (hunk 6 above)
Comment (taicchoumsft) [reply Composer/packages/client/src/components/AddRemoteSkillModal/Orchestrator.tsx]: Renamed.

**Review by hatpick — APPROVED** [review]

**Review by hatpick — APPROVED** [review]

**Review by hatpick — DISMISSED** [review]

**Review by cwhitten — APPROVED** [review]
